# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/14-agent-engineering/16-openai-agents-sdk
# Used in courses: AI-02, AI-19
# Framework: openai-agents
# Requires API key: False

"""agent-loop"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "/api/llm"  # same-origin proxy; server injects the gateway key
lrn_llm.DEFAULT_MODEL = "azure/gpt-5.4"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    _key = lrn_llm.API_KEY
    if _key:
        headers["Authorization"] = "Bearer " + _key
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key
#
# Optional: set your API key below. The LHIND gateway works without authentication on the local network.

# %%
lrn_llm.API_KEY = ""  # leave empty for gateway (no auth needed on LHIND network)
print(f"Endpoint: {lrn_llm.API_BASE}")
print(f"Model: {lrn_llm.DEFAULT_MODEL}")
print(f"Auth: {'custom key' if lrn_llm.API_KEY else 'no key (gateway mode)'}")

# %% [markdown]
# ## Step 1 — Reachability
#
# Test that the LLM gateway is reachable:

# %%
r = await lrn_llm.ping()
print(f"✅ LLM reachable: {r['ok']}")
print(f"Model: {r.get('model', 'unknown')}")

# %% [markdown]
# ## Step 2 — The OpenAI Agents SDK Shape
#
# The SDK has **five primitives**:
# 1. **Agent** — LLM + instructions + tools + handoffs
# 2. **Handoff** — Delegation to another agent (represented as a tool named `transfer_to_<agent>`)
# 3. **Guardrail** — Validation on input (first agent only), output (last agent only), or tool invocation
# 4. **Session** — Automatic conversation history
# 5. **Tracing** — Built-in spans for LLM calls, tool use, handoffs, guardrails
#
# We'll implement a **triage agent** that routes customer queries to **billing** or **support** specialists using real LLM calls.

# %%
from dataclasses import dataclass, field
from typing import Any, Callable

@dataclass
class Agent:
    """An agent: name, instructions, and tools/handoffs it can use."""
    name: str
    instructions: str
    tools: list['Tool'] = field(default_factory=list)
    handoffs: list['Handoff'] = field(default_factory=list)

@dataclass
class Handoff:
    """Delegation to another agent. The model sees it as a tool named transfer_to_<target>."""
    target: Agent
    
    @property
    def tool_name(self) -> str:
        return f"transfer_to_{self.target.name}"

@dataclass
class Tool:
    """A function tool the agent can call."""
    name: str
    description: str
    fn: Callable[..., str]

@dataclass
class GuardrailTripped(Exception):
    """Raised when a guardrail blocks input or output."""
    which: str  # 'input' or 'output'
    reason: str

print("✅ Agent SDK primitives defined")

# %% [markdown]
# ## Step 3 — Agent Runner with Guardrails
#
# The runner orchestrates the agent loop:
# - Runs input guardrails before any LLM call
# - Dispatches to agents and follows handoffs
# - Runs output guardrails on the final response
# - Emits a span tree for tracing

# %%
@dataclass
class InputGuardrail:
    """Validates user input before passing to the first agent."""
    name: str
    check: Callable[[str], tuple[bool, str]]  # returns (passed, reason)

@dataclass
class OutputGuardrail:
    """Validates the final output before returning to the user."""
    name: str
    check: Callable[[str], tuple[bool, str]]

@dataclass
class Span:
    """A trace span (LLM call, tool, handoff, guardrail)."""
    name: str
    attributes: dict[str, Any] = field(default_factory=dict)
    children: list['Span'] = field(default_factory=list)

print("✅ Guardrails and tracing types defined")

# %% [markdown]
# ## Step 4 — The Agent Runner Loop
#
# Now we implement the core runner that:
# 1. Checks input guardrails
# 2. Loops through agents, calling the LLM to decide: final answer, tool call, or handoff
# 3. Checks output guardrails
# 4. Emits traces

# %%
@dataclass
class Runner:
    """Orchestrates the multi-agent handoff loop with guardrails and tracing."""
    input_guardrails: list[InputGuardrail] = field(default_factory=list)
    output_guardrails: list[OutputGuardrail] = field(default_factory=list)
    max_hops: int = 3
    trace: Span = field(default_factory=lambda: Span(name="run"))
    
    async def run(self, agent: Agent, user_input: str) -> str:
        """Run an agent with handoff support, guardrails, and tracing."""
        # Check input guardrails
        for guard in self.input_guardrails:
            ok, reason = guard.check(user_input)
            span = Span(name=f"input_guardrail.{guard.name}",
                        attributes={"passed": ok, "reason": reason})
            self.trace.children.append(span)
            if not ok:
                raise GuardrailTripped(which="input", reason=reason)
        
        current_agent = agent
        current_input = user_input
        final_output = ""
        
        # Agent loop with handoff support
        for hop in range(self.max_hops):
            agent_span = Span(name=f"agent.{current_agent.name}",
                              attributes={"hop": hop,
                                          "instructions": current_agent.instructions[:50]})
            self.trace.children.append(agent_span)
            
            # Call the LLM to decide: final answer, tool call, or handoff?
            decision = await self._get_agent_decision(current_agent, current_input)
            kind = decision.get("kind")
            
            if kind == "final":
                final_output = decision["text"]
                agent_span.children.append(
                    Span(name="llm_generation",
                         attributes={"output": final_output[:80]})
                )
                break
            elif kind == "handoff":
                target_name = decision["to"]
                handoff = next((h for h in current_agent.handoffs
                                if h.target.name == target_name), None)
                if handoff is None:
                    final_output = f"error: no handoff to {target_name}"
                    break
                agent_span.children.append(
                    Span(name=f"handoff.{handoff.tool_name}",
                         attributes={"from": current_agent.name, "to": target_name})
                )
                current_agent = handoff.target
                current_input = decision.get("input", current_input)
                continue
            else:
                final_output = f"error: unexpected decision kind {kind}"
                break
        
        # Check output guardrails
        for guard in self.output_guardrails:
            ok, reason = guard.check(final_output)
            span = Span(name=f"output_guardrail.{guard.name}",
                        attributes={"passed": ok, "reason": reason})
            self.trace.children.append(span)
            if not ok:
                raise GuardrailTripped(which="output", reason=reason)
        
        return final_output
    
    async def _get_agent_decision(self, agent: Agent, user_input: str) -> dict[str, Any]:
        """Ask the LLM: final answer, tool call, or handoff?"""
        # Build the tool list from handoffs
        handoff_tools = [
            {"type": "function", "function": {"name": h.tool_name,
                                                 "description": f"Transfer to {h.target.name} agent"}}
            for h in agent.handoffs
        ]
        
        system = agent.instructions + "\n\nRespond with exactly one JSON line: {\"kind\": \"final\", \"text\": \"..\"} for a final answer, or {\"kind\": \"handoff\", \"to\": \"<agent_name>\", \"input\": \"..\"} to transfer."
        
        r = await lrn_llm.call(
            [{"role": "user", "content": user_input}],
            system=system,
            max_tokens=200
        )
        text = lrn_llm.text(r).strip()
        
        # Parse the LLM's JSON decision
        try:
            decision = json.loads(text)
            return decision
        except json.JSONDecodeError:
            # Fallback: treat as final answer
            return {"kind": "final", "text": text}

print("✅ Runner with LLM-based decision-making defined")

# %% [markdown]
# ## Step 5 — Define Guardrails
#
# We create input and output guardrails that validate the user's query and the agent's response:

# %%
def check_pii_input(text: str) -> tuple[bool, str]:
    """Block inputs that mention sensitive info (SSN, credit card)."""
    dangerous = ["ssn", "social security", "credit card", "ccn"]
    if any(d in text.lower() for d in dangerous):
        return False, "refuses: input contains PII keywords"
    return True, "ok"

def check_output_length(text: str) -> tuple[bool, str]:
    """Ensure output doesn't exceed 300 characters."""
    if len(text) > 300:
        return False, f"output too long: {len(text)} > 300 chars"
    return True, f"ok: {len(text)} chars"

print("✅ Guardrails defined")

# %% [markdown]
# ## Step 6 — Define Agents
#
# We create three agents:
# - **Triage**: routes queries to billing or support
# - **Billing**: handles refunds and invoices
# - **Support**: handles bugs and crashes

# %%
# Create the specialized agents (no tools for now, just handoffs/instructions)
billing_agent = Agent(
    name="billing",
    instructions="You handle refunds, invoices, and billing questions. Be helpful and professional."
)

support_agent = Agent(
    name="support",
    instructions="You handle bug reports, crashes, and technical errors. Be clear and supportive."
)

# Triage agent can handoff to both
triage_agent = Agent(
    name="triage",
    instructions="You are a customer service triage agent. Route queries to the right specialist. If the customer asks about refunds, invoices, or billing, handoff to billing. If they ask about bugs, crashes, or technical errors, handoff to support. Otherwise, try to help.",
    handoffs=[
        Handoff(target=billing_agent),
        Handoff(target=support_agent)
    ]
)

print("✅ Three agents created (triage, billing, support)")
print(f"   Triage can handoff to: {[h.tool_name for h in triage_agent.handoffs]}")

# %% [markdown]
# ## Step 7 — Create the Runner
#
# Now we create the runner with guardrails and run a test case:

# %%
runner = Runner(
    input_guardrails=[
        InputGuardrail("pii_block", check_pii_input)
    ],
    output_guardrails=[
        OutputGuardrail("length_cap", check_output_length)
    ],
    max_hops=3
)

print("✅ Runner created with:")
print(f"   Input guardrails: {[g.name for g in runner.input_guardrails]}")
print(f"   Output guardrails: {[g.name for g in runner.output_guardrails]}")
print(f"   Max hops: {runner.max_hops}")

# %% [markdown]
# ## Step 8 — Run a Real Case
#
# Test the triage agent with a billing query. Watch it make a real LLM call and decide whether to handoff or answer directly:

# %%
test_input = "I need a refund for invoice 4711 from last month."
print(f"User: {test_input}\n")

runner.trace = Span(name="run", attributes={"user_input": test_input[:60]})

try:
    output = await runner.run(triage_agent, test_input)
    print(f"✅ Final response:")
    print(f"{output}")
except GuardrailTripped as e:
    print(f"❌ GUARDRAIL TRIPPED ({e.which}): {e.reason}")

# %% [markdown]
# ## Step 9 — Show the Trace Tree
#
# The SDK emits a span tree that shows every LLM call, tool invocation, handoff, and guardrail check. This is the observability foundation:

# %%
def print_trace(span: Span, indent: int = 0) -> None:
    """Pretty-print the trace tree."""
    prefix = "  " * indent + "┣ " if indent > 0 else ""
    attrs = " | ".join(f"{k}={v!r}" for k, v in span.attributes.items())
    attr_str = f" ({attrs})" if attrs else ""
    print(f"{prefix}{span.name}{attr_str}")
    for child in span.children:
        print_trace(child, indent + 1)

print("Trace tree:")
print_trace(runner.trace)

# %% [markdown]
# ## Step 10 — Test an Input Guardrail Trip
#
# Now test a query that violates the PII guardrail (blocks SSN mentions before any LLM call):

# %%
bad_input = "can you confirm my ssn for my account?"
print(f"User: {bad_input}\n")

runner.trace = Span(name="run", attributes={"user_input": bad_input[:60]})

try:
    output = await runner.run(triage_agent, bad_input)
    print(f"Final response: {output}")
except GuardrailTripped as e:
    print(f"❌ GUARDRAIL TRIPPED ({e.which}): {e.reason}")
    print("\nTrace (showing the blocked guardrail):")
    print_trace(runner.trace)

# %% [markdown]
# ## Step 11 — Test a Support Query
#
# Test a technical support query (should handoff to support agent):

# %%
support_input = "The app keeps crashing when I open the settings menu. Any fix?"
print(f"User: {support_input}\n")

runner.trace = Span(name="run", attributes={"user_input": support_input[:60]})

try:
    output = await runner.run(triage_agent, support_input)
    print(f"✅ Final response:")
    print(f"{output}")
    print("\nTrace:")
    print_trace(runner.trace)
except GuardrailTripped as e:
    print(f"❌ GUARDRAIL TRIPPED ({e.which}): {e.reason}")

# %% [markdown]
# ## Step 12 — Key Takeaways
#
# The **OpenAI Agents SDK** codifies five primitives:
#
# 1. **Agent** — bundles instructions, tools, and handoffs
# 2. **Handoff** — represented as a tool (`transfer_to_<agent>`) the model can call
# 3. **Guardrail** — input/output/tool-level validation (trips with structured exceptions)
# 4. **Session** — conversation history (not shown here, but auto-managed in the real SDK)
# 5. **Tracing** — spans for every LLM call, tool invocation, handoff, guardrail
#
# Key patterns:
# - **Handoffs avoid prompt bloat**: each agent has focused instructions
# - **Guardrails prevent policy violations**: PII, length, tone, format
# - **Tracing enables debugging**: see exactly where the agent decided to handoff or what guardrail tripped
#
# Exercises from the lesson:
# 1. Add a hop counter to refuse after N transfers
# 2. Implement `nest_handoff_history` to summarize prior context before handoff
# 3. Write a blocking guardrail and compare latency vs parallel mode
# 4. Wire traces to a JSON logger; observe the span shape
# 5. Port this stdlib toy to the real `openai-agents-python` SDK

# %%
print("="*70)
print("OpenAI Agents SDK: Handoffs, Guardrails, Tracing")
print("="*70)
print("\n✅ All concepts demonstrated:")
print("  - Agents with instructions and handoffs")
print("  - Real LLM calls to decide final answer vs handoff")
print("  - Input/output guardrails with tripwire exceptions")
print("  - Span trees for observability")
print("\nNext steps:")
print("  1. Modify the triage instructions to test different routing logic")
print("  2. Add a tool that looks up customer info (mock or real)")
print("  3. Implement tool guardrails to validate tool arguments")
print("  4. Log traces to JSON and examine the span structure")

# %% [markdown]
# ## Try It Yourself
#
# Modify the scenario below and run your own agent interaction:

# %%
# TODO: Change this to test a different customer query
# Try variations: billing questions, support issues, out-of-scope requests
custom_input = "I can't log in to my account. I've tried resetting my password but it's not working."

print(f"Testing custom input: {custom_input}\n")
runner.trace = Span(name="run", attributes={"user_input": custom_input[:60]})

try:
    result = await runner.run(triage_agent, custom_input)
    print(f"✅ Result:\n{result}")
    print("\nTrace:")
    print_trace(runner.trace)
except GuardrailTripped as e:
    print(f"❌ Guardrail blocked ({e.which}): {e.reason}")
