# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/19-capstone-projects/29-end-to-end-coding-task-demo
# Used in courses: AI-02
# Framework: vanilla-openai
# Requires API key: False

"""notebook.ai-02.py"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "https://gateway.lhind.ai/v1"
lrn_llm.DEFAULT_MODEL = "azure/gpt-4o"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    _key = lrn_llm.API_KEY
    if not _key:
        try:
            import js as _js
            _key = getattr(_js, "__LRN_LLM_KEY__", "") or ""
        except Exception:
            _key = ""
    if _key:
        headers["Authorization"] = "Bearer " + _key
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key

# %%
# The LRN gateway is available on the LHIND network without a key.
# If you have a custom key, set it here:
lrn_llm.API_KEY = ""

print(f"Endpoint: {lrn_llm.API_BASE}")
print(f"Model: {lrn_llm.DEFAULT_MODEL}")
print(f"Key set: {bool(lrn_llm.API_KEY)}")

# %% [markdown]
# ## Step 1 — Reachability

# %%
r = await lrn_llm.ping()
print(f"✅ LLM erreichbar: {r}")

# %% [markdown]
# ## Overview: Agent Loop for Code Fixing
#
# In this notebook, we build an **agent loop** that fixes a buggy Python file using an LLM. The agent follows a deterministic **state machine** with five states:
#
# 1. **SURVEY**: Read the project structure and test file  
# 2. **RUN_TESTS**: Execute tests to see if they pass; if so, halt ✓  
# 3. **INSPECT**: Read the failing source file  
# 4. **FIX**: Ask the LLM to write a fix  
# 5. **VERIFY**: Run tests again; if they pass, halt ✓  
#
# Each step goes through a **harness** that enforces:
# - **Gate Chain**: Authorization rules (which tools are allowed)  
# - **Sandbox**: Execution isolation and safety  
# - **Observation Ledger**: Budget tracking (steps, tokens)  
# - **Span Builder**: Tracing and metrics  
#
# This mirrors the lesson's architecture, but uses a real LLM instead of a deterministic policy.

# %% [markdown]
# ## The Fixture: A Buggy fizz.py
#
# Our sample project has two files:
#
# **src/fizz.py** (buggy):
# ```python
# def fizzbuzz(n):
#     # Off-by-one bug: should return n+1 numbers, not n
#     result = []
#     for i in range(n):  # BUG: should be range(n+1)
#         if i % 15 == 0:
#             result.append("FizzBuzz")
#         elif i % 3 == 0:
#             result.append("Fizz")
#         elif i % 5 == 0:
#             result.append("Buzz")
#         else:
#             result.append(str(i))
#     return result
# ```
#
# **tests/test_fizz.py**:
# ```python
# from src.fizz import fizzbuzz
#
# def test_fizzbuzz():
#     result = fizzbuzz(5)
#     assert len(result) == 5, f"Expected 5 items, got {len(result)}"
#     assert result[4] == "Buzz", f"Expected result[4]='Buzz', got {result[4]}"
# ```
#
# The test expects 5 items (indices 0–4), but the buggy code only returns 4.

# %% [markdown]
# ## Step 2 — Harness Primitives
#
# We implement the minimal harness components (gate, sandbox, ledger, span).

# %%
import re
from datetime import datetime
from typing import Any, Dict, List

class GateChain:
    """Gate chain: authorize tool calls."""
    ALLOWED_TOOLS = {"read_file", "run_tests", "write_file"}
    
    @staticmethod
    def evaluate(tool_name: str) -> bool:
        return tool_name in GateChain.ALLOWED_TOOLS

class Sandbox:
    """Sandbox: simulated file system and test execution."""
    def __init__(self):
        self.files = {
            "src/fizz.py": '''def fizzbuzz(n):
    result = []
    for i in range(n):  # BUG: should be range(n+1)
        if i % 15 == 0:
            result.append("FizzBuzz")
        elif i % 3 == 0:
            result.append("Fizz")
        elif i % 5 == 0:
            result.append("Buzz")
        else:
            result.append(str(i))
    return result
''',
            "tests/test_fizz.py": '''from src.fizz import fizzbuzz

def test_fizzbuzz():
    result = fizzbuzz(5)
    assert len(result) == 5, f"Expected 5 items, got {len(result)}"
    assert result[4] == "Buzz", f"Expected result[4]=\'Buzz\', got {result[4]}"
'''
        }
    
    def read_file(self, path: str) -> str:
        if path not in self.files:
            return f"Error: file {path} not found"
        return self.files[path]
    
    def write_file(self, path: str, content: str) -> str:
        self.files[path] = content
        return f"OK: wrote {path}"
    
    def run_tests(self) -> Dict[str, Any]:
        """Simulate running tests; fails on the buggy code."""
        try:
            exec_globals = {}
            exec(self.files["src/fizz.py"], exec_globals)
            fizzbuzz = exec_globals["fizzbuzz"]
            result = fizzbuzz(5)
            if len(result) == 5:
                return {"passed": True, "message": "All tests passed!"}
            else:
                return {
                    "passed": False,
                    "error": f"AssertionError: Expected 5 items, got {len(result)}"
                }
        except Exception as e:
            return {"passed": False, "error": str(e)}

print("✅ Harness primitives loaded")

# %% [markdown]
# ## Step 3 — Agent State Machine
#
# We define the agent's five states and the LLM-powered policy.

# %%
class AgentState:
    """Agent state: tracks current state, observations, and step budget."""
    def __init__(self):
        self.state = "SURVEY"
        self.observations = []
        self.steps = 0
        self.max_steps = 10
        self.messages = []  # conversation history for LLM
    
    def add_observation(self, obs: str):
        self.observations.append(obs)
        self.steps += 1
    
    def within_budget(self) -> bool:
        return self.steps < self.max_steps
    
    def transition(self, next_state: str):
        self.state = next_state

class ObservationLedger:
    """Observation ledger: track tool calls and budgets."""
    def __init__(self):
        self.calls = []
        self.tokens_used = 0
    
    def log_call(self, tool: str, result: str, tokens: int = 0):
        self.calls.append({"tool": tool, "result": result[:100], "tokens": tokens})
        self.tokens_used += tokens

class SpanBuilder:
    """Span builder: emit traces for each step."""
    def __init__(self):
        self.spans = []
    
    def start_span(self, name: str) -> Dict:
        span = {"name": name, "start": datetime.now().isoformat()}
        self.spans.append(span)
        return span
    
    def end_span(self, span: Dict, status: str = "OK"):
        span["end"] = datetime.now().isoformat()
        span["status"] = status

print("✅ Agent state machine defined")

# %% [markdown]
# ## Step 4 — Survey State
#
# The agent's first step: read the project structure.

# %%
async def survey_phase(state: AgentState, sandbox: Sandbox) -> str:
    """SURVEY: Read the project structure."""
    tool = "read_file"
    
    # Check gate
    if not GateChain.evaluate(tool):
        state.add_observation(f"❌ Tool {tool} denied by gate")
        return None
    
    # Execute in sandbox
    project_files = "\n".join(sandbox.files.keys())
    observation = f"Project structure:\n{project_files}"
    state.add_observation(observation)
    state.messages.append({"role": "assistant", "content": f"I read the project files: {project_files}"})
    
    print(f"[SURVEY] {observation}")
    state.transition("RUN_TESTS")
    return observation

await survey_phase(AgentState(), Sandbox())
print("✅ Survey phase works")

# %% [markdown]
# ## Step 5 — Run Tests State
#
# The agent runs tests to see if the code is working.

# %%
async def run_tests_phase(state: AgentState, sandbox: Sandbox) -> bool:
    """RUN_TESTS: Execute tests. Return True if passed, False otherwise."""
    tool = "run_tests"
    
    if not GateChain.evaluate(tool):
        state.add_observation(f"❌ Tool {tool} denied by gate")
        return False
    
    result = sandbox.run_tests()
    state.add_observation(f"Test result: {result}")
    state.messages.append({
        "role": "assistant",
        "content": f"Tests ran: {result['message'] if result.get('passed') else result.get('error')}"
    })
    
    if result["passed"]:
        print(f"[RUN_TESTS] ✅ Tests PASSED")
        return True
    else:
        print(f"[RUN_TESTS] ❌ Tests FAILED: {result['error']}")
        state.transition("INSPECT")
        return False

# Simulate the test phase
state = AgentState()
sandbox = Sandbox()
await run_tests_phase(state, sandbox)
print(f"State transitioned to: {state.state}")

# %% [markdown]
# ## Step 6 — Inspect & Fix States (LLM-Powered)
#
# When tests fail, the agent reads the source and asks the LLM to identify and fix the bug.

# %%
async def inspect_and_fix_phase(state: AgentState, sandbox: Sandbox) -> str:
    """INSPECT: Read the failing source. Then FIX: Ask LLM to write a fix."""
    
    # --- INSPECT ---
    tool = "read_file"
    if not GateChain.evaluate(tool):
        state.add_observation(f"❌ Tool {tool} denied")
        return None
    
    source_code = sandbox.read_file("src/fizz.py")
    state.add_observation(f"Source code read (length={len(source_code)})")
    print(f"[INSPECT] Read src/fizz.py ({len(source_code)} chars)")
    state.transition("FIX")
    
    # --- FIX: Ask LLM ---
    state.messages.append({
        "role": "user",
        "content": f"""The test failed with: 'Expected 5 items, got 4'.

Here's the source code:
```python
{source_code}
```

Identify the off-by-one bug and provide the fixed version (Python code only, no explanation)."""
    })
    
    resp = await lrn_llm.call(state.messages, max_tokens=300)
    fixed_code = lrn_llm.text(resp).strip()
    
    # Try to extract Python code from markdown if present
    if "```python" in fixed_code:
        fixed_code = fixed_code.split("```python")[1].split("```")[0].strip()
    elif "```" in fixed_code:
        fixed_code = fixed_code.split("```")[1].split("```")[0].strip()
    
    print(f"[FIX] LLM provided fix ({len(fixed_code)} chars)")
    state.add_observation(f"LLM provided fix")
    state.messages.append({"role": "assistant", "content": fixed_code})
    
    return fixed_code

print("✅ Inspect & Fix phase ready (uses real LLM)")

# %% [markdown]
# ## Step 7 — Write & Verify (Complete the Loop)
#
# Write the fixed code and verify the tests pass.

# %%
async def write_and_verify_phase(state: AgentState, sandbox: Sandbox, fixed_code: str) -> bool:
    """Write the fixed code and verify tests pass."""
    
    # --- WRITE ---
    tool = "write_file"
    if not GateChain.evaluate(tool):
        state.add_observation(f"❌ Tool {tool} denied")
        return False
    
    result = sandbox.write_file("src/fizz.py", fixed_code)
    state.add_observation(result)
    print(f"[WRITE] {result}")
    state.transition("VERIFY")
    
    # --- VERIFY ---
    tool = "run_tests"
    if not GateChain.evaluate(tool):
        state.add_observation(f"❌ Tool {tool} denied")
        return False
    
    result = sandbox.run_tests()
    state.add_observation(f"Verify result: {result}")
    
    if result["passed"]:
        print(f"[VERIFY] ✅ Tests PASSED - bug fixed!")
        return True
    else:
        print(f"[VERIFY] ❌ Tests still failing: {result['error']}")
        return False

print("✅ Write & Verify phase ready")

# %% [markdown]
# ## Step 8 — End-to-End Agent Run
#
# Now run the complete agent loop: SURVEY → RUN_TESTS → INSPECT → FIX → VERIFY.

# %%
async def run_agent():
    """Execute the full agent loop."""
    state = AgentState()
    sandbox = Sandbox()
    ledger = ObservationLedger()
    span = SpanBuilder()
    
    print("\n" + "="*60)
    print("START: End-to-End Coding Agent")
    print("="*60 + "\n")
    
    # SURVEY
    await survey_phase(state, sandbox)
    
    # RUN_TESTS (first time)
    tests_passed = await run_tests_phase(state, sandbox)
    
    if not tests_passed:
        # INSPECT & FIX
        fixed_code = await inspect_and_fix_phase(state, sandbox)
        if not fixed_code:
            print("ERROR: LLM did not provide valid code")
            return False
        
        # WRITE & VERIFY
        success = await write_and_verify_phase(state, sandbox, fixed_code)
    else:
        success = True
    
    # Summary
    print("\n" + "="*60)
    print(f"RESULT: {'✅ SUCCESS' if success else '❌ FAILED'}")
    print(f"Steps taken: {state.steps}")
    print(f"Final state: {state.state}")
    print(f"Observations: {len(state.observations)}")
    print("="*60 + "\n")
    
    return success

success = await run_agent()
print(f"\nAgent run completed with success={success}")

# %% [markdown]
# ## Try it yourself
#
# Modify the LLM's system prompt or the test case below. Can you make the agent fix a different type of bug?

# %%
# TODO: Experiment!
# Try changing the bug in sandbox.files["src/fizz.py"] or the test assertion,
# then re-run the agent. What happens if the bug is more complex?
# For example, change the FizzBuzz logic or add a new test.

# Example: modify the test to be stricter
# Uncomment the line below and re-run run_agent():
# sandbox.files["tests/test_fizz.py"] = '''from src.fizz import fizzbuzz
# def test_fizzbuzz():
#     result = fizzbuzz(15)
#     assert len(result) == 15
#     assert result[0] == "FizzBuzz"
#     assert result[3] == "Fizz"
#     assert result[4] == "Buzz"
# '''

print("Ready for experimentation. Modify the code above and run the agent again.")
