# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/14-agent-engineering/02-rewoo-plan-and-execute
# Used in courses: AI-02
# Framework: none
# Requires API key: False

"""agent-loop"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "/api/llm"  # same-origin proxy; server injects the gateway key
lrn_llm.DEFAULT_MODEL = "azure/gpt-5.4-mini"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    _key = lrn_llm.API_KEY
    if _key:
        headers["Authorization"] = "Bearer " + _key
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key
#
# The gateway is on the LHIND network — no API key required. Leave it blank. Verify the endpoint and model below:

# %%
lrn_llm.API_KEY = ""  # optional; leave blank for LHIND network
print(f"Endpoint: {lrn_llm.API_BASE}")
print(f"Model: {lrn_llm.DEFAULT_MODEL}")
print(f"Using key: {bool(lrn_llm.API_KEY)}")

# %% [markdown]
# ## Step 1 — Reachability
#
# Ping the LLM to confirm the connection works:

# %%
r = await lrn_llm.ping()
print(f"✅ LLM erreichbar: {r['ok']}")
print(f"Model: {r['model']}")

# %% [markdown]
# ## Step 2 — ReWOO: The Problem with ReAct
#
# ReAct interleaves thought and action in one loop — but each step carries the full prior context, causing **quadratic token growth** and making **failure recovery hard**.
#
# ReWOO solves this by separating concerns:
# 1. **Planner** — emits a DAG of steps with references up front (no observations yet)
# 2. **Workers** — execute each step in dependency order (tools, parallel-safe)
# 3. **Solver** — composes the final answer from question + plan + evidence
#
# Result: **5x fewer tokens** + **clearer failure modes** on structured tasks.
#
# Let's build a toy ReWOO agent that answers: *"What is the population of the capital of France, rounded to millions?"*

# %%
import re
from dataclasses import dataclass
from typing import Any

@dataclass
class PlanStep:
    """A single step in the plan DAG."""
    id: str          # E1, E2, E3, ...
    tool: str        # what to call (e.g., 'search')
    args: dict       # arguments, may contain #E1, #E2 references

@dataclass
class Plan:
    """A complete plan DAG."""
    steps: list[PlanStep]

print("✅ Plan classes defined")

# %% [markdown]
# ## Step 3 — The Planner (LLM-driven)
#
# The planner reads the user question and emits a DAG. For this demo, we'll ask the LLM to generate the plan in a structured format, then parse it.

# %%
question = "What is the population of the capital of France, rounded to millions?"

# Ask the planner to create a step-by-step plan
plan_prompt = f"""Given the question: {question}

Create a step-by-step plan using search and rounding tools. Format each step as:
E<N>: <tool>(<arg1>="<val1>", <arg2>="<val2>")

Example:
E1: search(query="capital of France")
E2: search(query="population of #E1")
E3: round_million(text="#E2")

Use #E<N> to reference earlier step outputs."""

plan_resp = await lrn_llm.call(
    [{"role": "user", "content": plan_prompt}],
    system="You are a planning expert. Emit a minimal, acyclic DAG of search and rounding steps.",
    max_tokens=200
)

plan_text = lrn_llm.text(plan_resp)
print("Planner output:")
print(plan_text)

# %% [markdown]
# ## Step 4 — Parse the Plan
#
# Now we parse the planner's output into our `Plan` dataclass:

# %%
def parse_plan(text: str) -> Plan:
    """Parse planner output into a DAG."""
    steps = []
    # Match lines like: E1: search(query="...")
    pattern = r'E(\d+):\s+(\w+)\(([^)]+)\)'
    for match in re.finditer(pattern, text):
        step_num = match.group(1)
        tool = match.group(2)
        args_str = match.group(3)
        # Parse key="value" pairs (simple)
        args = {}
        for kv in re.findall(r'(\w+)="([^"]+)"', args_str):
            args[kv[0]] = kv[1]
        steps.append(PlanStep(f"E{step_num}", tool, args))
    return Plan(steps)

plan = parse_plan(plan_text)
print(f"Parsed {len(plan.steps)} steps:")
for step in plan.steps:
    print(f"  {step.id}: {step.tool}({step.args})")

# %% [markdown]
# ## Step 5 — Dependency Resolution
#
# Before we execute, we need to resolve references like `#E1` and execute steps in topological order:

# %%
REFERENCE_RE = re.compile(r"#E(\d+)")

def resolve_references(value: Any, evidence: dict[str, str]) -> Any:
    """Replace #E1, #E2, ... with actual values from evidence."""
    if not isinstance(value, str):
        return value
    return REFERENCE_RE.sub(lambda m: evidence.get(f"E{m.group(1)}", m.group(0)), value)

def topological(plan: Plan) -> list[PlanStep]:
    """Return steps in dependency order (no cycles)."""
    resolved = []
    known = set()
    pending = list(plan.steps)
    
    while pending:
        progress = False
        rest = []
        for step in pending:
            # Check if all #E<N> references are already computed
            refs = REFERENCE_RE.findall(str(step.args))
            if all(f"E{r}" in known for r in refs):
                resolved.append(step)
                known.add(step.id)
                progress = True
            else:
                rest.append(step)
        if not progress:
            raise RuntimeError("Cyclic or unresolved references in plan")
        pending = rest
    return resolved

ordered = topological(plan)
print(f"Topological order:")
for step in ordered:
    print(f"  {step.id}: {step.tool}")

# %% [markdown]
# ## Step 6 — Execute Workers (with Real LLM Calls)
#
# Now we execute each step by asking the LLM to perform the tool action (search, round, etc.):

# %%
async def worker_search(query: str) -> str:
    """Worker: search for a query."""
    resp = await lrn_llm.call(
        [{"role": "user", "content": f"Search query: {query}\nProvide a short factual answer."}],
        system="You are a search engine. Answer factually and concisely.",
        max_tokens=100
    )
    return lrn_llm.text(resp).strip()

async def worker_round_million(text: str) -> str:
    """Worker: extract a number and round to millions."""
    resp = await lrn_llm.call(
        [{"role": "user", "content": f"From this text: '{text}'\nExtract the number and round to millions. Reply only with '<N> million'."  }],
        system="Extract numbers and round them.",
        max_tokens=20
    )
    return lrn_llm.text(resp).strip()

print("✅ Worker functions defined")

# %%
async def run_workers(plan: Plan) -> dict[str, str]:
    """Execute all plan steps in topological order."""
    evidence = {}
    for step in topological(plan):
        # Resolve references in args
        bound_args = {k: resolve_references(v, evidence) for k, v in step.args.items()}
        print(f"\n→ Executing {step.id}: {step.tool}({bound_args})")
        
        # Call the appropriate worker
        if step.tool == "search":
            result = await worker_search(bound_args["query"])
        elif step.tool == "round_million":
            result = await worker_round_million(bound_args["text"])
        else:
            result = f"error: unknown tool {step.tool}"
        
        evidence[step.id] = result
        print(f"  → {step.id} = {result}")
    
    return evidence

evidence = await run_workers(plan)
print("\n" + "="*50)
print("EVIDENCE COLLECTED")
for k, v in evidence.items():
    print(f"  {k}: {v}")

# %% [markdown]
# ## Step 7 — Solver: Compose the Final Answer
#
# Now the solver reads the original question, the plan, and the evidence to generate the final answer:

# %%
# Build a context for the solver
solver_context = f"""Question: {question}

Plan that was executed:
"""
for step in plan.steps:
    solver_context += f"\n  {step.id}: {step.tool}({step.args})"

solver_context += f"\n\nEvidence from execution:\n"
for k, v in evidence.items():
    solver_context += f"  {k}: {v}\n"

solver_prompt = solver_context + "\n\nCompose a clear, one-sentence final answer to the original question."

solver_resp = await lrn_llm.call(
    [{"role": "user", "content": solver_prompt}],
    system="You are a solver. Compose a final answer from evidence and the plan.",
    max_tokens=100
)

final_answer = lrn_llm.text(solver_resp).strip()
print("FINAL ANSWER:")
print(final_answer)

# %% [markdown]
# ## Step 8 — ReWOO vs ReAct: Token Comparison
#
# Let's compare token usage between ReWOO (what we just did) and a hypothetical ReAct approach:

# %%
# ReWOO token estimate (char count as proxy)
planner_tokens = len(plan_prompt) + len(plan_text)
worker_tokens = sum(
    len(f"Search: {bound_args.get('query', '')}") + len(v)
    for step in plan.steps
    for bound_args in [{k: resolve_references(v, evidence) for k, v in step.args.items()}]
    for k, v in evidence.items()
    if step.id == k
)
solver_tokens = len(solver_context) + len(final_answer)
rewoo_total = planner_tokens + worker_tokens + solver_tokens

# ReAct would need the full context at each step
react_estimated = len(question)
for i in range(len(plan.steps)):
    # Each ReAct step includes the original question + all prior steps + the new action
    react_estimated += len(question) + 200 + 100  # rough per-step overhead
react_estimated += len(final_answer)

print(f"ReWOO token estimate (chars): {rewoo_total}")
print(f"  Planner: {planner_tokens}")
print(f"  Workers: {worker_tokens}")
print(f"  Solver: {solver_tokens}")
print(f"\nReAct estimated (chars): {react_estimated}")
print(f"Ratio (ReAct / ReWOO): {react_estimated / max(rewoo_total, 1):.1f}x")
print(f"\nNote: On HotpotQA, the ReWOO paper measured ~5x fewer tokens.")

# %% [markdown]
# ## Summary: Why ReWOO Wins
#
# 1. **Tokens**: One planner LLM call (emits the whole plan), N worker calls (just dispatch), one solver call. ReAct repeats the question at every step.
# 2. **Robustness**: If a worker fails, the solver sees the error in context with the plan. In ReAct, the loop has to recover mid-stream.
# 3. **Parallelism**: Independent plan nodes can run in parallel. ReAct is strictly sequential.
# 4. **Tradeoff**: The plan is static — you can't react to early observations. Use ReWOO for structured tasks; use ReAct for exploratory ones.
#
# ReWOO + a small planner model = cost-effective agents that still deliver high quality.

# %% [markdown]
# ## Try it yourself
#
# Modify the question and rebuild the notebook to see how the planner reacts. Try a different domain — maybe "What is the total GDP of Scandinavian countries?" or "Find the birth date of the inventor of the internet."
#
# TODO: Change `question` in the cell below and re-run cells 3–7 to see the planner adapt.

# %%
# TODO: Edit this question and re-run the entire workflow
new_question = "What is the birth year of the inventor of the World Wide Web?"

# Re-run the planner with this new question:
plan_prompt = f"""Given the question: {new_question}

Create a step-by-step plan. Format each step as:
E<N>: <tool>(<arg1>="<val1>")

Example:
E1: search(query="inventor of the World Wide Web")
E2: search(query="birth year of #E1")

Use #E<N> to reference earlier step outputs."""

plan_resp = await lrn_llm.call(
    [{"role": "user", "content": plan_prompt}],
    system="You are a planning expert. Emit a minimal, acyclic DAG.",
    max_tokens=200
)

plan_text = lrn_llm.text(plan_resp)
print("Planner output for new question:")
print(plan_text)
