# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/14-agent-engineering/13-langgraph-stateful-graphs
# Used in courses: AI-02, AI-19
# Framework: none
# Requires API key: False

"""agent-loop"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "/api/llm"  # same-origin proxy; server injects the gateway key
lrn_llm.DEFAULT_MODEL = "azure/gpt-5.4-mini"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    _key = lrn_llm.API_KEY
    if _key:
        headers["Authorization"] = "Bearer " + _key
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key

# %%
lrn_llm.API_KEY = ""  # leave empty on LHIND network; set your key here if needed
print(f"Endpoint: {lrn_llm.API_BASE}")
print(f"Model: {lrn_llm.DEFAULT_MODEL}")
print(f"API Key set: {bool(lrn_llm.API_KEY)}")

# %% [markdown]
# ## Step 1 — Reachability

# %%
r = await lrn_llm.ping()
print(f"✅ LLM erreichbar: {r}")

# %% [markdown]
# ## The Problem & Solution
#
# When a multi-step agent run fails at step 38, you want to **resume from step 38**, not restart from step 1.
#
# **LangGraph's answer:** State is immutable, mutations explicit, and **checkpoints persist after every node**. Resume is a `load(session_id)` call.
#
# We'll build a **support ticket routing system** with:
# - **Classify** (LLM-powered): route customer input → refund / bug / sales
# - **Create Ticket**: store the routing decision  
# - **Human Gate**: pause for approval (simulated)
# - **Send**: finalize and output
#
# The trick: serialize state after every step so we can resume exactly where we left off.

# %% [markdown]
# ## Step 2 — State & Graph Structure
#
# Define the **state** (what flows through the graph) and the **node functions** (pure functions that read and update state).

# %%
import copy
from typing import Any

# State is a typed dict with all info the agent needs
State = dict[str, Any]

# Node function: takes state, returns an update dict
# The runner merges updates into state after each node
def classify_node(state: State) -> dict:
    """Mark that classify ran (real classify happens in Step 3)."""
    return {"step": state.get("step", 0) + 1}

def create_ticket_node(state: State) -> dict:
    """Create a ticket ID based on the route."""
    route = state.get("route", "unknown")
    ticket_id = f"{route[:3].upper()}-{abs(hash(state['input']))%1000}"
    return {"ticket_id": ticket_id, "step": state.get("step", 0) + 1}

def human_gate_node(state: State) -> dict:
    """Check if human approved; if not, pause execution."""
    if not state.get("human_approved", False):
        # Signal the runner to pause and await external input
        return {"_pause_reason": "awaiting human approval", 
                "step": state.get("step", 0) + 1}
    return {"step": state.get("step", 0) + 1}

def send_node(state: State) -> dict:
    """Finalize and produce output."""
    output = f"Sent ticket {state.get('ticket_id')} ({state.get('route')}) to queue"
    return {"output": output, "step": state.get("step", 0) + 1}

print("✅ Nodes defined")

# %% [markdown]
# ## Step 3 — LLM-Powered Classification
#
# Call the LLM to classify the customer input into a **route** (refund, bug, or sales).

# %%
async def classify_with_llm(customer_input: str) -> str:
    """Use LLM to classify customer input into a route."""
    messages = [
        {"role": "user", "content": customer_input}
    ]
    system_prompt = (
        "You are a support ticket router. Classify the customer input into EXACTLY ONE category: "
        "refund, bug, or sales. Reply with only the word (e.g., 'refund'). "
        "refund: money back, charges, billing. "
        "bug: crash, error, broken. "
        "sales: pricing, quote, features."
    )
    resp = await lrn_llm.call(messages, system=system_prompt, max_tokens=10)
    route = lrn_llm.text(resp).strip().lower()
    # Validate the response
    if route not in ["refund", "bug", "sales"]:
        route = "sales"  # default fallback
    return route

# Test with a single example
test_input = "The app crashes when I try to export a PDF"
test_route = await classify_with_llm(test_input)
print(f"Input: {test_input}")
print(f"Route: {test_route}")

# %% [markdown]
# ## Step 4 — In-Memory Checkpointer
#
# After each node, save the **entire state** so we can resume from any failure.

# %%
class InMemoryCheckpointer:
    """Simple checkpoint store: saves state after every node."""
    def __init__(self):
        self._store = {}
    
    def save(self, session_id: str, node_name: str, state: State) -> None:
        """Save state snapshot after node execution."""
        if session_id not in self._store:
            self._store[session_id] = []
        self._store[session_id].append((node_name, copy.deepcopy(state)))
    
    def load_latest(self, session_id: str) -> tuple[str, State] | None:
        """Load the most recent checkpoint for a session."""
        history = self._store.get(session_id, [])
        return history[-1] if history else None
    
    def history(self, session_id: str) -> list:
        """Show all checkpoints for debugging."""
        return list(self._store.get(session_id, []))

ckpt = InMemoryCheckpointer()
print("✅ Checkpointer ready")

# %% [markdown]
# ## Step 5 — Graph Execution with Pause/Resume
#
# The **Runner** executes nodes sequentially, checkpoints state, and can **pause** when a human decision is needed.

# %%
class PausedAtNode(Exception):
    """Raised when graph pauses waiting for human input."""
    def __init__(self, node: str, state: State):
        super().__init__(node)
        self.node = node
        self.state = state

class Runner:
    """Executes the graph with checkpoint and pause/resume."""
    def __init__(self, checkpointer: InMemoryCheckpointer):
        self.checkpointer = checkpointer
    
    async def run(self, session_id: str, initial_state: State, 
                  resume_from: str | None = None,
                  llm_classify: bool = True) -> State:
        """Run the graph: classify -> create_ticket -> human_gate -> send."""
        state = copy.deepcopy(initial_state)
        
        # Determine where to start
        nodes_order = ["classify", "create_ticket", "human_gate", "send"]
        start_idx = 0
        if resume_from:
            try:
                start_idx = nodes_order.index(resume_from)
            except ValueError:
                raise RuntimeError(f"Unknown node: {resume_from}")
        
        for node_name in nodes_order[start_idx:]:
            # Run the appropriate node
            if node_name == "classify":
                if llm_classify and "route" not in state:
                    route = await classify_with_llm(state["input"])
                    update = {"route": route, "step": state.get("step", 0) + 1}
                else:
                    update = classify_node(state)
            elif node_name == "create_ticket":
                update = create_ticket_node(state)
            elif node_name == "human_gate":
                update = human_gate_node(state)
            elif node_name == "send":
                update = send_node(state)
            
            # Merge update into state
            state = {**state, **update}

            # Check for pause signal and clear it before checkpointing, so a
            # resumed run that reloads this checkpoint doesn't see a stale
            # _pause_reason and immediately re-pause on the next node.
            paused = state.pop("_pause_reason", None)

            # Checkpoint after node
            self.checkpointer.save(session_id, node_name, state)

            if paused:
                raise PausedAtNode(node_name, state)
        
        return state

print("✅ Runner ready")

# %% [markdown]
# ## Step 6 — First Run: Pause at Human Gate
#
# Run the graph with a customer input. It will classify (via LLM), create a ticket, then **pause** at the human gate because no human approval is set yet.

# %%
runner = Runner(ckpt)

session_id = "s001"
initial_state = {
    "input": "I was charged twice for my subscription last month, please refund",
    "step": 0,
    "human_approved": False
}

print("=" * 70)
print("FIRST RUN (will pause at human_gate)")
print("=" * 70)

try:
    final = await runner.run(session_id, initial_state, llm_classify=True)
    print(f"Completed: {final}")
except PausedAtNode as paused:
    print(f"\n🛑 PAUSED at node: {paused.node}")
    print(f"\nState at pause:")
    for key, value in paused.state.items():
        print(f"  {key}: {value}")

# %% [markdown]
# ## Step 7 — Review the Checkpoint History
#
# Inspect every step the graph took before pausing. This is where **durable execution** shines: if the graph crashed at step 4, we'd resume from step 4 with exact state.

# %%
print("\nCheckpoint history (every node saves state):")
print("-" * 70)
for i, (node_name, snap) in enumerate(ckpt.history(session_id), 1):
    print(f"Step {i}: {node_name}")
    print(f"  route={snap.get('route')} ticket_id={snap.get('ticket_id')} step={snap.get('step')}")

# %% [markdown]
# ## Step 8 — Resume After Human Approval
#
# A human reviews the paused state and approves it. We then **resume** from the next node with the updated state.

# %%
print("\nHuman approves the refund ticket. Running the final step...")
print("=" * 70)

# Resume must start from the *checkpointed* state, not the original initial_state —
# the Runner doesn't reload checkpoints itself, so we load(session_id) to get the
# state as of the pause, then hand it back to the Runner to continue the pipeline.
latest_node, paused_state = ckpt.load_latest(session_id)
print(f"Last checkpoint was at: {latest_node}")

approved_state = copy.deepcopy(paused_state)
approved_state["human_approved"] = True

# Resume through the Runner itself: resume_from="send" tells it to continue the
# pipeline at the node right after human_gate, instead of restarting from classify.
approved_state = await runner.run(session_id, approved_state, resume_from="send")

print(f"\n✅ Final output: {approved_state.get('output')}")
print(f"\nFinal state summary:")
print(f"  Input: {approved_state.get('input')}")
print(f"  Route (via LLM): {approved_state.get('route')}")
print(f"  Ticket ID: {approved_state.get('ticket_id')}")
print(f"  Human approved: {approved_state.get('human_approved')}")
print(f"  Final output: {approved_state.get('output')}")

# %% [markdown]
# ## Step 9 — The Key Insight
#
# **State is serialized after every node.** On failure at step 3, the graph resumes from step 3 with exact state. No fresh re-runs, no lost context, no data races.

# %%
print("\nFull execution trace with checkpoints:")
print("=" * 70)
all_history = ckpt.history(session_id)
for i, (node_name, snap) in enumerate(all_history, 1):
    print(f"{i}. {node_name}")
    print(f"   step count: {snap.get('step')}")
    print(f"   pause? {snap.get('_pause_reason', 'no')}")

print("\n" + "=" * 70)
print("PROPERTY: State checkpoint after every node → resume is exact.")
print("No fresh re-runs when step 38 fails; pick up at step 39.")
print("=" * 70)

# %% [markdown]
# ## Try It Yourself
#
# Modify the customer input below and run the graph. Watch how the LLM classifies it differently.

# %%
# TODO: Try a different customer input
# Examples:
#   - "Can you tell me about your enterprise pricing?"
#   - "The app keeps crashing on iOS"
#   - "I want my money back immediately"

test_input = "Can you send me a quote for 50 licenses?"
print(f"Classifying: {test_input}")
test_route = await classify_with_llm(test_input)
print(f"Route: {test_route}")
print(f"\nTry changing test_input to see different classifications.")
