# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/11-llm-engineering/09-function-calling
# Used in courses: LRN-02
# Framework: vanilla-openai
# Requires API key: False

"""tool_calling"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "/api/llm"  # same-origin proxy; server injects the gateway key
lrn_llm.DEFAULT_MODEL = "azure/gpt-5.4-mini"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    _key = lrn_llm.API_KEY
    if _key:
        headers["Authorization"] = "Bearer " + _key
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key

# %%
# Set API key if needed (optional; the gateway works without auth on LHIND network)
lrn_llm.API_KEY = ""
print(f"Gateway endpoint: {lrn_llm.API_BASE}")
print(f"Default model: {lrn_llm.DEFAULT_MODEL}")
print(f"API key configured: {bool(lrn_llm.API_KEY)}")

# %% [markdown]
# ## Step 1 — Reachability

# %%
r = await lrn_llm.ping()
print(f"✅ LLM erreichbar: {r['ok']}")
print(f"Model: {r['model']}")

# %% [markdown]
# ## Step 2 — Define Tool Registry & Implementations
#
# We'll build the same multi-tool agent from the lesson: weather lookup, calculator, web search, file reading, and code execution. Each tool has a JSON Schema definition (what the model sees) and a Python function (what your code executes).

# %%
import math, time

# In-memory tool definitions and implementations
TOOL_REGISTRY = {}

def register_tool(name, description, parameters, function):
    TOOL_REGISTRY[name] = {
        "definition": {
            "type": "function",
            "function": {"name": name, "description": description, "parameters": parameters},
        },
        "function": function,
    }

# Weather database
WEATHER_DB = {
    "tokyo": {"temp_c": 18, "condition": "cloudy", "humidity": 72, "wind_kph": 14},
    "new york": {"temp_c": 22, "condition": "sunny", "humidity": 45, "wind_kph": 8},
    "london": {"temp_c": 12, "condition": "rainy", "humidity": 88, "wind_kph": 22},
}

def get_weather(city, units="celsius"):
    key = city.lower().strip()
    if key not in WEATHER_DB:
        return {"error": True, "message": f"City '{city}' not found.", "code": "CITY_NOT_FOUND"}
    data = WEATHER_DB[key].copy()
    if units == "fahrenheit":
        data["temp_f"] = round(data["temp_c"] * 9 / 5 + 32, 1)
        del data["temp_c"]
    data["city"] = city
    return data

def calculator(expression, precision=2):
    allowed = set("0123456789+-*/.() ")
    if not all(c in allowed for c in expression):
        return {"error": True, "message": f"Invalid characters in expression"}
    try:
        result = eval(expression, {"__builtins__": {}}, {"math": math})
        return {"result": round(float(result), precision), "expression": expression}
    except Exception as e:
        return {"error": True, "message": str(e)}

# Register the tools
register_tool(
    "get_weather",
    "Get current weather for a city. Returns temperature, condition, humidity, and wind speed.",
    {"type": "object", "properties": {"city": {"type": "string", "description": "City name, e.g. 'Tokyo' or 'London'"}, "units": {"type": "string", "enum": ["celsius", "fahrenheit"], "description": "Temperature units"}}, "required": ["city"]},
    get_weather,
)
register_tool(
    "calculator",
    "Evaluate a mathematical expression. Supports +, -, *, /, parentheses, and decimals. Returns the numeric result.",
    {"type": "object", "properties": {"expression": {"type": "string", "description": "Math expression, e.g. '(10 + 5) * 3'"}, "precision": {"type": "integer", "description": "Decimal places in result"}}, "required": ["expression"]},
    calculator,
)

print(f"✅ Registered {len(TOOL_REGISTRY)} tools")
for name in TOOL_REGISTRY:
    print(f"  - {name}")

# %% [markdown]
# ## Step 3 — Execute Tool Calls
#
# When the model decides which tool to call, we execute the actual function and return the result.

# %%
def execute_tool_call(tool_call):
    """Execute a tool call and return the result with timing."""
    name = tool_call["name"]
    args = tool_call.get("arguments", {})
    
    if name not in TOOL_REGISTRY:
        return {"error": True, "message": f"Unknown tool: {name}", "code": "UNKNOWN_TOOL"}
    
    func = TOOL_REGISTRY[name]["function"]
    start = time.time()
    
    try:
        result = func(**args)
    except TypeError as e:
        result = {"error": True, "message": f"Invalid arguments: {e}"}
    
    elapsed_ms = round((time.time() - start) * 1000, 2)
    return {"tool": name, "result": result, "execution_time_ms": elapsed_ms}

# Test direct execution
print("Direct tool execution test:")
test_call = {"name": "calculator", "arguments": {"expression": "(10 + 5) * 3 / 2"}}
exec_result = execute_tool_call(test_call)
print(f"Tool: {exec_result['tool']}")
print(f"Result: {exec_result['result']}")
print(f"Time: {exec_result['execution_time_ms']}ms")

# %% [markdown]
# ## Step 4 — The Function Calling Loop: Use Real LLM Calls
#
# This is the core agent loop. We send the user's message and tool definitions to the
# LLM. The model decides which tool to call. We execute it. **Step 5 of the diagram
# above**: the result goes back to the model, which uses it to produce a final
# synthesized answer — it may also decide it needs another tool call first, so this
# repeats until the model gives a direct answer or a `max_iterations` guard trips
# (without it, a model that keeps requesting tools, or keeps failing the same call,
# would loop forever).

# %%
async def run_function_calling_loop(user_message, max_iterations=5):
    """
    Run the function calling loop to completion:
    1. Send user message + tool definitions to LLM
    2. LLM decides: call a tool, or answer directly
    3. If a tool call: execute it, feed the result back to the LLM (Step 5), go to 2
    4. If a direct/final response: return it
    Bounded by max_iterations so a model that keeps requesting tools can't loop forever.
    """
    system_prompt = """You are a helpful assistant with access to tools.
When the user asks a question:
1. Decide which tool(s) would help answer it
2. Call the appropriate tool with the correct arguments
3. DO NOT call tools for general knowledge questions
4. Once a tool result has been given to you, use it to produce a final natural-language answer

You MUST respond with a JSON object in this exact format:
{"tool_name": "<name>", "arguments": {<args>}}

Or, once you have enough information to answer (including right after a tool result
was given to you):
{"response": "Your final answer here"}"""

    transcript = [f"User: {user_message}"]
    tool_calls_made = []

    for iteration in range(1, max_iterations + 1):
        response = await lrn_llm.call(
            [{"role": "user", "content": "\n".join(transcript)}],
            system=system_prompt, max_tokens=300
        )
        model_output = lrn_llm.text(response)
        print(f"[Iteration {iteration}] LLM: " +
              (f"{model_output[:150]}..." if len(model_output) > 150 else model_output))

        try:
            decision = json.loads(model_output)
        except json.JSONDecodeError:
            return {"type": "error", "message": "LLM returned invalid JSON", "raw": model_output,
                    "iterations": iteration, "tool_calls": tool_calls_made}

        if "response" in decision:
            return {"type": "final" if tool_calls_made else "direct",
                    "response": decision["response"], "iterations": iteration,
                    "tool_calls": tool_calls_made}

        if "tool_name" in decision:
            tool_call = {"name": decision["tool_name"], "arguments": decision.get("arguments", {})}
            exec_result = execute_tool_call(tool_call)
            tool_calls_made.append(exec_result["tool"])

            if exec_result["result"].get("error"):
                return {"type": "error", "tool": exec_result["tool"],
                        "error": exec_result["result"]["message"], "iterations": iteration,
                        "tool_calls": tool_calls_made}

            # Step 5: feed the tool result back to the model instead of returning it to
            # the caller — this is the step that was previously skipped.
            transcript.append(f"Assistant: called {exec_result['tool']}({tool_call['arguments']})")
            transcript.append(f"Tool result: {json.dumps(exec_result['result'])}")
            continue

        return {"type": "error", "message": "LLM response did not contain tool_name or response field",
                "iterations": iteration, "tool_calls": tool_calls_made}

    return {"type": "error", "message": f"Exceeded max_iterations ({max_iterations}) without a final response",
            "iterations": max_iterations, "tool_calls": tool_calls_made}

print("✅ Function calling loop ready (feeds tool results back, guarded by max_iterations)")

# %% [markdown]
# ## Step 5 — Try It: Weather Query
#
# Let's ask the agent about the weather. The LLM will decide to call the `get_weather` tool.

# %%
def print_loop_result(result):
    """Result is always the model's own final answer now — 'final' means it came
    after one or more tool calls whose results were fed back; 'direct' means no tool
    was needed at all."""
    print(f"\nResult type: {result.get('type')} (iterations: {result.get('iterations')}, "
          f"tools called: {result.get('tool_calls') or 'none'})")
    if result.get('type') in ('final', 'direct'):
        print(f"Response: {result.get('response')}")
    elif result.get('type') == 'error':
        print(f"Error: {result.get('error') or result.get('message')}")

result = await run_function_calling_loop("What's the weather in Tokyo?")
print_loop_result(result)

# %% [markdown]
# ## Step 6 — Try It: Calculator Query
#
# Now let's ask a math question. The LLM should call the calculator tool.

# %%
result = await run_function_calling_loop("Calculate (100 + 250) * 0.15")
print_loop_result(result)

# %% [markdown]
# ## Step 7 — Try It: General Knowledge Query
#
# For this query, the LLM should recognize it doesn't need a tool and respond directly.

# %%
result = await run_function_calling_loop("What is the capital of France?")
print_loop_result(result)

# %% [markdown]
# ## Try It Yourself
#
# Edit the query below and run it. The LLM will decide which tool to call (or respond directly if no tool is needed). Try:
# - Weather queries: "What's the weather in London?"
# - Math: "What is 15% of 500?"
# - General knowledge: "Tell me about function calling in AI"

# %%
# TODO: Edit this query and run it
query = "What's the weather in New York?"
print(f"User query: {query}\n")

result = await run_function_calling_loop(query)
print_loop_result(result)
