# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/11-llm-engineering/09-function-calling
# Used in courses: AI-06
# Framework: vanilla-openai
# Requires API key: False

"""tool_calling"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "https://gateway.lhind.ai/v1"
lrn_llm.DEFAULT_MODEL = "azure/gpt-4o"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    if lrn_llm.API_KEY:
        headers["Authorization"] = "Bearer " + lrn_llm.API_KEY
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key

# %%
# Set API key if needed (optional; the gateway works without auth on LHIND network)
lrn_llm.API_KEY = ""
print(f"Gateway endpoint: {lrn_llm.API_BASE}")
print(f"Default model: {lrn_llm.DEFAULT_MODEL}")
print(f"API key configured: {bool(lrn_llm.API_KEY)}")

# %% [markdown]
# ## Step 1 — Reachability

# %%
r = await lrn_llm.ping()
print(f"✅ LLM erreichbar: {r['ok']}")
print(f"Model: {r['model']}")

# %% [markdown]
# ## Step 2 — Define Tool Registry & Implementations
#
# We'll build the same multi-tool agent from the lesson: weather lookup, calculator, web search, file reading, and code execution. Each tool has a JSON Schema definition (what the model sees) and a Python function (what your code executes).

# %%
import math, time

# In-memory tool definitions and implementations
TOOL_REGISTRY = {}

def register_tool(name, description, parameters, function):
    TOOL_REGISTRY[name] = {
        "definition": {
            "type": "function",
            "function": {"name": name, "description": description, "parameters": parameters},
        },
        "function": function,
    }

# Weather database
WEATHER_DB = {
    "tokyo": {"temp_c": 18, "condition": "cloudy", "humidity": 72, "wind_kph": 14},
    "new york": {"temp_c": 22, "condition": "sunny", "humidity": 45, "wind_kph": 8},
    "london": {"temp_c": 12, "condition": "rainy", "humidity": 88, "wind_kph": 22},
}

def get_weather(city, units="celsius"):
    key = city.lower().strip()
    if key not in WEATHER_DB:
        return {"error": True, "message": f"City '{city}' not found.", "code": "CITY_NOT_FOUND"}
    data = WEATHER_DB[key].copy()
    if units == "fahrenheit":
        data["temp_f"] = round(data["temp_c"] * 9 / 5 + 32, 1)
        del data["temp_c"]
    data["city"] = city
    return data

def calculator(expression, precision=2):
    allowed = set("0123456789+-*/.() ")
    if not all(c in allowed for c in expression):
        return {"error": True, "message": f"Invalid characters in expression"}
    try:
        result = eval(expression, {"__builtins__": {}}, {"math": math})
        return {"result": round(float(result), precision), "expression": expression}
    except Exception as e:
        return {"error": True, "message": str(e)}

# Register the tools
register_tool(
    "get_weather",
    "Get current weather for a city. Returns temperature, condition, humidity, and wind speed.",
    {"type": "object", "properties": {"city": {"type": "string", "description": "City name, e.g. 'Tokyo' or 'London'"}, "units": {"type": "string", "enum": ["celsius", "fahrenheit"], "description": "Temperature units"}}, "required": ["city"]},
    get_weather,
)
register_tool(
    "calculator",
    "Evaluate a mathematical expression. Supports +, -, *, /, parentheses, and decimals. Returns the numeric result.",
    {"type": "object", "properties": {"expression": {"type": "string", "description": "Math expression, e.g. '(10 + 5) * 3'"}, "precision": {"type": "integer", "description": "Decimal places in result"}}, "required": ["expression"]},
    calculator,
)

print(f"✅ Registered {len(TOOL_REGISTRY)} tools")
for name in TOOL_REGISTRY:
    print(f"  - {name}")

# %% [markdown]
# ## Step 3 — Execute Tool Calls
#
# When the model decides which tool to call, we execute the actual function and return the result.

# %%
def execute_tool_call(tool_call):
    """Execute a tool call and return the result with timing."""
    name = tool_call["name"]
    args = tool_call.get("arguments", {})
    
    if name not in TOOL_REGISTRY:
        return {"error": True, "message": f"Unknown tool: {name}", "code": "UNKNOWN_TOOL"}
    
    func = TOOL_REGISTRY[name]["function"]
    start = time.time()
    
    try:
        result = func(**args)
    except TypeError as e:
        result = {"error": True, "message": f"Invalid arguments: {e}"}
    
    elapsed_ms = round((time.time() - start) * 1000, 2)
    return {"tool": name, "result": result, "execution_time_ms": elapsed_ms}

# Test direct execution
print("Direct tool execution test:")
test_call = {"name": "calculator", "arguments": {"expression": "(10 + 5) * 3 / 2"}}
exec_result = execute_tool_call(test_call)
print(f"Tool: {exec_result['tool']}")
print(f"Result: {exec_result['result']}")
print(f"Time: {exec_result['execution_time_ms']}ms")

# %% [markdown]
# ## Step 4 — The Function Calling Loop: Use Real LLM Calls
#
# This is the core agent loop. We send the user's message and tool definitions to the LLM. The model decides which tool to call. We execute it. The result goes back to the model for synthesis.

# %%
async def run_function_calling_loop(user_message):
    """
    Run a single turn of the function calling loop:
    1. Send user message + tool definitions to LLM
    2. LLM decides which tool to call
    3. Execute the tool
    4. Return result to user
    """
    # Prepare tool definitions for the LLM
    tool_definitions = [t["definition"] for t in TOOL_REGISTRY.values()]
    
    # Step 1: Call LLM to decide which tool(s) to invoke
    system_prompt = """You are a helpful assistant with access to tools.
When the user asks a question:
1. Decide which tool(s) would help answer it
2. Call the appropriate tool with the correct arguments
3. DO NOT call tools for general knowledge questions

You MUST respond with a JSON object in this exact format:
{"tool_name": "<name>", "arguments": {<args>}}

Or if no tool is needed:
{"response": "Your direct answer here"}"""
    
    messages = [{"role": "user", "content": user_message}]
    
    response = await lrn_llm.call(messages, system=system_prompt, max_tokens=300)
    model_output = lrn_llm.text(response)
    
    print(f"LLM decision: {model_output[:150]}..." if len(model_output) > 150 else f"LLM decision: {model_output}")
    
    # Step 2: Parse the LLM's decision
    try:
        decision = json.loads(model_output)
    except json.JSONDecodeError:
        return {"error": True, "message": "LLM returned invalid JSON", "raw": model_output}
    
    # Step 3: If no tool needed, return direct response
    if "response" in decision:
        return {"type": "direct", "response": decision["response"]}
    
    # Step 4: Execute the tool call
    if "tool_name" in decision:
        tool_call = {"name": decision["tool_name"], "arguments": decision.get("arguments", {})}
        exec_result = execute_tool_call(tool_call)
        
        if exec_result["result"].get("error"):
            return {"type": "error", "tool": exec_result["tool"], "error": exec_result["result"]["message"]}
        
        return {"type": "tool_call", "tool": exec_result["tool"], "result": exec_result["result"], "time_ms": exec_result["execution_time_ms"]}
    
    return {"error": True, "message": "LLM response did not contain tool_name or response field"}

print("✅ Function calling loop ready")

# %% [markdown]
# ## Step 5 — Try It: Weather Query
#
# Let's ask the agent about the weather. The LLM will decide to call the `get_weather` tool.

# %%
result = await run_function_calling_loop("What's the weather in Tokyo?")
print(f"\nResult type: {result.get('type')}")
if result.get('type') == 'tool_call':
    print(f"Tool called: {result['tool']}")
    print(f"Result: {json.dumps(result['result'], indent=2)}")
    print(f"Execution time: {result['time_ms']}ms")
elif result.get('type') == 'error':
    print(f"Tool error: {result['error']}")
else:
    print(f"Response: {result.get('response')}")

# %% [markdown]
# ## Step 6 — Try It: Calculator Query
#
# Now let's ask a math question. The LLM should call the calculator tool.

# %%
result = await run_function_calling_loop("Calculate (100 + 250) * 0.15")
print(f"\nResult type: {result.get('type')}")
if result.get('type') == 'tool_call':
    print(f"Tool called: {result['tool']}")
    print(f"Result: {json.dumps(result['result'], indent=2)}")
    print(f"Execution time: {result['time_ms']}ms")
elif result.get('type') == 'error':
    print(f"Tool error: {result['error']}")
else:
    print(f"Response: {result.get('response')}")

# %% [markdown]
# ## Step 7 — Try It: General Knowledge Query
#
# For this query, the LLM should recognize it doesn't need a tool and respond directly.

# %%
result = await run_function_calling_loop("What is the capital of France?")
print(f"\nResult type: {result.get('type')}")
if result.get('type') == 'tool_call':
    print(f"Tool called: {result['tool']}")
    print(f"Result: {json.dumps(result['result'], indent=2)}")
elif result.get('type') == 'error':
    print(f"Tool error: {result['error']}")
else:
    print(f"Direct response: {result.get('response')}")

# %% [markdown]
# ## Try It Yourself
#
# Edit the query below and run it. The LLM will decide which tool to call (or respond directly if no tool is needed). Try:
# - Weather queries: "What's the weather in London?"
# - Math: "What is 15% of 500?"
# - General knowledge: "Tell me about function calling in AI"

# %%
# TODO: Edit this query and run it
query = "What's the weather in New York?"
print(f"User query: {query}\n")

result = await run_function_calling_loop(query)
print(f"\nResult type: {result.get('type')}")
if result.get('type') == 'tool_call':
    print(f"Tool called: {result['tool']}")
    print(f"Result:")
    print(json.dumps(result['result'], indent=2))
    print(f"Execution time: {result['time_ms']}ms")
elif result.get('type') == 'error':
    print(f"Tool error: {result['error']}")
else:
    print(f"Direct response: {result.get('response')}")
