# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/13-tools-and-protocols/06-mcp-fundamentals
# Used in courses: AI-03
# Framework: stdlib
# Requires API key: False

"""lrn_llm"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "/api/llm"  # same-origin proxy; server injects the gateway key
lrn_llm.DEFAULT_MODEL = "azure/gpt-5.4-mini"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    _key = lrn_llm.API_KEY
    if _key:
        headers["Authorization"] = "Bearer " + _key
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key
#
# Set your API key (optional on the LHIND network) and verify the endpoint.

# %%
lrn_llm.API_KEY = ""
print(f"Endpoint: {lrn_llm.API_BASE}")
print(f"Model: {lrn_llm.DEFAULT_MODEL}")
print(f"API Key set: {'yes' if lrn_llm.API_KEY else 'no (optional on LHIND)'}")

# %% [markdown]
# ## Step 1 — Reachability
#
# Verify the LLM is reachable.

# %%
r = await lrn_llm.ping()
print(f"✅ LLM erreichbar: {r}")

# %% [markdown]
# ## Step 2 — The JSON-RPC 2.0 Envelope
#
# MCP sits on top of JSON-RPC 2.0, a lightweight request/response/notification protocol. Every message is a JSON object with a specific shape. Let's ask the LLM to explain what each envelope type means.

# %%
system_prompt = """You are an MCP (Model Context Protocol) expert. Explain JSON-RPC 2.0 message shapes clearly and concisely."""

message = "What is the difference between a JSON-RPC request, response, and notification? Give one sentence each, then a JSON example for each."

r = await lrn_llm.call([{"role": "user", "content": message}], system=system_prompt, max_tokens=300)
print(lrn_llm.text(r))

# %% [markdown]
# ## Step 3 — Building a JSON-RPC Request: initialize
#
# The MCP lifecycle starts with an `initialize` request. The client sends its capabilities and client info; the server responds with its own capabilities, server info, and protocol version. Let's construct this message and ask the LLM to validate it.

# %%
# Build the initialize request as per the lesson domain (notes-server)
initialize_request = {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "initialize",
    "params": {
        "protocolVersion": "2025-11-25",
        "clientInfo": {"name": "learner-client", "version": "1.0.0"},
        "capabilities": {
            "roots": {"listChanged": True},
            "sampling": {},
            "elicitation": {},
        }
    }
}

print("Client initialize request:")
print(json.dumps(initialize_request, indent=2))

# Ask the LLM to validate it
validation_msg = f"Is this a valid MCP initialize request? {json.dumps(initialize_request)}"
r = await lrn_llm.call([{"role": "user", "content": validation_msg}], system=system_prompt, max_tokens=150)
print("\nValidation from LLM:")
print(lrn_llm.text(r))

# %% [markdown]
# ## Step 4 — Parsing the Server Response
#
# The server responds with its own capabilities and info. Let's parse it and have the LLM explain what capabilities are negotiated.

# %%
# Server's initialize response
server_response = {
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "protocolVersion": "2025-11-25",
        "serverInfo": {"name": "notes-server", "version": "1.0.0"},
        "capabilities": {
            "tools": {"listChanged": True},
            "resources": {"subscribe": True, "listChanged": True},
            "prompts": {"listChanged": True},
        }
    }
}

print("Server initialize response:")
print(json.dumps(server_response, indent=2))

# Ask the LLM to explain what's negotiated
caps_msg = f"""Given this server response, what capabilities are now mutually supported?
{json.dumps(server_response, indent=2)}

List the operations the client can now safely invoke."""

r = await lrn_llm.call([{"role": "user", "content": caps_msg}], system=system_prompt, max_tokens=200)
print("\nCapability negotiation analysis:")
print(lrn_llm.text(r))

# %% [markdown]
# ## Step 5 — Tool Discovery: tools/list
#
# After initialization, the client can discover tools. Let's construct a `tools/list` request and the server's response with a notes_search tool.

# %%
# Client requests the tool list
tools_list_request = {
    "jsonrpc": "2.0",
    "id": 2,
    "method": "tools/list"
}

print("Client tools/list request:")
print(json.dumps(tools_list_request, indent=2))

# Server's response with the notes_search tool
tools_list_response = {
    "jsonrpc": "2.0",
    "id": 2,
    "result": {
        "tools": [
            {
                "name": "notes_search",
                "description": "Search for notes by keywords. Returns matching notes with their content.",
                "inputSchema": {
                    "type": "object",
                    "properties": {
                        "query": {"type": "string"},
                        "limit": {"type": "integer", "minimum": 1, "maximum": 50}
                    },
                    "required": ["query"]
                }
            }
        ]
    }
}

print("\nServer tools/list response:")
print(json.dumps(tools_list_response, indent=2))

# %% [markdown]
# ## Step 6 — Tool Invocation: tools/call
#
# Now we invoke the `notes_search` tool. Let's construct the request and have the LLM generate a realistic response based on what the tool would return.

# %%
# Client calls the notes_search tool
tools_call_request = {
    "jsonrpc": "2.0",
    "id": 3,
    "method": "tools/call",
    "params": {
        "name": "notes_search",
        "arguments": {"query": "JSON-RPC", "limit": 5}
    }
}

print("Client tools/call request:")
print(json.dumps(tools_call_request, indent=2))

# Ask the LLM to generate a realistic tool response
response_msg = f"""You are a notes server responding to this MCP tools/call request:
{json.dumps(tools_call_request, indent=2)}

Generate a realistic server response that includes:
- A content array with text blocks
- isError set to false
- Don't include explanation; just the JSON response object (with result field for the id)."""

r = await lrn_llm.call([{"role": "user", "content": response_msg}], system="You are a JSON expert.", max_tokens=200)
response_text = lrn_llm.text(r)
print("\nServer tools/call response (LLM-generated):")
print(response_text)

# %% [markdown]
# ## Step 7 — Notifications: tools/list_changed
#
# While operation is in progress, either side can send notifications. Let's construct a `notifications/tools/list_changed` to show what happens when the server's tool list mutates.

# %%
# Server sends a notification (no id, no response expected)
tools_changed_notification = {
    "jsonrpc": "2.0",
    "method": "notifications/tools/list_changed"
}

print("Server sends notification (no response expected):")
print(json.dumps(tools_changed_notification, indent=2))

# Ask the LLM what this means
notif_msg = """In MCP, what does notifications/tools/list_changed mean? 
Why does it have no 'id' field?
What should the client do when it receives this?"""

r = await lrn_llm.call([{"role": "user", "content": notif_msg}], system=system_prompt, max_tokens=200)
print("\nLLM explanation:")
print(lrn_llm.text(r))

# %% [markdown]
# ## Step 8 — Error Handling
#
# If the client requests a tool that doesn't exist or there's an error, the server responds with a JSON-RPC error. Let's construct an error response.

# %%
# Client tries to call a non-existent tool
error_request = {
    "jsonrpc": "2.0",
    "id": 4,
    "method": "tools/call",
    "params": {
        "name": "notes_delete",
        "arguments": {"id": "unknown"}
    }
}

print("Client request for non-existent tool:")
print(json.dumps(error_request, indent=2))

# Server's error response
error_response = {
    "jsonrpc": "2.0",
    "id": 4,
    "error": {
        "code": -32601,
        "message": "Method not found",
        "data": {"tool": "notes_delete"}
    }
}

print("\nServer error response:")
print(json.dumps(error_response, indent=2))

# Explain the error code
error_msg = "What does JSON-RPC error code -32601 mean? Why is it used for missing tools in MCP?"
r = await lrn_llm.call([{"role": "user", "content": error_msg}], system=system_prompt, max_tokens=150)
print("\nError code explanation:")
print(lrn_llm.text(r))

# %% [markdown]
# ## Step 9 — Lifecycle Summary
#
# Let's recap the three phases of the MCP lifecycle and have the LLM validate our understanding.

# %%
lifecycle = {
    "Phase 1: initialize": "Client and server exchange capabilities; no operations until both have acknowledged",
    "Phase 2: operation": "Bidirectional requests, responses, and notifications. Client discovers and invokes tools; server may send sampling or mutation notifications",
    "Phase 3: shutdown": "Transport closes (no JSON-RPC shutdown method). Either side can initiate."
}

for phase, desc in lifecycle.items():
    print(f"{phase}")
    print(f"  {desc}")
    print()

# Ask the LLM why this three-phase structure matters
why_msg = """Why does MCP require explicit initialize/initialized handshake before any tool calls?
What breaks if the client skips capability negotiation?"""

r = await lrn_llm.call([{"role": "user", "content": why_msg}], system=system_prompt, max_tokens=200)
print("\nWhy the three-phase structure matters:")
print(lrn_llm.text(r))

# %% [markdown]
# ## Try It Yourself
#
# Now it's your turn! Below is a sandbox cell where you can:
# 1. Build your own JSON-RPC envelope (request, response, or notification)
# 2. Ask the LLM to validate it
# 3. Parse another's request and explain what it does
#
# Some ideas:
# - Build a `prompts/list` request (MCP has three server primitives: tools, resources, prompts)
# - Construct a `resources/read` request for a file URI
# - Modify the `notes_search` tool's inputSchema and ask the LLM if it's valid
# - Build your own tool definition and have the LLM review it

# %%
# TODO: Try building your own MCP message!
# Uncomment and modify one of the examples below:

# Example 1: Build a prompts/list request
# your_request = {
#     "jsonrpc": "2.0",
#     "id": 5,
#     "method": "prompts/list"
# }

# Example 2: Build a resources/read request
# your_request = {
#     "jsonrpc": "2.0",
#     "id": 6,
#     "method": "resources/read",
#     "params": {
#         "uri": "file:///notes/personal.txt"
#     }
# }

# Example 3: Create your own tool definition
# your_tool = {
#     "name": "notes_create",
#     "description": "Create a new note with a title and content.",
#     "inputSchema": {
#         "type": "object",
#         "properties": {
#             "title": {"type": "string"},
#             "content": {"type": "string"}
#         },
#         "required": ["title", "content"]
#     }
# }
# your_request = your_tool

print("Modify this cell to build and validate your own MCP message!")
print()
print("Once you've built 'your_request', uncomment and run this:")
print()
print("""# print(json.dumps(your_request, indent=2))
# validation = f"Validate this MCP message or tool: {json.dumps(your_request)}"
# r = await lrn_llm.call([{"role": "user", "content": validation}], system=system_prompt, max_tokens=200)
# print(lrn_llm.text(r))
""")
