# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/16-multi-agent-and-swarms/08-role-specialization
# Used in courses: AI-20
# Framework: agent-loop
# Requires API key: False

"""lesson"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "https://gateway.lhind.ai/v1"
lrn_llm.DEFAULT_MODEL = "azure/gpt-4o"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    if lrn_llm.API_KEY:
        headers["Authorization"] = "Bearer " + lrn_llm.API_KEY
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key
#
# Set your optional API key below. The gateway works without a key on the LHIND network.

# %%
lrn_llm.API_KEY = ""  # Leave empty for gateway-only access
print(f"API endpoint: {lrn_llm.API_BASE}")
print(f"Default model: {lrn_llm.DEFAULT_MODEL}")
print(f"Key set: {bool(lrn_llm.API_KEY)}")

# %% [markdown]
# ## Step 1 — Reachability
#
# Ping the LLM to verify the connection is working.

# %%
r = await lrn_llm.ping()
print(f"✅ LLM erreichbar: {r}")

# %% [markdown]
# ## Step 2 — The Role Specialization Pattern
#
# In this lesson, we build a **4-role pipeline** to generate Python code:
#
# 1. **Planner** — reads a user wish and produces a structured spec (function signature, test cases)
# 2. **Executor** — reads the spec and generates Python code
# 3. **Critic** — reviews the code for style and obvious issues (LLM-based, subjective)
# 4. **Verifier** — runs the generated code against test cases (deterministic, objective)
#
# The key insight: the **critic can be fooled** by plausible-looking code that is semantically wrong. Only the **verifier catches bugs that show up at runtime**.
#
# Let's start by defining the spec structure that flows from planner to executor to critic to verifier.

# %%
from dataclasses import dataclass, field
import json

@dataclass
class Spec:
    task_name: str
    signature: str
    description: str
    tests: list

@dataclass
class CriticReport:
    approved: bool
    notes: list = field(default_factory=list)

@dataclass
class VerifierReport:
    passed: bool
    failures: list = field(default_factory=list)

print("✅ Role data structures defined")

# %% [markdown]
# ## Step 3 — The Planner Role (LLM-based)
#
# The planner reads a user's wish and produces a structured spec: function name, signature, description, and test cases. This role uses an LLM to interpret the user intent and generate well-formed test cases.

# %%
async def planner_llm(user_wish: str) -> Spec:
    """Planner uses LLM to produce a structured spec from a user wish."""
    prompt = f"""You are a code specification writer. Given a user wish, produce a JSON spec with:
- task_name: a Python-friendly function name
- signature: Python function signature (with type hints)
- description: one-sentence summary
- tests: array of [inputs_array, expected_output] pairs (2-3 test cases)

User wish: {user_wish}

Reply with only valid JSON, no markdown, no explanation."""
    
    r = await lrn_llm.call([{"role": "user", "content": prompt}], max_tokens=200)
    text = lrn_llm.text(r)
    spec_dict = json.loads(text)
    return Spec(
        task_name=spec_dict["task_name"],
        signature=spec_dict["signature"],
        description=spec_dict["description"],
        tests=spec_dict["tests"]
    )

# Demo: planner interprets "add two numbers"
spec = await planner_llm("Write a function that returns the sum of two integers.")
print(f"Spec produced:")
print(f"  task_name: {spec.task_name}")
print(f"  signature: {spec.signature}")
print(f"  description: {spec.description}")
print(f"  tests: {spec.tests}")

# %% [markdown]
# ## Step 4 — The Executor Role (LLM-based)
#
# The executor reads the spec and generates Python code that matches the signature and passes the tests. We'll show both a correct and buggy executor to demo the point.

# %%
async def executor_llm(spec: Spec) -> str:
    """Executor uses LLM to generate Python code matching the spec."""
    prompt = f"""You are a Python code generator. Write ONLY the function body, matching this spec:

Function signature: {spec.signature}
Description: {spec.description}
Test cases (inputs → expected): {spec.tests}

Reply with ONLY the code (no markdown, no explanation, no def line), just the function body.
Example output:
    return a + b

Now generate code for this spec:"""
    
    r = await lrn_llm.call([{"role": "user", "content": prompt}], max_tokens=150)
    code_body = lrn_llm.text(r).strip()
    # Wrap in function definition
    code = f"def {spec.task_name}{spec.signature.split(spec.task_name)[1].split('->')[0]}:\n    {code_body.replace(chr(10), chr(10)+'    ')}"
    return code

# Demo: executor generates code for our spec
code = await executor_llm(spec)
print("Generated code:")
print(code)

# %% [markdown]
# ## Step 5 — The Critic Role (LLM-based, Subjective)
#
# The critic reviews the code for style and obvious structural issues. It's fast and opinionated but can be fooled by plausible-looking code that is semantically wrong.

# %%
async def critic_llm(spec: Spec, code: str) -> CriticReport:
    """Critic uses LLM to review code for style and obvious issues."""
    prompt = f"""You are a code reviewer. Review this code against the spec:

Spec: {spec.signature}
Description: {spec.description}

Code:
{code}

List any issues (e.g., style, missing edge cases, syntax, clarity). Be brief. Reply JSON:
{{
  "approved": true/false,
  "notes": ["issue1", "issue2", ...]
}}

Reply with ONLY JSON, no explanation."""
    
    r = await lrn_llm.call([{"role": "user", "content": prompt}], max_tokens=100)
    text = lrn_llm.text(r)
    review = json.loads(text)
    return CriticReport(approved=review["approved"], notes=review.get("notes", []))

# Demo: critic reviews the generated code
critic_report = await critic_llm(spec, code)
print(f"Critic report:")
print(f"  approved: {critic_report.approved}")
print(f"  notes: {critic_report.notes}")

# %% [markdown]
# ## Step 6 — The Verifier Role (Deterministic, Objective)
#
# The verifier runs the code in a sandbox against the test cases. It's slow but cannot be fooled — if the code fails a test, it fails objectively.

# %%
def verifier_deterministic(spec: Spec, code: str) -> VerifierReport:
    """Verifier runs the code in a sandbox and executes the tests."""
    ns = {}
    try:
        exec(code, ns, ns)
    except Exception as e:
        return VerifierReport(passed=False, failures=[f"exec error: {e}"])
    
    fn = ns.get(spec.task_name)
    if not callable(fn):
        return VerifierReport(passed=False, failures=[f"no callable '{spec.task_name}' produced"])
    
    failures = []
    for test_case in spec.tests:
        # Test cases may arrive as [inputs, expected] pairs (the spec format)
        # or as {"inputs": ..., "expected": ...} dicts, depending on the LLM.
        # Normalize both so indexing never raises KeyError.
        if isinstance(test_case, dict):
            args = test_case.get("inputs", test_case.get("input", test_case.get("args")))
            expected = test_case.get("expected", test_case.get("output", test_case.get("expected_output")))
        else:
            args, expected = test_case[0], test_case[1]
        try:
            got = fn(*args) if isinstance(args, list) else fn(args)
        except Exception as e:
            failures.append(f"call {args} raised {type(e).__name__}: {e}")
            continue
        if got != expected:
            failures.append(f"call {args}: expected {expected}, got {got}")
    
    return VerifierReport(passed=not failures, failures=failures)

# Demo: verifier tests the generated code
verifier_report = verifier_deterministic(spec, code)
print(f"Verifier report:")
print(f"  passed: {verifier_report.passed}")
print(f"  failures: {verifier_report.failures}")

# %% [markdown]
# ## Step 7 — The Full Pipeline
#
# Now let's run the complete 4-role pipeline end-to-end. We'll also show what happens when we inject a buggy manual code (critic passes, verifier fails — the key lesson).

# %%
async def run_pipeline(user_wish: str, label: str):
    """Run the full planner → executor → critic → verifier pipeline."""
    print(f"\n=== {label} ===")
    
    # Planner
    spec = await planner_llm(user_wish)
    print(f"[planner] spec: {spec.signature}")
    print(f"           tests: {spec.tests}")
    
    # Executor
    code = await executor_llm(spec)
    print(f"[executor] code:")
    for line in code.split('\n'):
        print(f"           {line}")
    
    # Critic
    critic_report = await critic_llm(spec, code)
    print(f"[critic] approved={critic_report.approved}, notes={critic_report.notes}")
    
    # Verifier
    verifier_report = verifier_deterministic(spec, code)
    print(f"[verifier] passed={verifier_report.passed}, failures={verifier_report.failures}")
    
    # Decision
    if critic_report.approved and verifier_report.passed:
        result = "✅ SHIP IT."
    elif not verifier_report.passed:
        result = "❌ VERIFIER BLOCKED (deterministic test failure)."
    else:
        result = "⚠️  CRITIC BLOCKED (style/structure issue)."
    print(f"[result] {result}")
    return spec, code, critic_report, verifier_report

# Run pipeline on the user wish
spec, code, cr, vr = await run_pipeline(
    "Write a function that returns the sum of two integers.",
    "Correct Executor Output"
)

# %% [markdown]
# ## Step 8 — The Key Lesson: Critic vs. Verifier
#
# Now let's inject a **buggy code manually** to show the classic MAST failure: the critic thinks it looks fine, but the verifier catches the bug because the test fails at runtime.
#
# **Buggy code:** multiplication instead of addition. The critic can be fooled because the code is syntactically correct and has a return statement. The verifier catches it immediately.

# %%
# Manually inject buggy code (multiply instead of add)
buggy_code = f"def {spec.task_name}{spec.signature.split(spec.task_name)[1].split('->')[0]}:\n    return a * b"

print(f"Testing buggy code:")
print(buggy_code)
print()

# Critic reviews it
critic_report_buggy = await critic_llm(spec, buggy_code)
print(f"[critic] approved={critic_report_buggy.approved}, notes={critic_report_buggy.notes}")

# Verifier tests it
verifier_report_buggy = verifier_deterministic(spec, buggy_code)
print(f"[verifier] passed={verifier_report_buggy.passed}, failures={verifier_report_buggy.failures}")

if not verifier_report_buggy.passed and critic_report_buggy.approved:
    print("\n🎯 KEY INSIGHT: Critic passed, verifier failed. This is the MAST failure mode.")
    print("All-LLM pipelines (no verifier) would ship this bug.")

# %% [markdown]
# ## Try it yourself
#
# Edit the user wish below and run the full pipeline. Watch how the planner, executor, critic, and verifier each do their part. Can you craft a user wish that the critic misses but the verifier catches?

# %%
# TODO: Change this user wish to test the pipeline with different functions
user_wish = "Write a function that returns the maximum of two numbers."

# Run the full pipeline
print(f"Your user wish: {user_wish}")
print()

# Uncomment the line below to run the pipeline
# spec2, code2, cr2, vr2 = await run_pipeline(user_wish, "Custom Wish")
