# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/13-tools-and-protocols/04-structured-output
# Used in courses: PROMPT-01
# Framework: vanilla-openai
# Requires API key: False

"""from lrn_llm import call, text, ping, API_BASE, DEFAULT_MODEL"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "/api/llm"  # same-origin proxy; server injects the gateway key
lrn_llm.DEFAULT_MODEL = "azure/gpt-5.4-mini"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    _key = lrn_llm.API_KEY
    if _key:
        headers["Authorization"] = "Bearer " + _key
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key
#
# Set your API key if needed (the LHIND gateway works without a key on the internal network).

# %%
lrn_llm.API_KEY = ""  # Leave empty for LHIND network, or paste your key here
print(f"Endpoint: {lrn_llm.API_BASE}")
print(f"Model: {lrn_llm.DEFAULT_MODEL}")
print(f"API Key set: {bool(lrn_llm.API_KEY)}")

# %% [markdown]
# ## Step 1 — Reachability
#
# Test that the LLM is reachable.

# %%
r = await lrn_llm.ping()
print("✅ LLM erreichbar:", r)

# %% [markdown]
# ## Step 2 — Invoice Schema
#
# Define the JSON Schema that will constrain the model's output. This schema captures an invoice with customer name, line items (each with SKU, quantity, and unit price), total, and currency.
#
# Key constraints:
# - `customer`: string with 1–200 characters
# - `line_items`: array of objects with `sku` (alphanumeric pattern), `qty` (integer ≥1), `unit_usd` (number ≥0)
# - `total_usd`: non-negative number
# - `currency`: enum of {USD, EUR, INR}
# - `additionalProperties: false` forbids hallucinated fields

# %%
import re
from dataclasses import dataclass
from typing import Any

INVOICE_SCHEMA = {
    "type": "object",
    "properties": {
        "customer": {"type": "string", "minLength": 1, "maxLength": 200},
        "line_items": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "sku": {"type": "string", "pattern": "^[A-Z0-9-]+$"},
                    "qty": {"type": "integer", "minimum": 1},
                    "unit_usd": {"type": "number", "minimum": 0},
                },
                "required": ["sku", "qty", "unit_usd"],
                "additionalProperties": False,
            },
        },
        "total_usd": {"type": "number", "minimum": 0},
        "currency": {"type": "string", "enum": ["USD", "EUR", "INR"]},
    },
    "required": ["customer", "line_items", "total_usd", "currency"],
    "additionalProperties": False,
}

print("Invoice schema keys:", list(INVOICE_SCHEMA["properties"].keys()))
print("Required fields:", INVOICE_SCHEMA["required"])

# %% [markdown]
# ## Step 3 — Validator
#
# Build a minimal JSON Schema validator that checks type, required fields, enum values, min/max constraints, patterns, and array items. The validator returns typed errors with path and message.

# %%
@dataclass
class ValidationError:
    path: str
    message: str
    def __str__(self) -> str:
        return f"{self.path}: {self.message}"

def validate(schema: dict, value: Any, path: str = "$") -> list[ValidationError]:
    errors: list[ValidationError] = []
    t = schema.get("type")
    if t == "object":
        if not isinstance(value, dict):
            return [ValidationError(path, f"expected object, got {type(value).__name__}")]
        required = schema.get("required", [])
        props = schema.get("properties", {})
        for field in required:
            if field not in value:
                errors.append(ValidationError(f"{path}.{field}", "missing required field"))
        if schema.get("additionalProperties") is False:
            extras = set(value) - set(props)
            for extra in extras:
                errors.append(ValidationError(f"{path}.{extra}", "additional property not allowed"))
        for key, sub in props.items():
            if key in value:
                errors.extend(validate(sub, value[key], f"{path}.{key}"))
        return errors
    if t == "array":
        if not isinstance(value, list):
            return [ValidationError(path, f"expected array, got {type(value).__name__}")]
        item_schema = schema.get("items")
        if item_schema is not None:
            for i, item in enumerate(value):
                errors.extend(validate(item_schema, item, f"{path}[{i}]"))
        return errors
    if t == "string":
        if not isinstance(value, str):
            errors.append(ValidationError(path, f"expected string, got {type(value).__name__}"))
            return errors
        if "minLength" in schema and len(value) < schema["minLength"]:
            errors.append(ValidationError(path, f"shorter than minLength {schema['minLength']}"))
        if "maxLength" in schema and len(value) > schema["maxLength"]:
            errors.append(ValidationError(path, f"longer than maxLength {schema['maxLength']}"))
        if "pattern" in schema and not re.match(schema["pattern"], value):
            errors.append(ValidationError(path, f"does not match pattern {schema['pattern']!r}"))
    elif t == "number":
        if not isinstance(value, (int, float)) or isinstance(value, bool):
            errors.append(ValidationError(path, f"expected number, got {type(value).__name__}"))
            return errors
    elif t == "integer":
        if not isinstance(value, int) or isinstance(value, bool):
            errors.append(ValidationError(path, f"expected integer, got {type(value).__name__}"))
            return errors
    if "minimum" in schema and isinstance(value, (int, float)) and value < schema["minimum"]:
        errors.append(ValidationError(path, f"below minimum {schema['minimum']}"))
    if "maximum" in schema and isinstance(value, (int, float)) and value > schema["maximum"]:
        errors.append(ValidationError(path, f"above maximum {schema['maximum']}"))
    if "enum" in schema and value not in schema["enum"]:
        errors.append(ValidationError(path, f"value {value!r} not in enum {schema['enum']}"))
    return errors

print("✅ Validator ready")

# %% [markdown]
# ## Step 4 — Three-Branch Handler
#
# The model can fail in three ways:
# 1. **Refusal**: Model declines (handled as typed outcome, no retry)
# 2. **Parse error**: Invalid JSON
# 3. **Schema violation**: Valid JSON but violates constraints
#
# Under strict mode, only refusal is possible. Outside it, all three are real.

# %%
@dataclass
class ParsedResult:
    kind: str  # "ok", "refusal", "parse_error", "violation"
    payload: Any
    errors: list[ValidationError]

def process_model_output(raw: str, schema: dict) -> ParsedResult:
    """Handle three branches: parse error, refusal, success/violation."""
    if raw.startswith("__REFUSAL__"):
        return ParsedResult("refusal", raw.removeprefix("__REFUSAL__").strip(), [])
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError as e:
        return ParsedResult("parse_error", None, [ValidationError("$", str(e))])
    errs = validate(schema, parsed)
    if errs:
        return ParsedResult("violation", parsed, errs)
    return ParsedResult("ok", parsed, [])

print("✅ Handler ready")

# %% [markdown]
# ## Step 5 — Extract from Free-Text Email
#
# Now ask the model to extract invoice fields from a realistic purchase-order email. The model must return valid JSON matching the invoice schema.

# %%
email_text = """Subject: Order confirmation for Acme Corp

Dear vendor,

Please process this order:
- Item ABC-123 (qty 2, $49.99 each)
- Item XYZ-9 (qty 1, $120.00)

Total: $219.98
Currency: USD
Customer: Acme Corp

Thanks!"""

prompt = f"""Extract the invoice from this email. Reply ONLY with valid JSON matching the schema:
{json.dumps(INVOICE_SCHEMA, indent=2)}

Email:
{email_text}"""

response = await lrn_llm.call([{"role": "user", "content": prompt}], max_tokens=200)
raw_output = lrn_llm.text(response)
print("Raw LLM output:")
print(raw_output)

# %% [markdown]
# ## Step 6 — Validate the Output
#
# Parse and validate the model's response. If valid, we have a typed invoice. If violated, the error list tells us exactly what to fix.

# %%
result = process_model_output(raw_output, INVOICE_SCHEMA)
print(f"Outcome: {result.kind}")
if result.kind == "ok":
    print(f"✅ Success!")
    print(f"  Customer: {result.payload['customer']}")
    print(f"  Line items: {len(result.payload['line_items'])}")
    print(f"  Total: ${result.payload['total_usd']} {result.payload['currency']}")
elif result.kind == "refusal":
    print(f"⚠️  Model declined: {result.payload}")
else:
    print(f"❌ {result.kind}:")
    for err in result.errors:
        print(f"    {err}")

# %% [markdown]
# ## Step 7 — Demonstrate the Three Failure Modes
#
# Let's test what happens with ambiguous or invalid inputs.

# %%
# Test 1: Parse error (trailing comma in JSON)
print("\n" + "="*60)
print("Test 1: Parse error (invalid JSON)")
print("="*60)
bad_json = '{"customer": "Acme", "line_items": [], "total_usd": 0, "currency": "USD",}'
result1 = process_model_output(bad_json, INVOICE_SCHEMA)
print(f"Outcome: {result1.kind}")
for err in result1.errors:
    print(f"  {err}")

# %%
# Test 2: Schema violation (lowercase SKU, extra field, missing required)
print("\n" + "="*60)
print("Test 2: Schema violation (SKU pattern fails, extra field)")
print("="*60)
violated_json = json.dumps({
    "customer": "Acme",
    "line_items": [{"sku": "abc_123", "qty": 1, "unit_usd": 10, "discount": 0.1}],
    "total_usd": 10,
    "currency": "USD",
})
result2 = process_model_output(violated_json, INVOICE_SCHEMA)
print(f"Outcome: {result2.kind}")
for err in result2.errors:
    print(f"  {err}")

# %%
# Test 3: Missing required field
print("\n" + "="*60)
print("Test 3: Missing required field (total_usd)")
print("="*60)
missing_json = json.dumps({
    "customer": "Acme",
    "line_items": [{"sku": "ABC-123", "qty": 1, "unit_usd": 10}],
    "currency": "USD",
})
result3 = process_model_output(missing_json, INVOICE_SCHEMA)
print(f"Outcome: {result3.kind}")
for err in result3.errors:
    print(f"  {err}")

# %% [markdown]
# ## Step 8 — Retry Strategy
#
# Outside strict mode, the recovery pattern is: generate → parse → validate → if fail, inject error and retry (max 3x).
#
# Demonstrate a minimal retry with error injection.

# %%
async def extract_invoice_with_retry(email: str, max_retries: int = 2) -> ParsedResult:
    """Extract invoice with typed error feedback."""
    for attempt in range(max_retries):
        prompt = f"""Extract invoice from this email. Reply ONLY with valid JSON.
Schema: {json.dumps(INVOICE_SCHEMA)}

Email:
{email}"""
        if attempt > 0:
            prompt += f"\n\nPrevious attempt failed. Fix the JSON to match the schema exactly."
        
        response = await lrn_llm.call([{"role": "user", "content": prompt}], max_tokens=300)
        raw_output = lrn_llm.text(response)
        result = process_model_output(raw_output, INVOICE_SCHEMA)
        
        print(f"Attempt {attempt + 1}: {result.kind}")
        if result.kind == "ok":
            return result
        if result.kind == "refusal":
            print(f"  Model declined: {result.payload}")
            return result
        # Violation or parse error: show errors and retry
        for err in result.errors:
            print(f"  Error: {err}")
    
    return result

print("✅ Retry function ready")

# %%
# Try extraction with retry on a clean email
test_email = """Subject: Order from Widget Inc

We need:
- 5x SKU PROD-001 at $29.99 each
- 2x SKU WIDGET-99 at $149.00 each

Total: $449.95 USD
Customer name: Widget Inc
"""

final_result = await extract_invoice_with_retry(test_email, max_retries=2)
if final_result.kind == "ok":
    print("\n✅ Final invoice:")
    print(json.dumps(final_result.payload, indent=2))
else:
    print(f"\n⚠️ Final outcome: {final_result.kind}")

# %% [markdown]
# ## Step 9 — Key Takeaways
#
# - **Strict mode** (OpenAI, Anthropic tool_use, Gemini responseSchema) guarantees the output is valid JSON and matches the schema. Only refusal is possible.
# - **Constrained decoding** masks invalid tokens at generation time, eliminating parse errors and violations entirely.
# - **Your code** must still handle refusal as a typed outcome — the model can always decline.
# - **Outside strict mode**, you must validate and retry on schema violations (up to 3x).
# - **The schema is the source of truth**: Pydantic models, Zod schemas, and JSON Schema all encode the same constraints.

# %% [markdown]
# ## Try it yourself
#
# Below is a sandbox to extract from a custom email. Replace the email text and schema fields to match your domain.

# %%
# TODO: Replace with your own email and schema
custom_email = """Subject: Urgent: Fix server issue

Our main server (SKU SERV-MAINT) had a 2-hour outage.
Labor: 2 hours @ $150/hour = $300
Parts: none

Customer: CloudTech Inc
Total: $300 USD
"""

custom_result = await extract_invoice_with_retry(custom_email, max_retries=1)
if custom_result.kind == "ok":
    print("✅ Extracted:")
    print(json.dumps(custom_result.payload, indent=2))
else:
    print(f"Outcome: {custom_result.kind}")
    if custom_result.errors:
        for err in custom_result.errors:
            print(f"  {err}")
    elif custom_result.payload:
        print(f"Reason: {custom_result.payload}")
