# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/00-setup-and-tooling/01-dev-environment
# Used in courses: core curriculum

"""
Dev Environment - Build It notebook
Full interactive setup for Python, Node, Rust, Julia environments.
"""

# %% [markdown]
## Step 1: System Foundation

Check your system and install the basics.

# %% [markdown]

```bash
# macOS
xcode-select --install
brew install git curl wget

# Ubuntu/Debian
sudo apt update && sudo apt install -y build-essential git curl wget

# Windows (use WSL2)
wsl --install -d Ubuntu-24.04
```

# %% [markdown]
## Step 2: Python with uv

We use `uv` — it's 10-100x faster than pip and handles virtual environments automatically.

# %% [markdown]

```bash
curl -LsSf https://astral.sh/uv/install.sh | sh

uv python install 3.12

uv venv
source .venv/bin/activate  # or .venv\Scripts\activate on Windows

uv pip install numpy matplotlib jupyter
```

# %% [markdown]
Verify Python setup:

# %% [markdown]

```python
import sys
print(f"Python {sys.version}")

import numpy as np
print(f"NumPy {np.__version__}")
a = np.array([1, 2, 3])
print(f"Vector: {a}, dot product with itself: {np.dot(a, a)}")
```

# %% [markdown]
## Step 3: Node.js with pnpm

For TypeScript lessons (agents, MCP servers, web apps).

# %% [markdown]

```bash
curl -fsSL https://fnm.vercel.app/install | bash
fnm install 22
fnm use 22

npm install -g pnpm

node -e "console.log('Node', process.version)"
```

# %% [markdown]
## Step 4: Rust

For performance-critical lessons (inference, systems).

# %% [markdown]

```bash
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

rustc --version
cargo --version
```

# %% [markdown]
## Step 5: Julia (Optional)

For math-heavy lessons where Julia shines.

# %% [markdown]

```bash
curl -fsSL https://install.julialang.org | sh

julia -e 'println("Julia ", VERSION)'
```

# %% [markdown]
## Step 6: GPU Setup (If You Have One)

# %% [markdown]

```bash
# NVIDIA
nvidia-smi

# Install PyTorch with CUDA
uv pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
```

# %% [markdown]

```python
import torch
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
```

No GPU? No problem. Most lessons work on CPU. For training-heavy lessons, use Google Colab or cloud GPUs.

# %% [markdown]
## Step 7: Verify Everything

Run the verification script:

# %% [markdown]

```bash
python phases/00-setup-and-tooling/01-dev-environment/code/verify.py
```
