# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/14-agent-engineering/06-tool-use-and-function-calling
# Used in courses: AI-01, AI-02
# Framework: vanilla-openai
# Requires API key: False

"""none"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "/api/llm"  # same-origin proxy; server injects the gateway key
lrn_llm.DEFAULT_MODEL = "azure/gpt-5.4-mini"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    _key = lrn_llm.API_KEY
    if _key:
        headers["Authorization"] = "Bearer " + _key
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key

# %%
# Optional: set your API key if using an external endpoint
lrn_llm.API_KEY = ""
print("Endpoint:", lrn_llm.API_BASE)
print("Model:", lrn_llm.DEFAULT_MODEL)
print("Key set:", bool(lrn_llm.API_KEY))

# %% [markdown]
# ## Step 1 — Reachability

# %%
r = await lrn_llm.ping()
print("✅ LLM erreichbar:", r)

# %% [markdown]
# ## Step 2 — Understanding Tool Use
#
# Tool use (function calling) lets an LLM invoke external tools by returning structured data. The LLM reads a **tool catalog** (name, description, and input schema) and decides whether to call a tool, which one, and with what arguments.
#
# In this lesson, we'll:
# 1. Define a tool catalog
# 2. Ask the LLM to solve a problem using tools
# 3. Execute the tool calls and return results
# 4. Handle validation errors gracefully

# %% [markdown]
# ## Step 3 — Tool Catalog & Schema
#
# Every tool needs a schema so the LLM knows its signature. We define three tools:
# - **add**: sum two integers
# - **multiply**: product of two integers
# - **classify**: label a status as one of {"open", "closed", "pending"}

# %%
tools_catalog = [
    {
        "name": "add",
        "description": "Add two integers a and b. Use for any integer addition.",
        "input_schema": {
            "type": "object",
            "properties": {
                "a": {"type": "integer"},
                "b": {"type": "integer"}
            },
            "required": ["a", "b"]
        }
    },
    {
        "name": "multiply",
        "description": "Multiply two integers a and b. Prefer multiplication over looped addition.",
        "input_schema": {
            "type": "object",
            "properties": {
                "a": {"type": "integer"},
                "b": {"type": "integer"}
            },
            "required": ["a", "b"]
        }
    },
    {
        "name": "classify",
        "description": "Classify a status as one of the allowed labels. Use only 'open', 'closed', or 'pending'.",
        "input_schema": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "enum": ["open", "closed", "pending"]
                }
            },
            "required": ["status"]
        }
    }
]

print("Tool Catalog:")
for tool in tools_catalog:
    print(f"  • {tool['name']}: {tool['description']}")

# %% [markdown]
# ## Step 4 — Argument Validation
#
# We need to validate what the LLM returns. This includes:
# - **Type coercion**: if the model returns string "5" where an integer is needed
# - **Enum validation**: if the schema says status must be one of {"open", "closed", "pending"}
# - **Required fields**: reject if any required argument is missing
# - **Range validation**: check minimum/maximum for numbers

# %%
def coerce_value(value, prop_schema):
    """Try to coerce a value to match the schema type."""
    t = prop_schema.get("type")
    if t == "integer":
        if isinstance(value, int) and not isinstance(value, bool):
            return value, None
        if isinstance(value, str):
            try:
                return int(value), None
            except ValueError:
                return value, f"cannot coerce '{value}' to integer"
        return value, f"expected integer, got {type(value).__name__}"
    if t == "string":
        if isinstance(value, str):
            return value, None
        return value, f"expected string, got {type(value).__name__}"
    return value, None

def validate_tool_args(args, tool_schema):
    """Validate and coerce tool arguments against the schema."""
    errors = []
    props = tool_schema.get("properties", {})
    required = tool_schema.get("required", [])
    out = {}
    
    # Check required fields
    for name in required:
        if name not in args:
            errors.append(f"missing required: {name}")
    
    # Validate and coerce each argument
    for name, value in args.items():
        prop = props.get(name)
        if prop is None:
            errors.append(f"unknown field: {name}")
            continue
        
        # Coerce type
        coerced, err = coerce_value(value, prop)
        if err:
            errors.append(f"{name}: {err}")
            continue
        
        # Check enum
        if "enum" in prop and coerced not in prop["enum"]:
            errors.append(f"{name}: '{coerced}' not in {prop['enum']}")
            continue
        
        out[name] = coerced
    
    return out, errors

# Test validation with a valid call
test_args = {"a": 5, "b": 3}
validated, errors = validate_tool_args(test_args, tools_catalog[0]["input_schema"])
print(f"Valid args {test_args} -> {validated}")
print(f"Errors: {errors if errors else 'none'}")

# Test with invalid enum
test_args2 = {"status": "in_progress"}  # not in {"open", "closed", "pending"}
validated2, errors2 = validate_tool_args(test_args2, tools_catalog[2]["input_schema"])
print(f"\nInvalid args {test_args2} -> validation failed")
print(f"Errors: {errors2}")

# %% [markdown]
# ## Step 5 — Tool Execution & Results
#
# When validation passes, we execute the tool and return a result. If validation fails, we return a structured error message that the LLM can read and retry against.

# %%
def execute_tool(tool_name, args):
    """Execute a tool call with validated arguments."""
    # Find the tool definition
    tool_def = None
    for tool in tools_catalog:
        if tool["name"] == tool_name:
            tool_def = tool
            break
    
    if tool_def is None:
        return {"ok": False, "error": f"unknown tool: {tool_name}"}
    
    # Validate arguments
    validated, errors = validate_tool_args(args, tool_def["input_schema"])
    if errors:
        return {"ok": False, "error": "validation failed: " + "; ".join(errors)}
    
    # Execute
    try:
        if tool_name == "add":
            result = str(validated["a"] + validated["b"])
        elif tool_name == "multiply":
            result = str(validated["a"] * validated["b"])
        elif tool_name == "classify":
            result = f"classified as {validated['status']}"
        else:
            result = "unknown"
        return {"ok": True, "result": result}
    except Exception as e:
        return {"ok": False, "error": f"execution error: {e}"}

# Test execution
result1 = execute_tool("add", {"a": 2, "b": 3})
print(f"add(2, 3) -> {result1}")

result2 = execute_tool("multiply", {"a": 4, "b": 5})
print(f"multiply(4, 5) -> {result2}")

result3 = execute_tool("classify", {"status": "open"})
print(f"classify('open') -> {result3}")

result4 = execute_tool("classify", {"status": "invalid_status"})
print(f"classify('invalid_status') -> {result4}")

# %% [markdown]
# ## Step 6 — Agentic Loop: Ask the LLM to Use Tools
#
# Now we ask the LLM to solve a math problem by calling tools. The LLM gets the tool catalog and decides which tools to use. We parse its response, execute the tools, and feed back the results.

# %%
import re

# Prepare the system message with tool definitions
system_msg = ("""You are a helpful assistant with access to tools. When you need to use a tool,
format your response with tool calls like this:

<tool_call>
{"tool": "tool_name", "args": {"arg1": value1, "arg2": value2}}
</tool_call>

Available tools:
""" + json.dumps(tools_catalog, indent=2) + """

You must call tools to solve math problems. Always use the multiply tool for multiplication.
After I show tool results, respond with your final answer.""")

user_query = "What is 7 times 8? Then classify the result as 'open'."

print(f"User: {user_query}")
print("\n--- LLM decides which tools to call ---")

# Call LLM
response = await lrn_llm.call(
    [{"role": "user", "content": user_query}],
    system=system_msg,
    max_tokens=300
)

assistant_msg = lrn_llm.text(response)
print(f"LLM response:\n{assistant_msg}")

# %% [markdown]
# ## Step 7 — Parse & Execute Tool Calls
#
# Now we extract tool calls from the LLM's response, execute them, and collect results.

# %%
# Extract tool calls from LLM response
tool_calls = []
tool_call_pattern = r'<tool_call>\s*({.*?})\s*</tool_call>'

for match in re.finditer(tool_call_pattern, assistant_msg, re.DOTALL):
    try:
        call_json = json.loads(match.group(1))
        tool_calls.append(call_json)
    except json.JSONDecodeError:
        print(f"Could not parse tool call: {match.group(1)}")

print(f"Found {len(tool_calls)} tool call(s):")
for i, call in enumerate(tool_calls, 1):
    print(f"  {i}. {call['tool']}({call['args']})")

# Execute each tool call
tool_results = []
print("\n--- Executing tools ---")
for call in tool_calls:
    result = execute_tool(call["tool"], call["args"])
    tool_results.append(result)
    status = "✓" if result["ok"] else "✗"
    msg = result.get("result") or result.get("error", "unknown")
    print(f"  {status} {call['tool']}: {msg}")

# %% [markdown]
# ## Step 8 — Feed Results Back to LLM
#
# We send the tool execution results back to the LLM so it can formulate its final answer.

# %%
# Build results message
results_text = "\n".join([
    f"Tool '{call['tool']}' result: " + 
    (f"success: {result['result']}" if result["ok"] else f"error: {result['error']}")
    for call, result in zip(tool_calls, tool_results)
])

print(f"Results to send back to LLM:\n{results_text}")

# Get final answer from LLM
print("\n--- LLM formulates final answer ---")
final_response = await lrn_llm.call(
    [
        {"role": "user", "content": user_query},
        {"role": "assistant", "content": assistant_msg},
        {"role": "user", "content": f"Tool results:\n{results_text}\n\nNow provide your final answer."}
    ],
    system="You are a helpful assistant. Based on the tool results provided, give a clear final answer.",
    max_tokens=200
)

final_answer = lrn_llm.text(final_response)
print(f"Final answer:\n{final_answer}")

# %% [markdown]
# ## Step 9 — Handling Validation Failures
#
# A key engineering principle: **every validation failure should return a structured error** so the model can retry with the correct shape, never raising an exception to crash the loop.

# %%
# Demonstrate error recovery
print("Scenario: Model returns invalid argument types\n")

bad_calls = [
    {"tool": "add", "args": {"a": "not_a_number", "b": 5}},
    {"tool": "classify", "args": {"status": "in_progress"}},  # not in enum
    {"tool": "multiply", "args": {"a": 10}}  # missing required arg 'b'
]

print("Executing invalid tool calls:")
for call in bad_calls:
    result = execute_tool(call["tool"], call["args"])
    error = result.get("error", "unknown")
    print(f"\n  Tool: {call['tool']}")
    print(f"  Args: {call['args']}")
    print(f"  Error: {error}")
    print(f"  → Structured error returned (no crash, agent can retry)")

# %% [markdown]
# ## Step 10 — Key Takeaways
#
# 1. **Tool Use is Structured Output**: The LLM predicts JSON (tool name, arguments) that we execute.
# 2. **Schema is Load-Bearing**: Good descriptions tell the model *when* to use a tool; bad descriptions cause wrong-tool picks.
# 3. **Validation is Essential**: Type coercion, enum checks, required fields—all happen before execution.
# 4. **Errors are Observations**: When validation fails, return a readable error message the model can fix and retry.
# 5. **Parallel Dispatch**: Modern providers send multiple tool calls in one turn; use correlation IDs (tool_use_id) to track which result goes where.
# 6. **2026 Challenge**: Single-turn tool calling is solved. The hard problems are *long-horizon chaining* (40+ steps), *memory* (carrying context), *dynamic decisions* (choosing tools based on prior results), and *hallucination detection* (refusing to call when no tool fits).

# %% [markdown]
# ## Try It Yourself
#
# Edit the prompt below and make the LLM use tools to solve a different problem. The LLM has access to `add`, `multiply`, and `classify`.

# %%
# TODO: Change this query to test tool use with a different problem
# Example: "Calculate 15 times 12, then classify it as 'open'"
# Or: "What is the sum of 100 and 50? Classify as 'closed'."

custom_query = "What is 6 plus 9? Then classify the result as 'pending'."

print(f"User: {custom_query}")
print("\n--- LLM response with tool calls ---")

# Call LLM with the tool catalog
response = await lrn_llm.call(
    [{"role": "user", "content": custom_query}],
    system=system_msg,
    max_tokens=300
)

assistant_response = lrn_llm.text(response)
print(assistant_response)

# Parse and execute tools
tool_calls = []
for match in re.finditer(r'<tool_call>\s*({.*?})\s*</tool_call>', assistant_response, re.DOTALL):
    try:
        tool_calls.append(json.loads(match.group(1)))
    except json.JSONDecodeError:
        pass

if tool_calls:
    print("\n--- Tool execution ---")
    tool_results = []
    for call in tool_calls:
        result = execute_tool(call["tool"], call["args"])
        tool_results.append(result)
        status = "✓" if result["ok"] else "✗"
        msg = result.get("result") or result.get("error", "unknown")
        print(f"  {status} {call['tool']}({call['args']}) → {msg}")
else:
    print("(No tool calls extracted)")
