# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/19-capstone-projects/23-function-call-dispatcher
# Used in courses: AI-02
# Framework: openai-agents
# Requires API key: False

"""function-call-dispatcher"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "/api/llm"  # same-origin proxy; server injects the gateway key
lrn_llm.DEFAULT_MODEL = "azure/gpt-5.4-mini"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    _key = lrn_llm.API_KEY
    if _key:
        headers["Authorization"] = "Bearer " + _key
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key
#
# Set your API key (optional on LHIND network) and verify the endpoint.

# %%
# Optional: set your API key here if needed
lrn_llm.API_KEY = ""
print(f"Endpoint: {lrn_llm.API_BASE}")
print(f"Model: {lrn_llm.DEFAULT_MODEL}")
print(f"API key configured: {bool(lrn_llm.API_KEY)}")

# %% [markdown]
# ## Step 1 — Reachability
#
# Ping the LLM endpoint to ensure it's reachable.

# %%
r = await lrn_llm.ping()
print(f"✅ LLM erreichbar: {r}")

# %% [markdown]
# ## Step 2 — Understanding the Dispatcher Problem
#
# When an agent calls a tool, many things can go wrong:
# - **Timeout**: The handler takes too long (e.g., network timeout at 5 seconds)
# - **Transient error**: The backend was temporarily unavailable, but might work on retry
# - **Schema error**: The arguments don't match the schema (deterministic, don't retry)
# - **Idempotency**: A retry fires while the original is still in flight, causing a duplicate call (e.g., charging twice)
#
# The dispatcher sits between the agent loop and tool handlers. It wraps each call with:
# 1. Timeout enforcement via `asyncio.wait_for`
# 2. Retry logic with exponential backoff for retryable errors
# 3. Idempotency key deduplication to prevent duplicates
# 4. A concurrency limit to avoid overwhelming the backend
#
# Let's see how the LLM reason about these concepts.

# %%
# Ask the LLM to explain why timeouts matter in tool calling
message = "Why is it important to set a timeout on each tool call in an agent loop? Keep it to 2 sentences."
resp = await lrn_llm.call([{"role": "user", "content": message}], max_tokens=100)
answer = lrn_llm.text(resp)
print("Q: Why timeouts matter?")
print(f"A: {answer}")

# %% [markdown]
# ## Step 3 — Retry Logic with Exponential Backoff
#
# When a transient error occurs (e.g., upstream not ready), the dispatcher retries with exponential backoff:
# - Attempt 1: delay = 0s
# - Attempt 2: delay = 0.1s × (1 + random[0..0.5])
# - Attempt 3: delay = 0.4s × (1 + random[0..0.5])
#
# Let's ask the LLM to explain why jitter is added to backoff.

# %%
# Ask the LLM about jitter in exponential backoff
message = "Why is random jitter added to exponential backoff delays? Give one reason in 1 sentence."
resp = await lrn_llm.call([{"role": "user", "content": message}], max_tokens=100)
answer = lrn_llm.text(resp)
print("Q: Why jitter in backoff?")
print(f"A: {answer}")

# %% [markdown]
# ## Step 4 — Idempotency Key Deduplication
#
# A critical production bug: a retry that fires while the original is still in flight.
#
# Example:
# - 14:00:05.0 - First call to `payments.charge({amount: 100})`
# - 14:00:09.9 - First call still in flight (hangs at 4.9s)
# - 14:00:10.0 - Timeout fires, retry #1 dispatches immediately
# - Now both the original and retry are racing against the backend → charged twice!
#
# The dispatcher uses an **idempotency key** to deduplicate:
# - If the same key is already in flight, wait on the existing future
# - If the key recently completed (within 60s), return cached result
#
# Let's ask the LLM about idempotency.

# %%
# Ask the LLM about idempotency in tool dispatch
message = "In tool dispatch, an idempotency key prevents duplicate calls. What's a real-world example of why this matters? 1-2 sentences."
resp = await lrn_llm.call([{"role": "user", "content": message}], max_tokens=100)
answer = lrn_llm.text(resp)
print("Q: Idempotency examples?")
print(f"A: {answer}")

# %% [markdown]
# ## Step 5 — Error Mapping
#
# The dispatcher returns a single error envelope shape:
#
# ```python
# {
#   "kind": "timeout" | "transient" | "schema" | "not_found" | "internal" | "budget_exceeded",
#   "message": str,
#   "attempts": int,
#   "jsonrpc_code": int  # -32601, -32602, -32603
# }
# ```
#
# The agent loop uses `kind` to decide the next state:
# - `schema` or `not_found` → `on_error` (replan needed, never retried — deterministic)
# - `transient` → always retried with backoff
# - `timeout` → retried **only if the caller marked the call `idempotent`**; a timeout
#   doesn't tell you whether the handler's side effect already committed, so retrying
#   a non-idempotent call by default (e.g. a payment) could duplicate it
# - `budget_exceeded` → special state (stop, no budget left)
#
# Let's ask the LLM about error recovery.

# %%
# Ask the LLM about error handling in agent loops
message = "In an agent loop, should a schema error (invalid arguments) trigger a retry? Why or why not? 1-2 sentences."
resp = await lrn_llm.call([{"role": "user", "content": message}], max_tokens=100)
answer = lrn_llm.text(resp)
print("Q: Should schema errors retry?")
print(f"A: {answer}")

# %% [markdown]
# ## Step 6 — Concurrency Limiting
#
# When the agent loop has multiple tool calls, `gather` runs them all concurrently.
# With 40 tool calls, that's 40 open sockets/pipes. Most backends don't like that.
#
# The dispatcher wraps `gather` in a **semaphore** to limit concurrency:
# - Default: 8 concurrent calls
# - Each call acquires the semaphore before dispatch
# - Released on completion
# - Caller sees `gather`-shaped output but scheduling is bounded
#
# Let's build a mini dispatcher and use it with LLM calls.

# %%
import asyncio
import time
from dataclasses import dataclass
from typing import Any

@dataclass
class DispatchError:
    kind: str            # schema | not_found | transient | timeout | internal | budget_exceeded
    message: str
    attempts: int
    jsonrpc_code: int

@dataclass
class DispatchOk:
    result: Any
    attempts: int

class TransientError(Exception):
    """Raised by a handler to signal the error is retryable regardless of idempotency
    (the handler itself is asserting nothing committed yet)."""
    pass

class SchemaError(Exception):
    """Raised by a handler to signal invalid arguments — deterministic, never retried."""
    pass

class NotFoundError(Exception):
    """Raised when the dispatcher can't resolve the requested tool/handler —
    deterministic, never retried."""
    pass

JSONRPC_CODES = {
    "not_found": -32601,   # Method not found
    "schema": -32602,      # Invalid params
    "internal": -32603,    # Internal error
    "timeout": -32000,     # Server error (implementation-defined range)
    "transient": -32000,
    "budget_exceeded": -32000,
}

class MiniDispatcher:
    def __init__(self, max_attempts=3, timeout_s=5.0):
        self.max_attempts = max_attempts
        self.timeout_s = timeout_s
        self._inflight = {}   # idempotency_key -> Future, for calls currently running
        self._completed = {}  # idempotency_key -> (finished_at, result), 60s TTL

    def _cached(self, key):
        entry = self._completed.get(key)
        if entry is None:
            return None
        finished_at, result = entry
        if time.monotonic() - finished_at > 60.0:
            del self._completed[key]
            return None
        return result

    async def dispatch(self, handler_factory, *, timeout_s=None, idempotency_key=None, idempotent=False):
        """Dispatch handler_factory() with timeout, retry, and idempotency dedup.

        handler_factory: a zero-arg callable returning a fresh coroutine each call —
        a coroutine object can only be awaited once, so a retry needs a fresh one per
        attempt, not the same object re-awaited.
        idempotency_key: if two calls share a key, a call already in flight is joined
        instead of re-run, and a call that completed within the last 60s returns the
        cached result instead of running again.
        idempotent: whether a *timeout* on this call is safe to retry. A timeout alone
        doesn't tell you whether the handler's side effect already committed — retrying
        a non-idempotent call (e.g. a payment) can duplicate it. TransientError always
        retries regardless, because raising it is the handler asserting "nothing
        committed yet".
        """
        if idempotency_key is not None:
            cached = self._cached(idempotency_key)
            if cached is not None:
                return cached
            inflight = self._inflight.get(idempotency_key)
            if inflight is not None:
                return await inflight
            fut = asyncio.get_running_loop().create_future()
            self._inflight[idempotency_key] = fut

        result = await self._run_with_retries(handler_factory, timeout_s or self.timeout_s, idempotent)

        if idempotency_key is not None:
            del self._inflight[idempotency_key]
            self._completed[idempotency_key] = (time.monotonic(), result)
            fut.set_result(result)
        return result

    async def _run_with_retries(self, handler_factory, timeout_s, idempotent):
        """The actual timeout + retry + error-classification loop. Subclasses that add
        concurrency limiting wrap this method rather than dispatch() — see Step 8 —
        so a call that only joins an in-flight duplicate never has to wait for a
        concurrency slot just to receive that result."""
        attempt = 0
        last_error = None
        while attempt < self.max_attempts:
            attempt += 1
            try:
                result = await asyncio.wait_for(handler_factory(), timeout=timeout_s)
                return DispatchOk(result=result, attempts=attempt)
            except asyncio.TimeoutError:
                last_error = DispatchError(kind="timeout", message=f"timeout after {timeout_s}s",
                                            attempts=attempt, jsonrpc_code=JSONRPC_CODES["timeout"])
                if not idempotent:
                    return last_error  # may have partially committed — unsafe to retry
            except TransientError as e:
                last_error = DispatchError(kind="transient", message=str(e), attempts=attempt,
                                            jsonrpc_code=JSONRPC_CODES["transient"])
            except SchemaError as e:
                return DispatchError(kind="schema", message=str(e), attempts=attempt,
                                      jsonrpc_code=JSONRPC_CODES["schema"])
            except NotFoundError as e:
                return DispatchError(kind="not_found", message=str(e), attempts=attempt,
                                      jsonrpc_code=JSONRPC_CODES["not_found"])
            if attempt < self.max_attempts:
                await asyncio.sleep(0.1 * (2 ** (attempt - 1)))  # backoff
        return last_error or DispatchError(kind="internal", message="unknown error",
                                            attempts=attempt, jsonrpc_code=JSONRPC_CODES["internal"])

print("✅ MiniDispatcher defined (idempotency dedup, retry-only-if-idempotent timeouts, JSON-RPC error codes)")

# %% [markdown]
# ## Step 7 — A Simple Agent Loop Using the Dispatcher
#
# Now let's build a simple agent loop that:
# 1. Calls the LLM with a system prompt and user message
# 2. If the LLM returns a tool call (imagined as a field in the response), dispatch it through our dispatcher
# 3. Feed the result back to the LLM
#
# For this demo, we'll ask the LLM to classify a user intent (rather than actually parse tool calls), but we'll dispatch the classification request itself.

# %%
# Demo: LLM-based intent classification with dispatcher

async def classify_intent_handler(query: str):
    """Handler that calls the LLM to classify intent."""
    system = "You are an intent classifier. Respond with exactly one word: greeting, question, or command."
    msg = f"Classify this user message: '{query}'"
    resp = await lrn_llm.call(
        [{"role": "user", "content": msg}],
        system=system,
        max_tokens=10
    )
    intent = lrn_llm.text(resp).strip().lower()
    return {"intent": intent, "query": query}

dispatcher = MiniDispatcher(max_attempts=2, timeout_s=10.0)

# Dispatch a single call. handler_factory is a zero-arg callable (here a lambda) so a
# retry can create a fresh coroutine instead of re-awaiting an already-used one.
result = await dispatcher.dispatch(
    lambda: classify_intent_handler("Hello, how are you?"),
    timeout_s=10.0
)

if isinstance(result, DispatchOk):
    print(f"✅ Intent classification succeeded (attempts: {result.attempts})")
    print(f"   Result: {result.result}")
else:
    print(f"❌ Dispatch failed: {result.kind} after {result.attempts} attempt(s)")
    print(f"   {result.message}")

# %% [markdown]
# ## Step 8 — Multi-Tool Dispatch with Concurrency Limit
#
# When the agent needs to call multiple tools (or make multiple LLM requests), we use a semaphore to limit concurrency. Let's dispatch several classification tasks in parallel, bounded to 2 concurrent calls.

# %%
# Multi-dispatch with concurrency limit

class ConcurrentDispatcher(MiniDispatcher):
    def __init__(self, max_attempts=3, timeout_s=5.0, concurrency=2):
        super().__init__(max_attempts, timeout_s)
        self._sem = asyncio.Semaphore(concurrency)

    async def _run_with_retries(self, handler_factory, timeout_s, idempotent):
        # Bounds the actual backend calls to `concurrency` at a time. Wrapping
        # _run_with_retries (not dispatch) means a call that only joins an in-flight
        # duplicate via idempotency_key never has to wait on this semaphore.
        async with self._sem:
            return await super()._run_with_retries(handler_factory, timeout_s, idempotent)

    async def dispatch_many(self, factories):
        """Dispatch multiple handler factories with bounded concurrency."""
        return await asyncio.gather(*[self.dispatch(f) for f in factories])

conc_dispatcher = ConcurrentDispatcher(max_attempts=2, timeout_s=10.0, concurrency=2)

# Create multiple classification tasks as factories (zero-arg callables), not
# already-created coroutines — see the dispatch() docstring in Step 6.
tasks = [
    lambda: classify_intent_handler("What time is it?"),
    lambda: classify_intent_handler("Please send an email."),
    lambda: classify_intent_handler("Hi there!"),
]

results = await conc_dispatcher.dispatch_many(tasks)

print(f"Dispatched {len(results)} tasks with concurrency limit=2")
for i, res in enumerate(results):
    if isinstance(res, DispatchOk):
        print(f"  Task {i}: {res.result['intent']} (attempts={res.attempts})")
    else:
        print(f"  Task {i}: {res.kind}")

# %% [markdown]
# ## Step 9 — Error Scenarios
#
# Each scenario below actually calls `dispatcher.dispatch()` and inspects the real
# `DispatchOk`/`DispatchError` it returns — nothing here is a printed description.

# %%
def make_schema_check_handler(user_id):
    """Returns a handler factory that validates its own argument first — this is what
    makes a schema error fail fast instead of retrying."""
    async def _run():
        if not isinstance(user_id, int):
            raise SchemaError(f"user_id must be an int, got {type(user_id).__name__!r}")
        return {"user_id": user_id}
    return _run

_flaky_state = {"calls": 0}
async def flaky_handler():
    """Fails with a transient error on the first attempt, succeeds on retry."""
    if _flaky_state["calls"] == 0:
        _flaky_state["calls"] += 1
        raise TransientError("upstream not ready")
    return {"ok": True}

async def slow_handler():
    """Always exceeds a short timeout — a real asyncio.TimeoutError, not a description of one."""
    await asyncio.sleep(2)
    return {"ok": True}

_charge_calls = {"n": 0}
async def counted_handler():
    """Counts how many times it actually ran — used to prove idempotency dedup below."""
    _charge_calls["n"] += 1
    await asyncio.sleep(0.05)
    return {"charged": True}

scenario_dispatcher = MiniDispatcher(max_attempts=3, timeout_s=10.0)

# 1. Happy path
r1 = await scenario_dispatcher.dispatch(lambda: classify_intent_handler("What is 2+2?"))
if isinstance(r1, DispatchOk):
    print(f"1. Happy path               -> ok (attempts={r1.attempts})")
else:
    print(f"1. Happy path               -> unexpected error: {r1.kind}")

# 2. Schema error — fails fast, no retry
r2 = await scenario_dispatcher.dispatch(make_schema_check_handler("not-a-number"))
print(f"2. Schema error             -> kind={r2.kind} jsonrpc_code={r2.jsonrpc_code} "
      f"attempts={r2.attempts} (no retry)")

# 3. Transient error — retried, succeeds on the 2nd attempt
_flaky_state["calls"] = 0
r3 = await scenario_dispatcher.dispatch(flaky_handler)
status = "ok after retry" if isinstance(r3, DispatchOk) else r3.kind
print(f"3. Transient error          -> {status} (attempts={r3.attempts})")

# 4. Timeout on a non-idempotent call (the default) — fails immediately, no retry
r4 = await scenario_dispatcher.dispatch(slow_handler, timeout_s=0.2)
print(f"4. Timeout, non-idempotent  -> kind={r4.kind} jsonrpc_code={r4.jsonrpc_code} "
      f"attempts={r4.attempts} (no retry: may have already committed)")

# 5. Timeout on an idempotent call — retried up to max_attempts
r5 = await scenario_dispatcher.dispatch(slow_handler, timeout_s=0.2, idempotent=True)
print(f"5. Timeout, idempotent      -> kind={r5.kind} jsonrpc_code={r5.jsonrpc_code} "
      f"attempts={r5.attempts} (retried up to max_attempts={scenario_dispatcher.max_attempts})")

# 6. Idempotency-key dedup — two concurrent calls sharing a key collapse into one
# underlying handler invocation.
_charge_calls["n"] = 0
await asyncio.gather(
    scenario_dispatcher.dispatch(counted_handler, idempotency_key="charge-42"),
    scenario_dispatcher.dispatch(counted_handler, idempotency_key="charge-42"),
)
print(f"6. Idempotency dedup        -> handler ran {_charge_calls['n']}x for 2 concurrent "
      f"calls sharing a key (expected: 1)")

# %% [markdown]
# ## Step 10 — Try It Yourself
#
# The cell below dispatches a batch of sentiment-analysis calls (same scenario
# as Step 9) through the `ConcurrentDispatcher` — but it has one deliberate bug.
# Find and fix the `# TODO: fix this` marker so all three dispatches complete
# with `DispatchOk` instead of raising an error.
#
# Remember:
# - The dispatcher handles timeout, retry, and concurrency
# - You get back either `DispatchOk(result, attempts)` or `DispatchError(kind, message, attempts)`
# - The LLM is called via `await lrn_llm.call([{...}], system=..., max_tokens=...)`

# %%
# TODO: fix this - one of the keyword arguments below is misspelled, so every
# call to lrn_llm.call() inside sentiment_handler raises TypeError("_lrn_call()
# got an unexpected keyword argument 'syste'") instead of dispatching. Find the
# typo and fix it so the sentiment dispatches below succeed.

# Sentiment analysis (same scenario as Step 9's classify_intent_handler, just a
# different classification task)
async def sentiment_handler(text: str):
    system = "Classify the sentiment as positive, negative, or neutral. Respond with one word."
    msg = f"Analyze sentiment: '{text}'"
    resp = await lrn_llm.call(
        [{"role": "user", "content": msg}],
        syste=system,  # TODO: fix this - misspelled kwarg, should be `system=system`
        max_tokens=10
    )
    return {"sentiment": lrn_llm.text(resp).strip(), "text": text}

# Test inputs
test_texts = [
    "I love this product!",
    "This is terrible.",
    "It's okay, nothing special.",
]

# Dispatch all sentiment analyses with concurrency limit. Each task is a zero-arg
# factory (not an already-created coroutine) — see the dispatch() docstring in Step 6.
task_dispatcher = ConcurrentDispatcher(max_attempts=2, timeout_s=10.0, concurrency=2)
tasks = [(lambda t=t: sentiment_handler(t)) for t in test_texts]
sentiment_results = await task_dispatcher.dispatch_many(tasks)

print("Sentiment Analysis Results:")
for i, res in enumerate(sentiment_results):
    if isinstance(res, DispatchOk):
        print(f"  {test_texts[i][:40]:40s} → {res.result['sentiment']} (attempts={res.attempts})")
    else:
        print(f"  {test_texts[i][:40]:40s} → ERROR ({res.kind})")

# Self-check: once the typo is fixed, every dispatch should succeed (DispatchOk),
# using the same isinstance(result, DispatchOk)/DispatchError pattern as Step 9.
assert all(isinstance(res, DispatchOk) for res in sentiment_results), (
    "Not all sentiment dispatches succeeded — did you fix the misspelled kwarg above?"
)
print("✅ Self-check passed: all sentiment dispatches succeeded")
