# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/13-tools-and-protocols/07-building-an-mcp-server
# Used in courses: AI-03
# Framework: none
# Requires API key: False

"""Building a functioning MCP server with tools, resources, and prompts — learning through implementation and LLM interaction"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "https://gateway.lhind.ai/v1"
lrn_llm.DEFAULT_MODEL = "azure/gpt-4o"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    _key = lrn_llm.API_KEY
    if not _key:
        try:
            import js as _js
            _key = getattr(_js, "__LRN_LLM_KEY__", "") or ""
        except Exception:
            _key = ""
    if _key:
        headers["Authorization"] = "Bearer " + _key
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key
#
# Set your API key (optional on LHIND network) and verify the endpoint.

# %%
lrn_llm.API_KEY = ""  # Leave empty on LHIND network; set if using external endpoint
print(f"Endpoint: {lrn_llm.API_BASE}")
print(f"Model: {lrn_llm.DEFAULT_MODEL}")
print(f"Key set: {bool(lrn_llm.API_KEY)}")

# %% [markdown]
# ## Step 1 — Reachability
#
# Ping the LLM endpoint to confirm it's reachable.

# %%
r = await lrn_llm.ping()
print(f"✅ LLM reachable: {r['ok']} · model: {r['model']}")

# %% [markdown]
# ## Step 2 — Build a Notes MCP Server (In-Memory)
#
# We'll implement a minimal MCP server in Python that exposes three tools (`notes_list`, `notes_search`, `notes_create`), resources (`notes://`), and a prompt template (`review_note`). This mirrors the lesson's main.py but in a notebook cell.

# %%
import uuid

# In-memory note store
NOTES = {
    "note-1": {"title": "MCP overview", "body": "Primitives: tools, resources, prompts. JSON-RPC over stdio.", "tag": "mcp"},
    "note-2": {"title": "Function calling", "body": "Tools let models invoke external logic.", "tag": "api"},
}

# Tool executors
def exec_notes_list(args):
    tag = args.get("tag")
    items = []
    for nid, note in NOTES.items():
        if tag and note.get("tag") != tag:
            continue
        items.append({"id": nid, "title": note["title"], "tag": note.get("tag", "")})
    return [{"type": "text", "text": json.dumps(items)}]

def exec_notes_search(args):
    q = args["query"].lower()
    limit = args.get("limit", 10)
    hits = []
    for nid, n in NOTES.items():
        if q in n["title"].lower() or q in n["body"].lower():
            hits.append({"id": nid, "title": n["title"]})
    return [{"type": "text", "text": json.dumps(hits[:limit])}]

def exec_notes_create(args):
    nid = f"note-{uuid.uuid4().hex[:6]}"
    NOTES[nid] = {"title": args["title"], "body": args["body"], "tag": args.get("tag", "")}
    return [
        {"type": "text", "text": f"Created {nid}"},
        {"type": "resource", "resource": {"uri": f"notes://{nid}", "text": args["body"]}},
    ]

TOOL_EXECUTORS = {
    "notes_list": exec_notes_list,
    "notes_search": exec_notes_search,
    "notes_create": exec_notes_create,
}

print("✅ Notes server initialized with 2 notes")

# %% [markdown]
# ## Step 3 — Implement the MCP Dispatcher
#
# The dispatcher routes JSON-RPC method calls to handlers. Each handler returns a structured result (tools/list, tools/call with content blocks, resources/list, resources/read, prompts/list, prompts/get).

# %%
# Tool and prompt definitions
TOOLS = [
    {
        "name": "notes_list",
        "description": "List all notes, optionally filtered by tag.",
        "inputSchema": {"type": "object", "properties": {"tag": {"type": "string"}}, "required": []},
        "annotations": {"readOnlyHint": True, "idempotentHint": True},
    },
    {
        "name": "notes_search",
        "description": "Search notes by keyword in title or body.",
        "inputSchema": {
            "type": "object",
            "properties": {"query": {"type": "string"}, "limit": {"type": "integer"}},
            "required": ["query"],
        },
        "annotations": {"readOnlyHint": True},
    },
    {
        "name": "notes_create",
        "description": "Create a new note with title, body, and optional tag.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "title": {"type": "string"},
                "body": {"type": "string"},
                "tag": {"type": "string"},
            },
            "required": ["title", "body"],
        },
        "annotations": {"destructiveHint": False},
    },
]

PROMPTS = [
    {
        "name": "review_note",
        "description": "Produce a critique of a note with improvements.",
        "arguments": [{"name": "note_id", "description": "The id of the note to review", "required": True}],
    }
]

print(f"✅ Tool registry: {len(TOOLS)} tools, {len(PROMPTS)} prompt template")

# %% [markdown]
# ## Step 4 — Implement MCP Handlers
#
# Handlers process initialize, tools/list, tools/call, resources/list, resources/read, prompts/list, and prompts/get requests.

# %%
def handle_initialize(params):
    return {
        "protocolVersion": "2025-11-25",
        "capabilities": {
            "tools": {"listChanged": False},
            "resources": {"listChanged": False, "subscribe": False},
            "prompts": {"listChanged": False},
        },
        "serverInfo": {"name": "notes-notebook", "version": "1.0.0"},
    }

def handle_tools_list(params):
    return {"tools": TOOLS}

def handle_tools_call(params):
    name = params["name"]
    args = params.get("arguments", {})
    if name not in TOOL_EXECUTORS:
        return {"content": [{"type": "text", "text": f"unknown tool {name}"}], "isError": True}
    try:
        content = TOOL_EXECUTORS[name](args)
        return {"content": content, "isError": False}
    except Exception as e:
        return {"content": [{"type": "text", "text": str(e)}], "isError": True}

def handle_resources_list(params):
    items = [{"uri": f"notes://{nid}", "name": n["title"], "mimeType": "text/markdown"} for nid, n in NOTES.items()]
    return {"resources": items}

HANDLERS = {
    "initialize": handle_initialize,
    "tools/list": handle_tools_list,
    "tools/call": handle_tools_call,
    "resources/list": handle_resources_list,
}

print(f"✅ Handlers registered: {list(HANDLERS.keys())}")

# %% [markdown]
# ## Step 5 — Test the Server Locally
#
# Before using the LLM, test the server by calling handlers directly with JSON-RPC method calls.

# %%
# Test: initialize
msg = {"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {}}
result = HANDLERS["initialize"](msg.get("params", {}))
print(f"initialize → protocolVersion: {result['protocolVersion']}, serverInfo: {result['serverInfo']['name']}")

# %% [markdown]
# ## Step 6 — Test tools/list
#
# Request the list of available tools.

# %%
# Test: tools/list
msg = {"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {}}
result = HANDLERS["tools/list"](msg.get("params", {}))
print(f"tools/list → {len(result['tools'])} tools:")
for t in result["tools"]:
    print(f"  - {t['name']}: {t['description'][:50]}...")

# %% [markdown]
# ## Step 7 — Test tools/call: notes_search
#
# Invoke a tool through the dispatcher.

# %%
# Test: tools/call with notes_search
msg = {
    "jsonrpc": "2.0",
    "id": 3,
    "method": "tools/call",
    "params": {"name": "notes_search", "arguments": {"query": "MCP"}},
}
result = HANDLERS["tools/call"](msg.get("params", {}))
print(f"notes_search('MCP') → {result['content'][0]['text']}")

# %% [markdown]
# ## Step 8 — Ask an LLM to Use Your Server
#
# Now let's ask the LLM to interact with the notes server by calling tools. The LLM will see the tool definitions and decide which tool to invoke.

# %%
# Ask LLM to list notes
messages = [{"role": "user", "content": "What notes are currently in the system?"}]
system = f"""You are a helpful assistant. You have access to an MCP server with these tools:
{json.dumps([{'name': t['name'], 'description': t['description']} for t in TOOLS], indent=2)}

Respond naturally, and if asked, use the tools available."""

r = await lrn_llm.call(messages, system=system, max_tokens=150)
response = lrn_llm.text(r)
print(f"LLM: {response}")

# %% [markdown]
# ## Step 9 — Test tools/call: notes_create
#
# Create a new note through the server, which the LLM helped us decide on.

# %%
# Create a note
msg = {
    "jsonrpc": "2.0",
    "id": 4,
    "method": "tools/call",
    "params": {
        "name": "notes_create",
        "arguments": {
            "title": "LLM Integration",
            "body": "Connecting language models to tool-calling servers enables dynamic reasoning.",
            "tag": "llm",
        },
    },
}
result = HANDLERS["tools/call"](msg.get("params", {}))
print(f"notes_create → {result['content'][0]['text']}")
print(f"Total notes now: {len(NOTES)}")

# %% [markdown]
# ## Step 10 — Ask LLM to Search and Summarize
#
# Ask the LLM to search for notes and summarize what it finds.

# %%
# Ask LLM to search and summarize
all_notes = json.dumps([{"id": nid, "title": n["title"], "body": n["body"][:60]} for nid, n in NOTES.items()], indent=2)
messages = [{"role": "user", "content": f"Here are our current notes:\n{all_notes}\n\nWhat themes do you see across them?"}]

r = await lrn_llm.call(messages, system="You are a note analyst. Analyze the themes and patterns.", max_tokens=200)
response = lrn_llm.text(r)
print(f"LLM Analysis:\n{response}")

# %% [markdown]
# ## Step 11 — MCP Server as a Protocol Bridge
#
# Understand how the MCP protocol bridges human intent → LLM reasoning → tool execution.

# %%
# Simulate a full workflow: user request → LLM decides tools → server executes
print("\n=== Full Workflow ===")
print("1. User: 'Create a note about JSON-RPC and then list all mcp-tagged notes.'")
print("2. LLM reasons: 'I need to call notes_create, then notes_list with tag=mcp.'")
print("3. Server executes:")

# Step 1: Create
create_result = TOOL_EXECUTORS["notes_create"]({"title": "JSON-RPC Protocol", "body": "JSON-RPC 2.0 spec defines request/response/notification semantics.", "tag": "mcp"})
print(f"   - notes_create: {create_result[0]['text']}")

# Step 2: List with filter
list_result = TOOL_EXECUTORS["notes_list"]({"tag": "mcp"})
print(f"   - notes_list(tag='mcp'): {list_result[0]['text']}")
print(f"\n4. Result: Now {len(NOTES)} total notes, {len(json.loads(list_result[0]['text']))} tagged 'mcp'")

# %% [markdown]
# ## Step 12 — Understand Content Blocks
#
# MCP returns results as **content blocks**—typed elements in the `content` array. Tools can return text, resources, images, or errors.

# %%
# Demonstrate content block structure
block_types = {
    "text": {"type": "text", "text": "Plain text result"},
    "resource": {"type": "resource", "resource": {"uri": "notes://example", "text": "Resource body"}},
    "error": {"type": "text", "text": "Error message (set isError: true)"},
}

print("MCP Content Block Types:")
for name, block in block_types.items():
    print(f"  {name}: {json.dumps(block)}")

print(f"\nExample: notes_create returns {len(create_result)} blocks:")
for i, b in enumerate(create_result, 1):
    print(f"  Block {i}: type={b.get('type')}, keys={list(b.keys())}")

# %% [markdown]
# ## Step 13 — Ask LLM to Critique the Server Design
#
# Use the LLM to reflect on the server's architecture and suggest improvements.

# %%
# Ask LLM to critique the server
server_spec = f"""MCP Notes Server:
- Tools: notes_list (filter by tag), notes_search (keyword), notes_create (title+body+tag)
- Resources: notes:// URIs for individual notes
- Prompts: review_note (critique a note)
- Storage: in-memory dict
- Annotations: readOnlyHint, destructiveHint for tool safety

Current implementation: {len(NOTES)} notes, pure function style."""

messages = [{"role": "user", "content": f"Design critique: what are 2 limitations of this server, and 1 way to extend it?\n\n{server_spec}"}]

r = await lrn_llm.call(messages, system="You are a software architect reviewing MCP server design.", max_tokens=250)
response = lrn_llm.text(r)
print(f"Architect Review:\n{response}")

# %% [markdown]
# ## Step 14 — Graduation Path: FastMCP
#
# The lesson shows that this stdlib implementation can graduate to FastMCP (Python SDK) or TypeScript SDK without changing the wire behavior. The key insight: the three primitives (tools, resources, prompts) and content blocks stay the same; only the wrapper changes.
#
# Key pattern:
# ```python
# from fastmcp import FastMCP
# app = FastMCP("notes")
#
# @app.tool()
# def notes_create(title: str, body: str, tag: str = "") -> str:
#     nid = f"note-{uuid.uuid4().hex[:6]}"
#     NOTES[nid] = {"title": title, "body": body, "tag": tag}
#     return f"Created {nid}"
# ```
#
# The dispatch loop, JSON-RPC parsing, and content blocks are handled by the SDK.

# %%
# Summarize the server capabilities
print("\n=== MCP Server Summary ===")
print(f"Protocol: {HANDLERS['initialize']({}).get('protocolVersion')}")
print(f"Server: {HANDLERS['initialize']({}).get('serverInfo')}")
print(f"Primitives supported:")
for method in HANDLERS:
    print(f"  - {method}")
print(f"\nTools: {', '.join(t['name'] for t in TOOLS)}")
print(f"Stored notes: {list(NOTES.keys())}")
print(f"\nKey insight: This pure-function server can be wrapped by FastMCP for production use.")

# %% [markdown]
# ## Try It Yourself
#
# Now it's your turn. Create a tool that works with the notes server and ask the LLM to use it.
#
# **TODO:** Define a new tool (e.g., `notes_tag_rename` to rename a tag across all notes, or `notes_export` to return notes as markdown). Then add it to `TOOL_EXECUTORS`, call the LLM with the updated tool definition, and invoke it.
#
# Start by editing the cell below:

# %%
# TODO: Implement a new tool for the notes server
# Example: notes_tag_rename(old_tag: str, new_tag: str) -> str

# Step 1: Define the executor
def exec_notes_tag_rename(args):
    """Rename a tag across all notes."""
    old_tag = args["old_tag"]
    new_tag = args["new_tag"]
    count = 0
    for note in NOTES.values():
        if note.get("tag") == old_tag:
            note["tag"] = new_tag
            count += 1
    return [{"type": "text", "text": f"Renamed tag '{old_tag}' to '{new_tag}' in {count} notes"}]

# Step 2: Add to registry
TOOL_EXECUTORS["notes_tag_rename"] = exec_notes_tag_rename

# Step 3: Add to tool definitions
TOOLS.append({
    "name": "notes_tag_rename",
    "description": "Rename a tag across all notes.",
    "inputSchema": {
        "type": "object",
        "properties": {
            "old_tag": {"type": "string"},
            "new_tag": {"type": "string"},
        },
        "required": ["old_tag", "new_tag"],
    },
    "annotations": {"destructiveHint": True},
})

print(f"✅ Added notes_tag_rename tool")
print(f"Total tools: {len(TOOLS)}")

# Step 4: Ask LLM to use it
messages = [{"role": "user", "content": "Rename the 'api' tag to 'function-calling' in all notes. Show me the result."}]
system = f"You have access to tools: {json.dumps([{'name': t['name']} for t in TOOLS], indent=2)}"

r = await lrn_llm.call(messages, system=system, max_tokens=150)
response = lrn_llm.text(r)
print(f"\nLLM Response: {response}")

# Step 5: Verify the change
result = TOOL_EXECUTORS["notes_tag_rename"]({"old_tag": "api", "new_tag": "function-calling"})
print(f"Execute: {result[0]['text']}")
print(f"Updated notes: {json.dumps({nid: n['tag'] for nid, n in NOTES.items()}, indent=2)}")
