# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/11-llm-engineering/02-few-shot-cot
# Used in courses: AI-18
# Framework: none
# Requires API key: False

"""client_brief_refinement"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "https://gateway.lhind.ai/v1"
lrn_llm.DEFAULT_MODEL = "azure/gpt-4o"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    _key = lrn_llm.API_KEY
    if not _key:
        try:
            import js as _js
            _key = getattr(_js, "__LRN_LLM_KEY__", "") or ""
        except Exception:
            _key = ""
    if _key:
        headers["Authorization"] = "Bearer " + _key
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key
#
# Set your API key below if needed (optional on LHIND network). The gateway uses the default Azure GPT-4o model.

# %%
lrn_llm.API_KEY = ""  # Leave empty for LHIND network access
print(f"Endpoint: {lrn_llm.API_BASE}")
print(f"Model: {lrn_llm.DEFAULT_MODEL}")
print(f"Key set: {bool(lrn_llm.API_KEY)}")

# %% [markdown]
# ## Step 1 — Reachability
#
# Ping the LLM to verify connectivity.

# %%
r = await lrn_llm.ping()
print("✅ LLM erreichbar:", r)

# %% [markdown]
# ## The Scenario
#
# You are an LHIND consultant. A client sends you an ambiguous business brief that needs clarification:
#
# > "Janet's ducks lay 16 eggs per day. She eats three for breakfast every morning and bakes muffins for her friends every day with four. She sells every remaining egg at the farmers' market for $2. How much does she make every day at the farmers' market?"
#
# The problem statement has unclear details, and you need to help the client nail down the logic. You'll compare two prompting strategies:
#
# 1. **Zero-shot**: Ask the LLM directly without examples (fast, but reasoning may be vague)
# 2. **Few-shot + CoT**: Show worked examples with step-by-step reasoning (slower, but clearer logic chain)
#
# Let's see which approach produces reasoning you'd actually want to show the client.

# %% [markdown]
# ## Step 2 — Zero-Shot Prompt (Direct Question)
#
# First, ask the LLM to solve the problem without any examples. Notice how the reasoning is compressed and the logic path is harder to verify.

# %%
zero_shot_prompt = """You are a business analyst. Solve this client's business math problem clearly.
End your response with 'The answer is [number]'.

Problem:
Janet's ducks lay 16 eggs per day. She eats three for breakfast every morning and bakes muffins for her friends every day with four. She sells every remaining egg at the farmers' market for $2. How much does she make every day at the farmers' market?

Reasoning:"""

r_zero = await lrn_llm.call(
    [{"role": "user", "content": zero_shot_prompt}],
    system="You are a business analyst solving word problems.",
    max_tokens=300
)
zero_shot_answer = lrn_llm.text(r_zero)
print("=== ZERO-SHOT RESPONSE ===")
print(zero_shot_answer)

# %% [markdown]
# ## Step 3 — Few-Shot + CoT Prompt (With Examples)
#
# Now, provide the same LLM with **worked examples** that show step-by-step reasoning. The model will pattern-match on the examples and provide more explicit reasoning steps.

# %%
few_shot_cot_prompt = """I'll show you some examples of business math problems solved step-by-step, then ask you to solve a new one the same way.

Example 1:
Q: A robe takes 2 bolts of blue fiber and half that much white fiber. How many bolts in total does it take?
A: It takes 2 bolts of blue fiber. Half of 2 is 1, so it takes 1 bolt of white fiber. In total, 2 + 1 = 3 bolts. The answer is 3.

Example 2:
Q: Josh decides to try flipping a house. He buys a house for $80,000 and puts $50,000 in repairs. This increased the value of the house by 150%. How much profit did he make?
A: The house cost $80,000. Repairs cost $50,000. Total investment: 80,000 + 50,000 = $130,000. The value increased by 150% of $80,000: 80,000 * 1.5 = $120,000. New value: 80,000 + 120,000 = $200,000. Profit: 200,000 - 130,000 = $70,000. The answer is 70000.

Example 3:
Q: James writes a 3-page letter to 2 different friends twice a week. How many pages does he write a year?
A: He writes to 2 friends, so 2 letters each time. Each letter is 3 pages, so 2 * 3 = 6 pages per session. He does this twice a week: 6 * 2 = 12 pages per week. In a year (52 weeks): 12 * 52 = 624 pages. The answer is 624.

Now solve this problem the same way:
Q: Janet's ducks lay 16 eggs per day. She eats three for breakfast every morning and bakes muffins for her friends every day with four. She sells every remaining egg at the farmers' market for $2. How much does she make every day at the farmers' market?
A:"""

r_few = await lrn_llm.call(
    [{"role": "user", "content": few_shot_cot_prompt}],
    system="You are a business analyst solving word problems step-by-step.",
    max_tokens=400
)
few_shot_answer = lrn_llm.text(r_few)
print("=== FEW-SHOT + COT RESPONSE ===")
print(few_shot_answer)

# %% [markdown]
# ## Step 4 — Side-by-Side Comparison
#
# Let's extract and compare the final answers and reasoning clarity.

# %%
import re

def extract_number(text):
    """Extract the final answer from response text."""
    match = re.search(r'[Tt]he answer is[:\s]*(\$?[\d,]+)', text)
    if match:
        return match.group(1).strip()
    return "[not found]"

zero_answer = extract_number(zero_shot_answer)
few_answer = extract_number(few_shot_answer)

print("\n" + "="*60)
print("COMPARISON: Zero-Shot vs Few-Shot + CoT")
print("="*60)
print(f"\nFinal Answers:")
print(f"  Zero-shot answer:        {zero_answer}")
print(f"  Few-shot + CoT answer:   {few_answer}")
print(f"\nReasoning Quality:")
print(f"  Zero-shot tokens:        ~{len(zero_shot_answer.split())} words")
print(f"  Few-shot + CoT tokens:   ~{len(few_shot_answer.split())} words")
print(f"\nObservation:")
if zero_answer == few_answer:
    print(f"  Both methods reached the same answer: {zero_answer}")
else:
    print(f"  ⚠️  Answers differ! Zero-shot: {zero_answer}, Few-shot: {few_answer}")
print(f"\n  Few-shot + CoT provides MORE explicit reasoning steps.")
print(f"  This clarity helps clients understand the logic chain.")

# %% [markdown]
# ## Step 5 — Why Few-Shot + CoT Wins for Consultant Work
#
# **Zero-shot** (direct question):
# - Fast (~1 second)
# - But reasoning is **compressed and hard to verify**
# - Client can't follow the logic
#
# **Few-shot + CoT** (examples + step-by-step):
# - Slightly slower (~2 seconds, because examples are longer)
# - **Explicit step-by-step reasoning**
# - Client sees every arithmetic step
# - Model pattern-matches on your examples → consistent format
#
# For LHIND consulting, few-shot + CoT is often worth the extra tokens because:
# 1. **Auditability**: You can show the client exactly how the LLM arrived at the answer
# 2. **Trust**: Step-by-step reasoning builds confidence in recommendations
# 3. **Flexibility**: If the client questions a step, you can ask the LLM to re-examine just that part
#
# This is the core of **prompt engineering as a business skill** — it's not about getting the fastest answer, it's about getting the **most defensible** answer.

# %% [markdown]
# ## Try It Yourself
#
# Below is a sandbox where you can test few-shot + CoT on your own client problem. Edit the problem statement and examples to match a real LHIND scenario (e.g., cost analysis, staffing calculations, project timeline estimation).

# %%
# TODO: Edit this client problem and examples to match your scenario
# Example: Replace with a real LHIND consulting brief

custom_problem = """EDIT THIS: Your custom client problem here.
Example template:
'A consulting firm has 5 teams. Each team has 3 senior consultants and 2 junior consultants.
Senior consultants bill at $200/hour, junior at $100/hour.
If each team works 40 hours per week, how much revenue is generated per week?'

For now, we'll use a simple test."""

custom_examples = """Example 1:
Q: A company has 10 employees. Each earns $50,000 per year. What is the total annual payroll?
A: There are 10 employees. Each earns $50,000. Total payroll: 10 * $50,000 = $500,000 per year. The answer is 500000.

Example 2:
Q: A project takes 100 hours and costs $5,000 in materials. If labor costs $100 per hour, what is the total project cost?
A: Labor hours: 100. Labor cost per hour: $100. Labor cost: 100 * $100 = $10,000. Materials: $5,000. Total: $10,000 + $5,000 = $15,000. The answer is 15000."""

print("✨ Prompt Template Ready")
print("\nTo use:")
print("1. Replace 'custom_problem' above with your client brief")
print("2. Replace 'custom_examples' with your domain's worked examples")
print("3. Run the cell below to see few-shot + CoT reasoning on YOUR problem")
print("\nThis is how LHIND consultants use LLMs to clarify ambiguous briefs.")
