# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/14-agent-engineering/39-reviewer-agent
# Used in courses: AI-12, AI-35
# Framework: none
# Requires API key: False

"""lrn_llm.call"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "https://gateway.lhind.ai/v1"
lrn_llm.DEFAULT_MODEL = "azure/gpt-4o"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    if lrn_llm.API_KEY:
        headers["Authorization"] = "Bearer " + lrn_llm.API_KEY
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key
#
# Optional: Set your API key below if needed. The gateway works without a key on the LHIND network.

# %%
lrn_llm.API_KEY = ""  # optional; leave empty on LHIND network
print("Endpoint:", lrn_llm.API_BASE)
print("Model:", lrn_llm.DEFAULT_MODEL)
print("Using key:", "yes" if lrn_llm.API_KEY else "no")

# %% [markdown]
# ## Step 1 — Reachability
#
# Ping the LLM endpoint to verify connectivity.

# %%
r = await lrn_llm.ping()
print("✅ LLM erreichbar" if r["ok"] else "❌ LLM nicht erreichbar")
print("Model:", r.get("model", "unknown"))

# %% [markdown]
# ## Step 2 — The Reviewer Agent Task
#
# A reviewer agent separates the role of builder from the role of grader. The builder edits code; the reviewer reads the change and scores it against a 5-dimension rubric:
#
# 1. **Problem fit**: Did the change solve the stated task, not a nearby one?
# 2. **Scope discipline**: Were edits confined to the contract?
# 3. **Assumptions**: Are hidden assumptions documented?
# 4. **Verification quality**: Does acceptance prove the goal?
# 5. **Handoff readiness**: Can the next session pick up cleanly?
#
# Each dimension scores 0–2; total out of 10. A run ≥7 is a pass, 5–6 is soft fail, <5 is hard fail.

# %% [markdown]
# ## Step 3 — Sample Builder Artifacts
#
# We'll review two cases: a clean change and one that solved the wrong problem.

# %%
# Case 1: Clean change — fixed the right problem, documented assumptions, good state
case_clean = {
    "task_id": "T-001",
    "goal": "add input validation to signup",
    "diff_summary": {
        "touched": ["app/signup.py", "tests/test_signup.py"],
        "added_lines": 45,
        "removed_lines": 8,
    },
    "state": {
        "active_task_id": None,
        "assumptions": ["users sign up with email + password only", "email length ≤ 254 chars"],
        "next_action": "pick next task from board",
    },
    "feedback": [{"command": "pytest", "exit_code": 0}],
    "verdict": {"passed": True, "findings": []},
}

# Case 2: Wrong problem — tests pass, but only docs changed, not code
case_wrong = {
    "task_id": "T-002",
    "goal": "add input validation to signup",
    "diff_summary": {
        "touched": ["docs/api.md"],
        "added_lines": 12,
        "removed_lines": 0,
    },
    "state": {
        "active_task_id": "T-002",  # task not closed
        "assumptions": [],  # no assumptions recorded
        "next_action": "",  # no next action
    },
    "feedback": [{"command": "pytest", "exit_code": 0}],
    "verdict": {"passed": True, "findings": [{"code": "scope.off_scope", "severity": "warn"}]},
}

print("Case 1 (clean): files =", case_clean["diff_summary"]["touched"])
print("Case 2 (wrong): files =", case_wrong["diff_summary"]["touched"])

# %% [markdown]
# ## Step 4 — Score Problem Fit
#
# The reviewer asks: *Did this change solve the stated task?*
#
# We'll ask the LLM to score (0–2) whether the files touched align with the goal.

# %%
async def score_problem_fit(case):
    prompt = f"""You are a code reviewer assessing whether a change solves its stated task.

Task goal: {case['goal']}
Files touched: {', '.join(case['diff_summary']['touched'])}

Does the set of files touched align with the goal?
If yes (code/test files changed for signup), score 2.
If partial (only one touched), score 1.
If no (unrelated files), score 0.

Reply with ONLY a JSON object: {{"score": <int>, "note": "<reason>"}}"""

    r = await lrn_llm.call(
        [{"role": "user", "content": prompt}],
        max_tokens=100
    )
    text = lrn_llm.text(r)
    try:
        result = json.loads(text)
        return result["score"], result.get("note", "")
    except:
        return 0, f"Could not parse response: {text[:50]}"

# Score both cases
print("Case 1 (clean):")
score1, note1 = await score_problem_fit(case_clean)
print(f"  Problem fit: {score1}/2 — {note1}")

print("\nCase 2 (wrong):")
score2, note2 = await score_problem_fit(case_wrong)
print(f"  Problem fit: {score2}/2 — {note2}")

# %% [markdown]
# ## Step 5 — Score Scope Discipline
#
# The reviewer asks: *Were edits confined to the contract, or did scope creep in?*

# %%
async def score_scope_discipline(case):
    findings_text = "; ".join([f"{f.get('code')}: {f.get('severity')}" for f in case["verdict"].get("findings", [])])
    prompt = f"""You are reviewing whether a change respected its scope boundaries.

Task: {case['goal']}
Verification findings: {findings_text if findings_text else "none"}
Files touched: {', '.join(case['diff_summary']['touched'])}

Did the builder stay within scope?
If no findings and files are on-scope: score 2.
If there are off-scope warnings but no forbidden writes: score 1.
If there are forbidden writes: score 0.

Reply with ONLY a JSON object: {{"score": <int>, "note": "<reason>"}}"""

    r = await lrn_llm.call(
        [{"role": "user", "content": prompt}],
        max_tokens=100
    )
    text = lrn_llm.text(r)
    try:
        result = json.loads(text)
        return result["score"], result.get("note", "")
    except:
        return 0, f"Could not parse response: {text[:50]}"

print("Case 1 (clean):")
score1, note1 = await score_scope_discipline(case_clean)
print(f"  Scope discipline: {score1}/2 — {note1}")

print("\nCase 2 (wrong):")
score2, note2 = await score_scope_discipline(case_wrong)
print(f"  Scope discipline: {score2}/2 — {note2}")

# %% [markdown]
# ## Step 6 — Score Assumptions
#
# The reviewer asks: *Are hidden assumptions written down?*
#
# Reviewer logic: if no assumptions recorded, either work was trivial (unlikely) or undocumented (bad). We want to see the assumptions that bound the solution.

# %%
async def score_assumptions(case):
    assumptions = case["state"].get("assumptions") or []
    assumptions_text = "; ".join(assumptions) if assumptions else "none"
    
    prompt = f"""You are reviewing whether a builder documented their assumptions.

Task: {case['goal']}
Assumptions recorded: {assumptions_text}

Are assumptions properly documented?
If ≥2 assumptions are recorded and specific: score 2.
If some assumptions recorded but sparse: score 1.
If no assumptions recorded: score 1 (either trivial or undocumented).

Reply with ONLY a JSON object: {{"score": <int>, "note": "<reason>"}}"""

    r = await lrn_llm.call(
        [{"role": "user", "content": prompt}],
        max_tokens=100
    )
    text = lrn_llm.text(r)
    try:
        result = json.loads(text)
        return result["score"], result.get("note", "")
    except:
        return 0, f"Could not parse response: {text[:50]}"

print("Case 1 (clean):")
score1, note1 = await score_assumptions(case_clean)
print(f"  Assumptions: {score1}/2 — {note1}")

print("\nCase 2 (wrong):")
score2, note2 = await score_assumptions(case_wrong)
print(f"  Assumptions: {score2}/2 — {note2}")

# %% [markdown]
# ## Step 7 — Score Verification Quality
#
# The reviewer asks: *Does the acceptance command actually prove the goal?*
#
# We check: did the feedback exit with code 0 (pass)? Did the verifier find issues?

# %%
async def score_verification_quality(case):
    exits = [rec.get("exit_code") for rec in case["feedback"]]
    exit_text = ", ".join(str(e) for e in exits)
    
    prompt = f"""You are reviewing whether acceptance tests were sufficient.

Task: {case['goal']}
Feedback exit codes: {exit_text}
Verification passed: {case['verdict'].get('passed')}

Were the acceptance tests adequate?
If all exit zero and verification passed: score 2.
If mixed exit codes or verification has findings: score 1.
If missing exit codes: score 0.

Reply with ONLY a JSON object: {{"score": <int>, "note": "<reason>"}}"""

    r = await lrn_llm.call(
        [{"role": "user", "content": prompt}],
        max_tokens=100
    )
    text = lrn_llm.text(r)
    try:
        result = json.loads(text)
        return result["score"], result.get("note", "")
    except:
        return 0, f"Could not parse response: {text[:50]}"

print("Case 1 (clean):")
score1, note1 = await score_verification_quality(case_clean)
print(f"  Verification quality: {score1}/2 — {note1}")

print("\nCase 2 (wrong):")
score2, note2 = await score_verification_quality(case_wrong)
print(f"  Verification quality: {score2}/2 — {note2}")

# %% [markdown]
# ## Step 8 — Score Handoff Readiness
#
# The reviewer asks: *Could the next session pick up cleanly?*
#
# Has the builder closed the task in state and set a next action?

# %%
async def score_handoff_readiness(case):
    active = case["state"].get("active_task_id")
    next_action = case["state"].get("next_action")
    
    prompt = f"""You are reviewing whether a builder left a clean handoff.

Task ID: {case['task_id']}
Active task after work: {active if active else "none"}
Next action set: {next_action if next_action else "none"}

Is the handoff ready for the next session?
If task closed and next_action is set: score 2.
If task not closed but next_action is set: score 1.
If neither is set: score 0.

Reply with ONLY a JSON object: {{"score": <int>, "note": "<reason>"}}"""

    r = await lrn_llm.call(
        [{"role": "user", "content": prompt}],
        max_tokens=100
    )
    text = lrn_llm.text(r)
    try:
        result = json.loads(text)
        return result["score"], result.get("note", "")
    except:
        return 0, f"Could not parse response: {text[:50]}"

print("Case 1 (clean):")
score1, note1 = await score_handoff_readiness(case_clean)
print(f"  Handoff readiness: {score1}/2 — {note1}")

print("\nCase 2 (wrong):")
score2, note2 = await score_handoff_readiness(case_wrong)
print(f"  Handoff readiness: {score2}/2 — {note2}")

# %% [markdown]
# ## Step 9 — Assemble the Full Review Report
#
# Now we'll combine all five dimension scores and compute the final verdict.

# %%
async def review_case(case):
    """Run all five dimension scorers and produce a review report."""
    dimensions = []
    total = 0
    
    # Score each dimension
    scores = [
        await score_problem_fit(case),
        await score_scope_discipline(case),
        await score_assumptions(case),
        await score_verification_quality(case),
        await score_handoff_readiness(case),
    ]
    names = ["problem_fit", "scope_discipline", "assumptions", "verification_quality", "handoff_readiness"]
    
    for name, (score, note) in zip(names, scores):
        dimensions.append({"name": name, "score": score, "note": note})
        total += score
    
    # Determine verdict
    has_zero = any(d["score"] == 0 for d in dimensions)
    if has_zero or total < 5:
        verdict = "hard_fail"
    elif total >= 7:
        verdict = "pass"
    else:
        verdict = "soft_fail"
    
    return {
        "task_id": case["task_id"],
        "total": total,
        "verdict": verdict,
        "dimensions": dimensions,
    }

# Review both cases
print("Reviewing Case 1 (clean)...")
report1 = await review_case(case_clean)
print(f"✅ Task {report1['task_id']}: {report1['total']}/10 — {report1['verdict']}")
for d in report1["dimensions"]:
    print(f"   {d['name']:25} {d['score']}/2 — {d['note'][:40]}..." if len(d['note']) > 40 else f"   {d['name']:25} {d['score']}/2 — {d['note']}")

print("\nReviewing Case 2 (wrong problem)...")
report2 = await review_case(case_wrong)
print(f"{'✅' if report2['verdict'] == 'pass' else '⚠️ ' if report2['verdict'] == 'soft_fail' else '❌'} Task {report2['task_id']}: {report2['total']}/10 — {report2['verdict']}")
for d in report2["dimensions"]:
    print(f"   {d['name']:25} {d['score']}/2 — {d['note'][:40]}..." if len(d['note']) > 40 else f"   {d['name']:25} {d['score']}/2 — {d['note']}")

# %% [markdown]
# ## Step 10 — Try It Yourself
#
# Edit the task below and run the reviewer on a custom change. What happens when you:
# - Change only docs (like Case 2)?
# - Record no assumptions?
# - Leave an active task unclosed?

# %%
# TODO: Try your own review case!
# Modify this case and run it through review_case(your_case)

your_case = {
    "task_id": "T-003",
    "goal": "refactor database connection pooling",  # TODO: change to a different goal
    "diff_summary": {
        "touched": ["db/pool.py", "tests/test_pool.py"],  # TODO: add or remove files
        "added_lines": 30,
        "removed_lines": 15,
    },
    "state": {
        "active_task_id": None,  # TODO: try setting this to "T-003" to break handoff
        "assumptions": ["pool size must be ≥4"],  # TODO: remove to test assumption scoring
        "next_action": "measure latency impact in staging",  # TODO: empty this to test handoff
    },
    "feedback": [{"command": "pytest", "exit_code": 0}],
    "verdict": {"passed": True, "findings": []},
}

print("Running custom review...")
report = await review_case(your_case)
print(f"Task {report['task_id']}: {report['total']}/10 — {report['verdict']}")
for d in report["dimensions"]:
    print(f"   {d['name']:25} {d['score']}/2")
