# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/14-agent-engineering/01-the-agent-loop
# Used in courses: AI-02
# Framework: none
# Requires API key: False

"""agent-loop"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "https://gateway.lhind.ai/v1"
lrn_llm.DEFAULT_MODEL = "azure/gpt-4o"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    _key = lrn_llm.API_KEY
    if not _key:
        try:
            import js as _js
            _key = getattr(_js, "__LRN_LLM_KEY__", "") or ""
        except Exception:
            _key = ""
    if _key:
        headers["Authorization"] = "Bearer " + _key
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key
#
# The notebook uses the LHIND gateway. API key is optional on the LHIND network; set it only if needed.

# %%
lrn_llm.API_KEY = ""  # leave empty on LHIND network, or set your key
print(f"Endpoint: {lrn_llm.API_BASE}")
print(f"Model: {lrn_llm.DEFAULT_MODEL}")
print(f"Key configured: {bool(lrn_llm.API_KEY)}")

# %% [markdown]
# ## Step 1 — Reachability
#
# Ping the LLM endpoint to verify the connection is live.

# %%
r = await lrn_llm.ping()
print("✅ LLM reachable" if r["ok"] else "❌ LLM unreachable")
print(f"Model: {r['model']}")

# %% [markdown]
# ## Step 2 — The Agent Loop in Action
#
# The agent loop is **Observe → Think → Act → Observe → repeat until stop**.
#
# We'll build a **tax calculator agent** that:
# 1. Takes a user question like "What is $100 plus 15% tax?"
# 2. Calls the LLM to reason about the steps needed
# 3. The LLM chooses tools (calculator, storage) to solve the problem
# 4. The agent runs those tools and feeds results back
# 5. The loop repeats until the LLM says it's finished
#
# This mirrors the lesson's concrete example. Let's define the tools first.

# %%
import re

class ToolRegistry:
    """A registry of available tools the LLM can call."""
    def __init__(self):
        self._tools = {}

    def register(self, name, fn):
        self._tools[name] = fn

    def names(self):
        return sorted(self._tools)

    def dispatch(self, tool_name, args):
        """Execute a tool and return the result as a string."""
        fn = self._tools.get(tool_name)
        if fn is None:
            return f"ERROR: unknown tool {tool_name!r}"
        try:
            return fn(**args)
        except TypeError as e:
            return f"ERROR: bad args for {tool_name}: {e}"
        except Exception as e:
            return f"ERROR: {type(e).__name__}: {e}"

# Tool 1: calculator
def calculator(expr: str) -> str:
    """Safely evaluate a math expression."""
    allowed = set("0123456789+-*/(). ")
    if not set(expr).issubset(allowed):
        return "ERROR: illegal character in expr"
    try:
        result = eval(expr, {"__builtins__": {}}, {})
        return str(result)
    except Exception as e:
        return f"ERROR: {type(e).__name__}: {e}"

# Tool 2: key-value store
class KVStore:
    def __init__(self):
        self._store = {}

    def get(self, key: str) -> str:
        val = self._store.get(key)
        return val if val is not None else f"missing:{key}"

    def set(self, key: str, value: str) -> str:
        self._store[key] = value
        return f"stored: {key} = {value}"

# Build the registry
tools = ToolRegistry()
tools.register("calculator", calculator)
kv = KVStore()
tools.register("kv_get", kv.get)
tools.register("kv_set", kv.set)

print(f"✅ Tools registered: {tools.names()}")

# %% [markdown]
# ## Step 3 — Parse LLM Tool Calls
#
# The LLM will emit text like `<tool_call name="calculator" args='{"expr": "100 * 0.15"}'>`. We parse this into (name, args) pairs.

# %%
def parse_tool_calls(text):
    """Extract tool calls from the LLM's response."""
    calls = []
    # Pattern: <tool_call name="TOOL_NAME" args='JSON_DICT'>
    pattern = r'<tool_call\s+name="([^"]+)"\s+args=\'([^\']+)\'\s*>'
    for match in re.finditer(pattern, text):
        tool_name = match.group(1)
        try:
            args_dict = json.loads(match.group(2))
        except json.JSONDecodeError:
            args_dict = {}
        calls.append((tool_name, args_dict))
    return calls

# Test the parser
test_response = '''I need to calculate 15% tax on $100.
<tool_call name="calculator" args='{"expr": "100 * 0.15"}'>
<tool_call name="kv_set" args='{"key": "tax", "value": "15"}'>'''

calls = parse_tool_calls(test_response)
print(f"Parsed {len(calls)} tool calls:")
for name, args in calls:
    print(f"  • {name}({args})")

# %% [markdown]
# ## Step 4 — Run One Turn of the Agent Loop
#
# One turn = LLM responds + tools execute + observations collected.

# %%
async def agent_turn(messages, turn_num):
    """Run one step of the agent loop."""
    # Build the system prompt that tells the LLM about available tools
    system = f"""You are a helpful agent. You have access to these tools:

1. calculator: safely evaluate a math expression. Usage: <tool_call name="calculator" args='{{"expr": "..."}}'>. Return the numeric result.
2. kv_get: retrieve a value from storage. Usage: <tool_call name="kv_get" args='{{"key": "..."}}'>. Return the stored value or a missing indicator.
3. kv_set: store a value. Usage: <tool_call name="kv_set" args='{{"key": "...", "value": "..."}}'>. Return confirmation.

When answering:
- Always emit tool_call tags to invoke tools.
- After you receive tool results, explain what you learned.
- When you have enough information to answer the user's question, say DONE and give your final answer.

Current turn: {turn_num}
"""

    # Call the LLM
    response = await lrn_llm.call(messages, system=system, max_tokens=300)
    assistant_text = lrn_llm.text(response)

    # Parse tool calls
    tool_calls = parse_tool_calls(assistant_text)

    # Dispatch tools
    observations = []
    for tool_name, args in tool_calls:
        result = tools.dispatch(tool_name, args)
        observations.append(f"{tool_name}({args}) → {result}")

    return {
        "assistant_text": assistant_text,
        "tool_calls": tool_calls,
        "observations": observations
    }

print("✅ agent_turn() ready")

# %% [markdown]
# ## Step 5 — The Full Agent Loop
#
# We loop until the LLM says DONE or we hit the max turn budget.

# %%
async def run_agent(user_message, max_turns=5):
    """Run the full agent loop."""
    messages = [{"role": "user", "content": user_message}]
    print(f"🎯 User: {user_message}\n")

    for turn in range(max_turns):
        print(f"--- Turn {turn + 1} ---")

        # Run the LLM
        result = await agent_turn(messages, turn + 1)
        assistant_text = result["assistant_text"]
        observations = result["observations"]

        # Show what the LLM said
        print(f"Assistant: {assistant_text[:200]}..." if len(assistant_text) > 200 else f"Assistant: {assistant_text}")

        # Show tool calls and results
        if observations:
            for obs in observations:
                print(f"  Tool: {obs}")
        else:
            print("  (no tool calls)")

        # Append assistant response and observations to message history
        messages.append({"role": "assistant", "content": assistant_text})
        if observations:
            obs_text = "\n".join(observations)
            messages.append({"role": "user", "content": f"Tool results:\n{obs_text}"})

        # Check for stop condition
        if "DONE" in assistant_text.upper():
            print(f"\n✅ Agent finished. Final answer:")
            print(assistant_text.split("DONE")[1] if "DONE" in assistant_text else assistant_text)
            return assistant_text

        print()

    print("⏹️ Budget exhausted after", max_turns, "turns")
    return "Budget exhausted"

print("✅ run_agent() ready")

# %% [markdown]
# ## Step 6 — Execute the Agent
#
# Let's run the agent on the same problem from the lesson: **computing total price with 15% tax**.

# %%
result = await run_agent(
    "What is $120 plus 15% tax? Store the base price, compute tax, then give me the total.",
    max_turns=4
)

print(f"\n🎓 This is the ReAct loop in action:")
print(f"   1. LLM observes the user question")
print(f"   2. LLM thinks about what tools to call")
print(f"   3. We dispatch those tools (Act)")
print(f"   4. Tool results come back (Observe)")
print(f"   5. Loop until the LLM says DONE")

# %% [markdown]
# ## Try it yourself
#
# Modify the user message below and re-run. The LLM will figure out what tools to call. Try:
# - "What is $200 with 20% tax?"
# - "Store the value 'pi' then retrieve it"
# - "Calculate 50 * 3, then add 10%"

# %%
# TODO: Edit the message below and run this cell to try your own agent prompt
my_message = "Calculate $75 plus 10% tax and store it as 'final_total'"

result = await run_agent(my_message, max_turns=4)
print(f"\nFinal result: {result}")
