# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/11-llm-engineering/01-prompt-engineering
# Used in courses: AI-15
# Framework: stdlib
# Requires API key: False

"""ai-15-user-research-synthesis"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "/api/llm"  # same-origin proxy; server injects the gateway key
lrn_llm.DEFAULT_MODEL = "azure/gpt-5.4-mini"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    _key = lrn_llm.API_KEY
    if _key:
        headers["Authorization"] = "Bearer " + _key
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key
#
# Optional: If you have an API key, set it below. The gateway works without a key on the LHIND network.

# %%
lrn_llm.API_KEY = ""  # set your key here if needed
print(f"Endpoint: {lrn_llm.API_BASE}")
print(f"Model: {lrn_llm.DEFAULT_MODEL}")
print(f"API key set: {bool(lrn_llm.API_KEY)}")

# %% [markdown]
# ## Step 1 — Reachability
#
# Verify the LLM endpoint is reachable.

# %%
r = await lrn_llm.ping()
print(f"✅ LLM erreichbar: {r['ok']}")
print(f"Model: {r['model']}")

# %% [markdown]
# ## Step 2 — The Problem: Vague vs Engineered Prompts
#
# Imagine you're synthesizing insights from customer interviews for a fintech app. Without clear prompts, the LLM produces generic, scattered insights. With a well-engineered prompt, you get focused, actionable synthesis.
#
# Let's compare two approaches using the same interview corpus.

# %%
# Customer interview snippets (anonymized)
INTERVIEW_CORPUS = """
Interview 1: "The mobile app is slow on 4G networks. I often give up waiting for payments to process. We'd switch providers if there was a faster alternative."

Interview 2: "I love the dashboard, but I have no idea where my fees come from. The billing page shows a total but no breakdown. I call support every month asking questions I should be able to answer myself."

Interview 3: "Onboarding took 2 days because I didn't understand which documents were required. The instructions were vague. But once I was set up, using the app was straightforward."

Interview 4: "My accountant asked how much I'm paying in transaction fees this year. I couldn't answer because there's no export function. I had to take screenshots and compile a spreadsheet manually."

Interview 5: "The customer support team is responsive, but they keep asking me to describe my problem in detail, even for simple issues. A self-service FAQ for common questions would save everyone time."
"""

print("Customer interview corpus ready.")
print(f"Length: {len(INTERVIEW_CORPUS)} characters")

# %% [markdown]
# ## Step 3 — Vague Prompt (Baseline)
#
# This is how most people write prompts: generic request, no structure, no examples.

# %%
vague_prompt = "Summarize what customers are saying."

messages = [{"role": "user", "content": f"{INTERVIEW_CORPUS}\n\n{vague_prompt}"}]
response = await lrn_llm.call(messages, max_tokens=300)
vague_output = lrn_llm.text(response)

print("=== VAGUE PROMPT ===")
print(f"Prompt: {vague_prompt}")
print(f"\nOutput:\n{vague_output}")

# %% [markdown]
# ## Step 4 — Engineered Prompt (Few-Shot + Role + Format)
#
# Now with specific role, format, and examples showing the expected output structure.

# %%
engineered_prompt = """You are a UX researcher at a fintech company. Synthesize customer feedback into actionable insights.

Analyze the interviews below and identify:
1. Key pain points (specific problems customers face)
2. Impact (how often/how many customers affected)
3. Recommended fix (specific action the product team should take)

Output format:
Pain Point: [specific problem]
Evidence: [quote or number from interviews]
Impact: [frequency: frequent/occasional/rare]
Recommendation: [specific action in one sentence]

Example:
Pain Point: Slow payment processing
Evidence: "I often give up waiting for payments to process"
Impact: frequent
Recommendation: Optimize API endpoint latency for 4G networks below 2 seconds.

Now analyze these interviews:
{}

Provide 3-4 distinct pain points. Be specific, not generic.""".format(INTERVIEW_CORPUS)

messages = [{"role": "user", "content": engineered_prompt}]
response = await lrn_llm.call(messages, max_tokens=600)
engineered_output = lrn_llm.text(response)

print("=== ENGINEERED PROMPT ===")
print(f"Prompt structure: Role + Format + Example + Task")
print(f"\nOutput:\n{engineered_output}")

# %% [markdown]
# ## Step 5 — Comparison
#
# Notice the difference:
# - **Vague output**: Generic summary, lacks structure, mixes pain points with vague statements
# - **Engineered output**: Specific pain points, clear evidence, actionable recommendations

# %%
print("\n" + "="*70)
print("COMPARISON METRICS")
print("="*70)

vague_lines = len(vague_output.split('\n'))
engineered_lines = len(engineered_output.split('\n'))

print(f"\nVague output:")
print(f"  - Lines: {vague_lines}")
print(f"  - Word count: {len(vague_output.split())}")
print(f"  - Structure: paragraphs (unstructured)")
print(f"  - Specific recommendations: {vague_output.lower().count('recommend')}")

print(f"\nEngineered output:")
print(f"  - Lines: {engineered_lines}")
print(f"  - Word count: {len(engineered_output.split())}")
print(f"  - Structure: labeled fields (Pain Point, Evidence, Impact, Recommendation)")
print(f"  - Specific recommendations: {engineered_output.lower().count('recommend')}")

print(f"\n✅ The engineered prompt produced more structured, actionable output.")
print(f"   Same model, same interviews, better instructions → better results.")

# %% [markdown]
# ## Step 6 — Breaking Down the Engineered Prompt
#
# Let's identify the prompt engineering patterns used in the engineered version.

# %%
patterns_used = {
    "Role Prompting": "You are a UX researcher at a fintech company",
    "Output Format Control": "Output format: [specific fields with structure]",
    "Few-Shot Example": "Example: [shows one complete pain point analysis]",
    "Constraint Specification": "Be specific, not generic / Provide 3-4 distinct pain points",
    "Task Decomposition": "Identify: 1) Pain points 2) Impact 3) Recommendation",
}

print("Patterns in the Engineered Prompt:")
print()
for pattern, example in patterns_used.items():
    print(f"• {pattern}")
    print(f"  → {example}")
    print()

print("Why each pattern matters:")
print("  - Role: Activates 'UX researcher' quality in the model's training data")
print("  - Format: Eliminates ambiguity about how output should be organized")
print("  - Example: Shows the model exactly what 'done' looks like")
print("  - Constraints: Removes vague outputs by stating what NOT to do")
print("  - Decomposition: Breaks synthesis into clear sub-tasks")

# %% [markdown]
# ## Step 7 — Try It Yourself
#
# Write your own vague and engineered prompts for a different synthesis task. You can use the interview corpus above or add new ones.

# %%
# TODO: Modify the prompts below and test them

# Add a new customer interview or use the existing corpus
new_interview = INTERVIEW_CORPUS  # or add your own: "Interview 6: '...'"

# Your vague prompt
my_vague = "What problems do customers mention?"

# Your engineered prompt (add role, format, example, constraints)
my_engineered = f"""You are a product manager.

List the top customer complaints from these interviews:
{new_interview}

Format your answer as:
- Complaint: [problem]
- Fix: [solution]

Give me 2-3 items."""

print("Testing your vague prompt:")
messages = [{"role": "user", "content": f"{new_interview}\n\n{my_vague}"}]
response = await lrn_llm.call(messages, max_tokens=300)
print(lrn_llm.text(response))

print("\n" + "="*70)
print("\nTesting your engineered prompt:")
messages = [{"role": "user", "content": my_engineered}]
response = await lrn_llm.call(messages, max_tokens=300)
print(lrn_llm.text(response))

print("\n✅ Compare the two outputs. Which is more useful for a PM?")
