# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/14-agent-engineering/03-reflexion-verbal-rl
# Used in courses: AI-02
# Framework: none
# Requires API key: False

"""reflexion_verbal_rl"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "/api/llm"  # same-origin proxy; server injects the gateway key
lrn_llm.DEFAULT_MODEL = "azure/gpt-5.4-mini"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    _key = lrn_llm.API_KEY
    if _key:
        headers["Authorization"] = "Bearer " + _key
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key
#
# The notebook uses the LHIND AI gateway (no key required on the internal network). If you need to override, set `lrn_llm.API_KEY` below.

# %%
lrn_llm.API_KEY = ""  # Leave empty for LHIND network; set your Bearer token if needed
print(f"Endpoint: {lrn_llm.API_BASE}")
print(f"Model: {lrn_llm.DEFAULT_MODEL}")
print(f"Key configured: {bool(lrn_llm.API_KEY)}")

# %% [markdown]
# ## Step 1 — Reachability
#
# Ping the LLM endpoint to confirm connectivity.

# %%
r = await lrn_llm.ping()
print(f"✅ LLM erreichbar: {r['ok']} (model: {r['model']})")

# %% [markdown]
# ## Reflexion: Verbal Reinforcement Learning
#
# Reflexion is the pattern where an agent:
# 1. **Acts** — generates a candidate solution (using the LLM)
# 2. **Evaluates** — checks if it's correct
# 3. **Reflects** — if it fails, the LLM writes why it failed ("I picked small numbers when I needed large ones")
# 4. **Remembers** — stores the reflection in episodic memory
# 5. **Repeats** — the next trial sees the reflection in its prompt and adapts
#
# No weight updates. No gradients. Just natural language fed back into the loop.
#
# ### The Toy Task
# Pick three integers from 1–9 that sum to a **target** (we'll use 20). The Actor (LLM) must learn from reflections to converge.

# %% [markdown]
# ## Step 2 — Define the Episodic Memory
#
# Reflections are stored in a bounded buffer. Older reflections are evicted when the buffer fills.

# %%
from dataclasses import dataclass, field

@dataclass
class Reflection:
    trial: int
    text: str

@dataclass
class EpisodicMemory:
    items: list[Reflection] = field(default_factory=list)
    max_len: int = 6
    
    def add(self, r: Reflection) -> None:
        self.items.append(r)
        if len(self.items) > self.max_len:
            self.items.pop(0)
    
    def as_prompt(self) -> str:
        if not self.items:
            return "(no prior reflections)"
        lines = [f"- trial {r.trial}: {r.text}" for r in self.items]
        return "\n".join(lines)

memory = EpisodicMemory()
print("✅ Episodic memory initialized")

# %% [markdown]
# ## Step 3 — Define the Binary Evaluator
#
# The evaluator checks if the sum equals the target. It returns (success: bool, delta: int) where delta is how far off we are.

# %%
TARGET = 20

def binary_evaluator(attempt: list[int], target: int) -> tuple[bool, int]:
    """Check if list sums to target. Return (success, delta)."""
    total = sum(attempt)
    return total == target, total - target

# Test
test_attempt = [6, 7, 7]  # sums to 20
success, delta = binary_evaluator(test_attempt, TARGET)
print(f"Test: {test_attempt} → sum={sum(test_attempt)}, success={success}, delta={delta}")

# %% [markdown]
# ## Step 4 — Actor: Generate a Candidate
#
# The Actor (LLM) generates three integers. On the first trial it gets a generic prompt; on later trials, it sees reflections from prior failures.

# %%
async def actor(memory: EpisodicMemory, trial: int, target: int = TARGET) -> list[int]:
    """LLM generates three integers in [1..9] that should sum to target."""
    reflection_context = memory.as_prompt()
    prompt = f"""You are solving a puzzle: pick three integers from 1 to 9 (inclusive) that sum to {target}.
Return ONLY a valid JSON array of exactly 3 integers, e.g. [3, 5, 7]

Prior trial reflections (if any):
{reflection_context}

Trial {trial}: generate your three integers."""
    
    r = await lrn_llm.call(
        [{"role": "user", "content": prompt}],
        max_tokens=50
    )
    text = lrn_llm.text(r).strip()
    # Parse JSON array from response
    try:
        attempt = json.loads(text)
        # Clamp to [1..9]
        attempt = [max(1, min(9, x)) for x in attempt[:3]]
        if len(attempt) < 3:
            attempt.extend([5] * (3 - len(attempt)))
        return attempt
    except:
        return [5, 5, 5]  # fallback

# Test actor on trial 1 with empty memory
attempt = await actor(memory, trial=1)
print(f"Trial 1 attempt: {attempt}, sum={sum(attempt)}")

# %% [markdown]
# ## Step 5 — Self-Reflector: Write a Diagnosis
#
# If the trial fails, the Self-Reflector (LLM) writes a one-line reflection explaining why.

# %%
async def self_reflector(attempt: list[int], delta: int, trial: int, target: int = TARGET) -> str:
    """LLM writes a one-line reflection on why the attempt failed."""
    prompt = f"""You just tried {attempt}, which sums to {sum(attempt)}.
Target is {target}. Delta (actual - target) = {delta}.

Write ONE SHORT LINE explaining what went wrong and how to fix it next time.
Be specific: e.g. 'sum was too low by 3; need larger integers' or 'tried [8,9,9] which overshoots by 6; need smaller'.
Do NOT say 'I should try harder' or generic advice.
Reply with ONLY the reflection, no markdown."""
    
    r = await lrn_llm.call(
        [{"role": "user", "content": prompt}],
        max_tokens=40
    )
    return lrn_llm.text(r).strip()

# Test reflector
test_delta = 5  # sum was 15, target is 20
reflection = await self_reflector([5, 5, 5], test_delta, trial=1)
print(f"Reflection: {reflection}")

# %% [markdown]
# ## Step 6 — Run the Reflexion Loop
#
# Run 4 trials. Each failure stores a reflection in episodic memory. The next actor call sees those reflections and adapts.

# %%
@dataclass
class TrialResult:
    trial: int
    attempt: list[int]
    success: bool
    delta: int
    reflection: str

async def run_reflexion(max_trials: int, target: int = TARGET) -> list[TrialResult]:
    """Run reflexion loop: actor → evaluator → reflector → memory → repeat."""
    global memory
    memory = EpisodicMemory()  # Fresh memory for this run
    trials: list[TrialResult] = []

    for t in range(1, max_trials + 1):
        print(f"\n--- Trial {t} ---")
        attempt = await actor(memory, trial=t, target=target)
        success, delta = binary_evaluator(attempt, target)
        
        print(f"Attempt: {attempt}, sum={sum(attempt)}, delta={delta:+d}", end="")
        
        if success:
            reflection_text = "success!"
            print(" ✅")
            trials.append(TrialResult(t, attempt, success, delta, reflection_text))
            break
        else:
            print(" ❌")
            reflection_text = await self_reflector(attempt, delta, t, target=target)
            print(f"Reflection: {reflection_text}")
            memory.add(Reflection(trial=t, text=reflection_text))
            trials.append(TrialResult(t, attempt, success, delta, reflection_text))
    
    return trials

trials = await run_reflexion(max_trials=4)
print(f"\n=== Final: {'✅ Success' if trials[-1].success else '❌ Failed'} in {len(trials)} trials ===")

# %% [markdown]
# ## Step 7 — Analyze the Results
#
# Reflexion succeeds when the LLM uses reflections to adapt. Compare against a baseline (no memory).

# %%
def summarize(trials: list[TrialResult], name: str) -> None:
    print(f"\n{name}")
    print("-" * 70)
    for r in trials:
        mark = "✅" if r.success else "❌"
        print(f"  trial {r.trial}: {r.attempt} → sum={sum(r.attempt):2d}, "
              f"delta={r.delta:+3d} {mark}")
        if not r.success:
            print(f"           reflection: {r.reflection}")
    last = trials[-1]
    print(f"\n  Result: {'✅ converged' if last.success else '❌ stuck'} "
          f"in {len(trials)} trials")

summarize(trials, "REFLEXION RUN (with episodic memory)")
print(f"\n💡 The LLM adapted based on reflections, improving each trial.")

# %% [markdown]
# ## Step 8 — Try It Yourself
#
# Edit the prompt below to try a different puzzle or modify the evaluation. What happens if you change TARGET? What if the LLM misunderstands the reflection?

# %%
# TODO: Experiment!
# 1. Try changing TARGET to a different value (e.g., 15 or 25)
# 2. Or modify the actor prompt above to be more or less explicit
# 3. Or add a heuristic evaluator (e.g., mark stuck if same attempt twice)

# Re-run the loop with a different target
TARGET_EXPERIMENT = 18  # Change this
print(f"Running reflexion with TARGET = {TARGET_EXPERIMENT}")

trials_exp = await run_reflexion(max_trials=4, target=TARGET_EXPERIMENT)
summarize(trials_exp, f"EXPERIMENT (TARGET={TARGET_EXPERIMENT})")
print(f"\n=== Final: {'✅ Success' if trials_exp[-1].success else '❌ Failed'} in {len(trials_exp)} trials (target={TARGET_EXPERIMENT}) ===")

print("\n✅ Notebook complete! You now understand:")
print("  - Actor: LLM generates attempts")
print("  - Evaluator: binary signal (pass/fail)")
print("  - Self-Reflector: LLM writes why it failed")
print("  - Episodic Memory: reflections feed back into next trial")
print("  - Result: verbal reinforcement without gradients")
