# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/11-llm-engineering/03-structured-outputs
# Used in courses: AI-06
# Framework: vanilla-openai
# Requires API key: False

"""Support-ticket triage: extract a typed TriageTicket record from a support agent's response, validating against JSON schema and handling parse errors and refusals."""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "/api/llm"  # same-origin proxy; server injects the gateway key
lrn_llm.DEFAULT_MODEL = "azure/gpt-4o"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    _key = lrn_llm.API_KEY
    if _key:
        headers["Authorization"] = "Bearer " + _key
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key
#
# Set your API key (optional; the LHIND gateway works without a key on the internal network).

# %%
lrn_llm.API_KEY = ""
print(f"Endpoint: {lrn_llm.API_BASE}")
print(f"Model: {lrn_llm.DEFAULT_MODEL}")
print(f"Key set: {bool(lrn_llm.API_KEY)}")

# %% [markdown]
# ## Step 1 — Reachability
#
# Ping the LLM endpoint to verify the connection is working.

# %%
r = await lrn_llm.ping()
print("✅ LLM erreichbar:", r)

# %% [markdown]
# ## Step 2 — The Problem: Unstructured IT Support Responses
#
# Your IT helpdesk receives natural-language answers from support agents. Your ticketing system needs structured, typed records to organize and route them properly. Without schema validation, you're left parsing free-form text with regex.

# %%
# Example raw helpdesk responses
raw_responses = [
    """The issue is with the employee's VPN connection. They're unable to authenticate using their corporate credentials. We've verified the account is active and the VPN gateway is responding. Recommend resetting their VPN certificate and checking firewall rules. This is urgent as they cannot access critical project resources.""",
    """User reported their laptop will not boot. We've confirmed the SSD is functioning and there are no obvious hardware failures. The Windows bootloader appears corrupted. This is not blocking critical operations but the user needs a working device soon. Recommend a clean OS reinstall or sending to hardware repair.""",
]

for i, response in enumerate(raw_responses, 1):
    print(f"Response {i}:")
    print(response)
    print("-" * 60)

# %% [markdown]
# ## Step 3 — Define the Support Answer Schema
#
# We need each response to be extracted into a **TriageTicket** with: `category` (network, hardware, software, account), `priority` (high/medium/low), `summary` (concise description), and `requires_escalation` (boolean). This is the contract the LLM must follow.

# %%
ticket_schema = {
    "type": "object",
    "properties": {
        "category": {
            "type": "string",
            "enum": ["network", "hardware", "software", "account"]
        },
        "priority": {
            "type": "string",
            "enum": ["high", "medium", "low"]
        },
        "summary": {"type": "string"},
        "requires_escalation": {"type": "boolean"}
    },
    "required": ["category", "priority", "summary", "requires_escalation"]
}

print("TriageTicket Schema:")
print(json.dumps(ticket_schema, indent=2))

# %% [markdown]
# ## Step 4 — Build a Schema Validator
#
# Implement validation logic that checks if the LLM's output matches the schema. This catches parse errors and structural violations.

# %%
def validate_schema(data, schema):
    """Check if data matches schema. Returns list of errors (empty = valid)."""
    errors = []
    
    if schema.get("type") == "object":
        if not isinstance(data, dict):
            return [f"Expected object, got {type(data).__name__}"]
        
        # Check required fields
        for field in schema.get("required", []):
            if field not in data:
                errors.append(f"Required field missing: {field}")
        
        # Validate each field
        for key, value in data.items():
            if key in schema.get("properties", {}):
                prop_schema = schema["properties"][key]
                prop_errors = _validate_value(value, prop_schema, key)
                errors.extend(prop_errors)
    
    return errors

def _validate_value(value, schema, path=""):
    """Recursively validate a single value against a schema."""
    errors = []
    schema_type = schema.get("type")
    
    if schema_type == "string":
        if not isinstance(value, str):
            errors.append(f"{path}: expected string, got {type(value).__name__}")
        elif "enum" in schema and value not in schema["enum"]:
            errors.append(f"{path}: '{value}' not in {schema['enum']}")
    
    elif schema_type == "boolean":
        if not isinstance(value, bool):
            errors.append(f"{path}: expected boolean, got {type(value).__name__}")
    
    return errors

# Test the validator
test_ticket = {"category": "network", "priority": "high", "summary": "VPN auth failed", "requires_escalation": True}
errors = validate_schema(test_ticket, ticket_schema)
print(f"Valid ticket: {errors}")

invalid_ticket = {"category": "INVALID", "priority": "high", "summary": "Test"}
errors = validate_schema(invalid_ticket, ticket_schema)
print(f"Invalid ticket errors: {errors}")

# %% [markdown]
# ## Step 5 — Extract a Real Support Response
#
# Send a real helpdesk response to the LLM and ask it to extract a TriageTicket as JSON. Watch how the schema constraint forces clean, typed output.

# %%
response_to_extract = raw_responses[0]

system_prompt = """You are an IT support triage expert. Extract ticket information from a support agent's response.
Respond ONLY with valid JSON matching this schema:
{
  "category": one of [network, hardware, software, account],
  "priority": one of [high, medium, low],
  "summary": a 1-2 sentence summary of the issue and recommended action,
  "requires_escalation": true if urgent or requires senior engineer, false otherwise
}
No preamble. No markdown. Only JSON."""

user_message = f"Extract ticket information from this support response:\n\n{response_to_extract}"

resp = await lrn_llm.call(
    [{"role": "user", "content": user_message}],
    system=system_prompt,
    max_tokens=200
)

raw_response = lrn_llm.text(resp)
print("LLM Response:")
print(raw_response)
print()

# Parse and validate
try:
    ticket = json.loads(raw_response)
    errors = validate_schema(ticket, ticket_schema)
    if errors:
        print(f"Validation errors: {errors}")
    else:
        print("✅ Ticket is valid!")
        print(json.dumps(ticket, indent=2))
except json.JSONDecodeError as e:
    print(f"❌ Failed to parse JSON: {e}")

# %% [markdown]
# ## Step 6 — Handle Refusal (Invalid Input Path)
#
# Test what happens when we send the LLM something that cannot be triaged (e.g., spam, off-topic content). The schema validator should reject it, or the LLM may refuse entirely.

# %%
# Off-topic message that is not a valid support response
invalid_input = """This is just a random chat message. Please tell me a joke about cats and tell me what your favorite color is."""

user_message = f"Extract ticket information from this support response:\n\n{invalid_input}"

resp = await lrn_llm.call(
    [{"role": "user", "content": user_message}],
    system=system_prompt,
    max_tokens=200
)

raw_response = lrn_llm.text(resp)
print("LLM Response to invalid input:")
print(raw_response)
print()

try:
    ticket = json.loads(raw_response)
    errors = validate_schema(ticket, ticket_schema)
    if errors:
        print(f"❌ Validation errors (expected for invalid input): {errors}")
    else:
        print("✅ Ticket is valid (LLM interpreted input)")
        print(json.dumps(ticket, indent=2))
except json.JSONDecodeError as e:
    print(f"❌ Failed to parse JSON (LLM refused): {e}")
    print("This is OK — the LLM sensed invalid input and refused to produce JSON.")

# %% [markdown]
# ## Step 7 — Extraction Pipeline with Retry Logic
#
# Combine validation with retries: if the first attempt fails, send errors back to the model and ask it to fix the output.

# %%
async def extract_ticket_with_retry(response_text, max_retries=2):
    """Extract a ticket from a support response with automatic retry on validation failure."""
    system_prompt = """You are an IT support triage expert. Extract ticket information from a support agent's response.
Respond ONLY with valid JSON matching this schema:
{
  "category": one of [network, hardware, software, account],
  "priority": one of [high, medium, low],
  "summary": a 1-2 sentence summary of the issue and recommended action,
  "requires_escalation": true if urgent or requires senior engineer, false otherwise
}
No preamble. No markdown. Only JSON."""
    
    messages = [{"role": "user", "content": f"Extract ticket information from this support response:\n\n{response_text}"}]
    
    for attempt in range(max_retries):
        resp = await lrn_llm.call(messages, system=system_prompt, max_tokens=200)
        raw_response = lrn_llm.text(resp)
        
        try:
            ticket = json.loads(raw_response)
        except json.JSONDecodeError as e:
            print(f"Attempt {attempt + 1}: JSON parse error -- {e}")
            continue
        
        errors = validate_schema(ticket, ticket_schema)
        if not errors:
            return ticket
        
        print(f"Attempt {attempt + 1}: Schema validation failed -- {errors}")
        if attempt < max_retries - 1:
            messages.append({"role": "assistant", "content": raw_response})
            messages.append({
                "role": "user",
                "content": f"Fix these validation errors: {errors}. Return valid JSON only."
            })
    
    return None

# Test with the second response
ticket = await extract_ticket_with_retry(raw_responses[1])
if ticket:
    print("✅ Extracted ticket:")
    print(json.dumps(ticket, indent=2))
else:
    print("❌ Failed to extract ticket after retries")

# %% [markdown]
# ## Step 8 — Try It Yourself
#
# Edit the support response below and run the extraction pipeline. Watch how structured output forces clean, typed data even from messy support input.

# %%
# TODO: Replace this with your own IT support response
custom_response = """User's email client is not syncing. We've checked the mailbox configuration and the server connection is stable. The issue appears to be a caching problem in Outlook. They can still access email via the web portal. This is mildly annoying but not critical. We recommend clearing the local cache and reconnecting the account, which should resolve it."""

print("Processing support response:")
print(custom_response)
print()

ticket = await extract_ticket_with_retry(custom_response)
if ticket:
    print("✅ Extracted ticket:")
    print(json.dumps(ticket, indent=2))
    print()
    print(f"Action: Route to {ticket['category'].upper()} team (priority: {ticket['priority']})")
    if ticket['requires_escalation']:
        print("⚠️  Flag for escalation to senior engineer")
    else:
        print("✓ Standard priority")
else:
    print("❌ Could not extract structured ticket")
