# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/11-llm-engineering/03-structured-outputs
# Used in courses: AI-18
# Framework: stdlib
# Requires API key: False

"""Consulting brief → typed recommendation via JSON schema validation with retry"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "https://gateway.lhind.ai/v1"
lrn_llm.DEFAULT_MODEL = "azure/gpt-4o"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    if lrn_llm.API_KEY:
        headers["Authorization"] = "Bearer " + lrn_llm.API_KEY
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key
#
# Set your optional API key (the LHIND gateway works without a key on the network). Then verify the endpoint and model.

# %%
# Optional: set your API key if you have one
lrn_llm.API_KEY = ""

print(f"Endpoint: {lrn_llm.API_BASE}")
print(f"Model: {lrn_llm.DEFAULT_MODEL}")
print(f"Key set: {bool(lrn_llm.API_KEY)}")

# %% [markdown]
# ## Step 1 — Reachability
#
# Ping the LLM endpoint to confirm it's reachable.

# %%
r = await lrn_llm.ping()
print(f"✅ LLM erreichbar: {r}")

# %% [markdown]
# ## Step 2 — The Scenario: Structured Consulting Recommendations
#
# You are a management consultant analyzing client problems. For each consulting brief (problem statement + context), you must produce a **structured recommendation** with exact fields: category (strategy/operations/finance), priority (high/medium/low), risk (identified risks as array), and control_measures (required actions as array).
#
# The challenge: the LLM returns free text. You need schema-validated JSON that your executive dashboard can parse and display reliably. Invalid JSON or missing fields crashes the pipeline.
#
# You'll build a validator that ensures the recommendation matches your schema, and retry with error feedback if it doesn't.

# %% [markdown]
# ## Step 3 — Define the JSON Schema
#
# Define the exact structure your recommendations must follow. Every field has a type, and some fields have constraints (enums for category/priority, required fields, arrays with specific item types).

# %%
recommendation_schema = {
    "type": "object",
    "properties": {
        "category": {
            "type": "string",
            "enum": ["strategy", "operations", "finance"]
        },
        "priority": {
            "type": "string",
            "enum": ["high", "medium", "low"]
        },
        "risk": {
            "type": "array",
            "items": {"type": "string"},
            "minItems": 1
        },
        "control_measures": {
            "type": "array",
            "items": {"type": "string"},
            "minItems": 1
        }
    },
    "required": ["category", "priority", "risk", "control_measures"]
}

print("Recommendation Schema:")
print(json.dumps(recommendation_schema, indent=2))

# %% [markdown]
# ## Step 4 — Build a Schema Validator
#
# Implement validation logic to check whether a parsed JSON object matches the schema. Validation catches three categories of errors: type mismatches, missing required fields, and constraint violations (enums, array length).

# %%
def validate_schema(data, schema):
    """Validate a Python object against a JSON Schema. Return list of error strings."""
    errors = []
    _validate(data, schema, "", errors)
    return errors

def _validate(data, schema, path, errors):
    schema_type = schema.get("type")
    
    if schema_type == "object":
        if not isinstance(data, dict):
            errors.append(f"{path}: expected object, got {type(data).__name__}")
            return
        for key in schema.get("required", []):
            if key not in data:
                errors.append(f"{path}.{key}: required field missing")
        properties = schema.get("properties", {})
        for key, value in data.items():
            if key in properties:
                _validate(value, properties[key], f"{path}.{key}", errors)
    
    elif schema_type == "array":
        if not isinstance(data, list):
            errors.append(f"{path}: expected array, got {type(data).__name__}")
            return
        min_items = schema.get("minItems", 0)
        if len(data) < min_items:
            errors.append(f"{path}: array has {len(data)} items, minimum is {min_items}")
        items_schema = schema.get("items", {})
        for i, item in enumerate(data):
            _validate(item, items_schema, f"{path}[{i}]", errors)
    
    elif schema_type == "string":
        if not isinstance(data, str):
            errors.append(f"{path}: expected string, got {type(data).__name__}")
            return
        enum_values = schema.get("enum")
        if enum_values and data not in enum_values:
            errors.append(f"{path}: '{data}' not in allowed values {enum_values}")

# Test the validator
valid_rec = {"category": "strategy", "priority": "high", "risk": ["market volatility"], "control_measures": ["diversify portfolio"]}
invalid_rec = {"category": "strategy", "priority": "urgent"}  # invalid enum, missing fields

print("Valid recommendation:", "PASS" if not validate_schema(valid_rec, recommendation_schema) else "FAIL")
print("Invalid recommendation:", "PASS (detected errors)" if validate_schema(invalid_rec, recommendation_schema) else "FAIL")
print("Errors:", validate_schema(invalid_rec, recommendation_schema))

# %% [markdown]
# ## Step 5 — Call the LLM with a Consulting Brief
#
# Prompt the LLM to analyze a consulting brief and produce a structured recommendation as JSON. This is the real call — the LLM returns free-form text that may or may not be valid JSON.

# %%
consulting_brief = """
Client: MediTech Solutions, a mid-sized medical device manufacturer.
Problem: Supply chain disruptions have delayed product delivery by 8 weeks. Customer satisfaction is at 62%, down from 88% last year. The CEO wants a plan to restore trust and prevent future delays.
Context: The company has 15 suppliers, 4 of which are single-source dependencies. Inventory buffer is currently 2 weeks; competitors maintain 4-6 weeks.
"""

system_prompt = f"""You are a management consultant. Analyze this consulting brief and produce a JSON recommendation.
Your response MUST be valid JSON matching this schema:
{json.dumps(recommendation_schema)}

Respond ONLY with the JSON object, no markdown or extra text."""

r = await lrn_llm.call(
    [{"role": "user", "content": consulting_brief}],
    system=system_prompt,
    max_tokens=300
)
raw_response = lrn_llm.text(r)
print("LLM Response (raw):")
print(raw_response)

# %% [markdown]
# ## Step 6 — Parse and Validate the Response
#
# Attempt to parse the LLM's response as JSON, then validate it against the schema. If validation fails, log the errors.

# %%
try:
    parsed = json.loads(raw_response)
    print("✅ JSON parsed successfully")
except json.JSONDecodeError as e:
    print(f"❌ JSON parse error: {e}")
    parsed = None

if parsed:
    errors = validate_schema(parsed, recommendation_schema)
    if not errors:
        print("✅ Schema validation passed")
        print("Recommendation:")
        print(json.dumps(parsed, indent=2))
    else:
        print(f"❌ Schema validation failed:")
        for err in errors:
            print(f"  - {err}")

# %% [markdown]
# ## Step 7 — Retry with Error Feedback
#
# If validation failed, send the errors back to the LLM and ask it to fix the recommendation. This demonstrates how structured outputs work with retries: the LLM sees exactly what's wrong and can correct it.

# %%
async def extract_recommendation_with_retry(brief, schema, max_retries=2):
    """Extract a structured recommendation with retry on validation failure."""
    system_prompt = f"""You are a management consultant. Analyze the consulting brief and produce a JSON recommendation.
    Your response MUST be valid JSON matching this schema:
    {json.dumps(schema)}
    
    Respond ONLY with the JSON object, no markdown or extra text."""
    
    for attempt in range(max_retries):
        if attempt == 0:
            # First attempt: just the brief
            msg = brief
        else:
            # Retry: brief + validation errors
            msg = f"{brief}\n\nPrevious attempt had these errors:\n" + "\n".join([f"  - {e}" for e in errors])
        
        r = await lrn_llm.call(
            [{"role": "user", "content": msg}],
            system=system_prompt,
            max_tokens=300
        )
        raw = lrn_llm.text(r)
        
        try:
            parsed = json.loads(raw)
        except json.JSONDecodeError as e:
            print(f"  Attempt {attempt + 1}: JSON parse error -- {e}")
            continue
        
        errors = validate_schema(parsed, schema)
        if not errors:
            print(f"  Attempt {attempt + 1}: ✅ Success")
            return parsed
        
        print(f"  Attempt {attempt + 1}: Validation failed -- {errors}")
    
    return None

print("Extracting recommendation with retry...")
result = await extract_recommendation_with_retry(consulting_brief, recommendation_schema, max_retries=2)
if result:
    print("\nFinal recommendation:")
    print(json.dumps(result, indent=2))
else:
    print("❌ Failed to extract valid recommendation after retries")

# %% [markdown]
# ## Step 8 — Try It Yourself
#
# Write your own consulting brief and extract a recommendation. Edit the `brief` variable and run the cell.

# %%
# TODO: Edit this consulting brief with your own scenario
my_brief = """
Client: FinServe Bank, a regional financial services company.
Problem: Cybersecurity incident exposed customer data; regulatory fines pending. Need immediate action plan.
Context: Legacy systems, underfunded security team, outdated compliance processes.
"""

print("Your brief:")
print(my_brief)
print("\nExtracting recommendation...")

my_result = await extract_recommendation_with_retry(my_brief, recommendation_schema, max_retries=2)
if my_result:
    print("\n✅ Recommendation extracted:")
    print(json.dumps(my_result, indent=2))
else:
    print("\n❌ Could not extract valid recommendation")
