# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/11-llm-engineering/03-structured-outputs
# Used in courses: PROMPT-01
# Framework: vanilla-openai
# Requires API key: False

"""Support-ticket triage: turn raw customer-support emails into a typed TriageTicket record."""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "/api/llm"  # same-origin proxy; server injects the gateway key
lrn_llm.DEFAULT_MODEL = "azure/gpt-5.4"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    _key = lrn_llm.API_KEY
    if _key:
        headers["Authorization"] = "Bearer " + _key
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key
#
# Set your API key (optional; the LHIND gateway works without a key on the internal network).

# %%
lrn_llm.API_KEY = ""
print(f"Endpoint: {lrn_llm.API_BASE}")
print(f"Model: {lrn_llm.DEFAULT_MODEL}")
print(f"Key set: {bool(lrn_llm.API_KEY)}")

# %% [markdown]
# ## Step 1 — Reachability
#
# Ping the LLM endpoint to verify the connection is working.

# %%
r = await lrn_llm.ping()
print("✅ LLM erreichbar:", r)

# %% [markdown]
# ## Step 2 — The Problem: Unstructured Tickets
#
# Customer support receives emails in freeform text. Your system needs typed, validated ticket records to route them to the right team. Without structure, you parse with regex at 3am and miss critical fields.

# %%
# Example raw support emails
raw_emails = [
    """Subject: Login not working
I can't log in to my account. I get an error that says 'Invalid credentials' but my password is correct. This is blocking me from accessing my data. Please help ASAP!""",
    """Subject: Billing inquiry
Hi, I want to know why I was charged twice for my subscription. My order number is ORD-2024-5678 and I was charged on June 15th and June 16th. Very upset.""",
]

for i, email in enumerate(raw_emails, 1):
    print(f"Email {i}:")
    print(email)
    print("-" * 60)

# %% [markdown]
# ## Step 3 — Define the Ticket Schema
#
# We want each ticket to have: `category` (one of: billing, technical, account, feedback), `priority` (high/medium/low), `summary` (short description), and `requires_immediate_response` (boolean).
#
# This is the contract the LLM must follow.

# %%
ticket_schema = {
    "type": "object",
    "properties": {
        "category": {
            "type": "string",
            "enum": ["billing", "technical", "account", "feedback"]
        },
        "priority": {
            "type": "string",
            "enum": ["high", "medium", "low"]
        },
        "summary": {"type": "string"},
        "requires_immediate_response": {"type": "boolean"}
    },
    "required": ["category", "priority", "summary", "requires_immediate_response"]
}

print("TriageTicket Schema:")
print(json.dumps(ticket_schema, indent=2))

# %% [markdown]
# ## Step 4 — Validate Against Schema
#
# Build a validator that checks if parsed JSON matches the schema. This is what runs on the output side.

# %%
def validate_schema(data, schema):
    """Check if data matches schema. Returns list of errors (empty = valid)."""
    errors = []
    
    if schema.get("type") == "object":
        if not isinstance(data, dict):
            return [f"Expected object, got {type(data).__name__}"]
        
        # Check required fields
        for field in schema.get("required", []):
            if field not in data:
                errors.append(f"Required field missing: {field}")
        
        # Validate each field
        for key, value in data.items():
            if key in schema.get("properties", {}):
                prop_schema = schema["properties"][key]
                prop_errors = _validate_value(value, prop_schema, key)
                errors.extend(prop_errors)
    
    return errors

def _validate_value(value, schema, path=""):
    """Recursively validate a single value against a schema."""
    errors = []
    schema_type = schema.get("type")
    
    if schema_type == "string":
        if not isinstance(value, str):
            errors.append(f"{path}: expected string, got {type(value).__name__}")
        elif "enum" in schema and value not in schema["enum"]:
            errors.append(f"{path}: '{value}' not in {schema['enum']}")
    
    elif schema_type == "boolean":
        if not isinstance(value, bool):
            errors.append(f"{path}: expected boolean, got {type(value).__name__}")
    
    return errors

# Test the validator
test_ticket = {"category": "technical", "priority": "high", "summary": "Login broken", "requires_immediate_response": True}
errors = validate_schema(test_ticket, ticket_schema)
print(f"Valid ticket: {errors}")

invalid_ticket = {"category": "INVALID", "priority": "high", "summary": "Test"}
errors = validate_schema(invalid_ticket, ticket_schema)
print(f"Invalid ticket errors: {errors}")

# %% [markdown]
# ## Step 5 — Extract & Validate a Real Email
#
# Now send a real support email to the LLM and ask it to produce a TriageTicket as JSON. Use strict mode to ensure the output matches the schema.

# %%
email_to_triage = raw_emails[0]

system_prompt = """You are a support ticket triage expert. Extract ticket information from a customer email.
Respond ONLY with valid JSON matching this schema:
{
  "category": one of [billing, technical, account, feedback],
  "priority": one of [high, medium, low],
  "summary": a 1-2 sentence summary of the issue,
  "requires_immediate_response": true if the customer is angry or blocked, false otherwise
}
No preamble. No markdown. Only JSON."""

user_message = f"Triage this support email:\n\n{email_to_triage}"

resp = await lrn_llm.call(
    [{"role": "user", "content": user_message}],
    system=system_prompt,
    max_tokens=200
)

raw_response = lrn_llm.text(resp)
print("LLM Response:")
print(raw_response)
print()

# Parse and validate
try:
    ticket = json.loads(raw_response)
    errors = validate_schema(ticket, ticket_schema)
    if errors:
        print(f"Validation errors: {errors}")
    else:
        print("✅ Ticket is valid!")
        print(json.dumps(ticket, indent=2))
except json.JSONDecodeError as e:
    print(f"❌ Failed to parse JSON: {e}")

# %% [markdown]
# ## Step 6 — Handle Invalid Input (Spam)
#
# Now test what happens when we send the LLM something completely off-topic. The schema validator should reject it.

# %%
# A spam/off-topic email
spam_email = """Subject: FREE MONEY!!!
CLICK HERE NOW to claim your FREE PRIZE!!! You have won 1 MILLION DOLLARS!!!!
Just reply with your credit card info and banking details.
This is a LIMITED TIME OFFER!!!"""

user_message = f"Triage this support email:\n\n{spam_email}"

resp = await lrn_llm.call(
    [{"role": "user", "content": user_message}],
    system=system_prompt,
    max_tokens=200
)

raw_response = lrn_llm.text(resp)
print("LLM Response to spam:")
print(raw_response)
print()

try:
    ticket = json.loads(raw_response)
    errors = validate_schema(ticket, ticket_schema)
    if errors:
        print(f"❌ Validation errors (expected for spam): {errors}")
    else:
        print("✅ Ticket is valid (LLM triaged spam correctly)")
        print(json.dumps(ticket, indent=2))
except json.JSONDecodeError as e:
    print(f"❌ Failed to parse JSON (LLM refused): {e}")
    print("This is OK — the LLM sensed invalid input and refused to produce JSON.")

# %% [markdown]
# ## Step 7 — Full Extraction Pipeline with Retries
#
# Combine validation with retry logic: if the first attempt fails, send errors back to the model and ask it to fix the output.

# %%
async def extract_ticket_with_retry(email, max_retries=2):
    """Extract a ticket from an email with automatic retry on validation failure."""
    system_prompt = """You are a support ticket triage expert. Extract ticket information from a customer email.
Respond ONLY with valid JSON matching this schema:
{
  "category": one of [billing, technical, account, feedback],
  "priority": one of [high, medium, low],
  "summary": a 1-2 sentence summary of the issue,
  "requires_immediate_response": true if the customer is angry or blocked, false otherwise
}
No preamble. No markdown. Only JSON."""
    
    messages = [{"role": "user", "content": f"Triage this support email:\n\n{email}"}]
    
    for attempt in range(max_retries):
        resp = await lrn_llm.call(messages, system=system_prompt, max_tokens=200)
        raw_response = lrn_llm.text(resp)
        
        try:
            ticket = json.loads(raw_response)
        except json.JSONDecodeError as e:
            print(f"Attempt {attempt + 1}: JSON parse error -- {e}")
            continue
        
        errors = validate_schema(ticket, ticket_schema)
        if not errors:
            return ticket
        
        print(f"Attempt {attempt + 1}: Schema validation failed -- {errors}")
        if attempt < max_retries - 1:
            messages.append({"role": "assistant", "content": raw_response})
            messages.append({
                "role": "user",
                "content": f"Fix these validation errors: {errors}. Return valid JSON only."
            })
    
    return None

# Test with the billing email
ticket = await extract_ticket_with_retry(raw_emails[1])
if ticket:
    print("✅ Extracted ticket:")
    print(json.dumps(ticket, indent=2))
else:
    print("❌ Failed to extract ticket after retries")

# %% [markdown]
# ## Step 8 — Try It Yourself
#
# Edit the email below and run the extraction pipeline. Watch how structured output forces clean, typed data even from messy customer input.

# %%
# TODO: Replace this with your own customer support email
custom_email = """Subject: Refund Request
Hi, I purchased a subscription last month but I'm not happy with the service.
I haven't used it much and would like a full refund. My order number is ORD-2024-9999.
Thanks,
John"""

print("Processing custom email:")
print(custom_email)
print()

ticket = await extract_ticket_with_retry(custom_email)
if ticket:
    print("✅ Extracted ticket:")
    print(json.dumps(ticket, indent=2))
    print()
    print(f"Action: Route to {ticket['category'].upper()} team (priority: {ticket['priority']})")
    if ticket['requires_immediate_response']:
        print("⚠️  Flag for immediate response")
else:
    print("❌ Could not extract structured ticket")
