#!/usr/bin/env node
/**
 * Keeps the editable LRN curriculum manifests and browser globals in sync.
 * The JSON files are the canonical source used by the curriculum admin.
 * Run with --extract once to migrate the legacy browser assignments, with
 * --check in CI, or without flags to regenerate the compatibility files.
 */

const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const assert = require("node:assert/strict");

const ROOT = path.resolve(__dirname, "..");
const LRN = path.join(ROOT, "site", "lrn");
const MANIFESTS = path.join(LRN, "manifests");
const TARGETS = [
  {
    manifest: path.join(MANIFESTS, "catalog.json"),
    browser: path.join(LRN, "data.js"),
    global: "LrnData",
  },
  {
    manifest: path.join(MANIFESTS, "curriculum-map.json"),
    browser: path.join(LRN, "curriculum-map.js"),
    global: "LrnCurriculumMap",
  },
];

function readBrowserGlobal(target) {
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  vm.runInContext(fs.readFileSync(target.browser, "utf8"), sandbox, {
    filename: path.basename(target.browser),
  });
  const value = sandbox.window[target.global];
  if (!value || typeof value !== "object") {
    throw new Error(`${target.browser} did not assign window.${target.global}`);
  }
  return JSON.parse(JSON.stringify(value));
}

function readManifest(target) {
  return JSON.parse(fs.readFileSync(target.manifest, "utf8"));
}

function browserSource(target, value) {
  return [
    "// Generated by scripts/build_lrn_manifests.js. Edit the JSON manifest instead.",
    `window.${target.global} = ${JSON.stringify(value, null, 2)};`,
    "",
  ].join("\n");
}

function extract() {
  fs.mkdirSync(MANIFESTS, { recursive: true });
  for (const target of TARGETS) {
    const value = readBrowserGlobal(target);
    fs.writeFileSync(target.manifest, `${JSON.stringify(value, null, 2)}\n`);
    console.log(`extracted ${path.relative(ROOT, target.manifest)}`);
  }
}

function build() {
  for (const target of TARGETS) {
    const value = readManifest(target);
    fs.writeFileSync(target.browser, browserSource(target, value));
    console.log(`built ${path.relative(ROOT, target.browser)}`);
  }
}

function check() {
  for (const target of TARGETS) {
    assert.deepStrictEqual(
      readBrowserGlobal(target),
      readManifest(target),
      `${path.relative(ROOT, target.browser)} has drifted from its manifest`,
    );
    console.log(`ok ${path.relative(ROOT, target.manifest)}`);
  }
}

const mode = process.argv[2];
if (mode === "--extract") extract();
else if (mode === "--check") check();
else if (!mode) build();
else {
  console.error("usage: node scripts/build_lrn_manifests.js [--extract|--check]");
  process.exitCode = 2;
}
