#!/usr/bin/env python3
"""Generate `notebook.py` files from the audit workflow's lesson-notebook-specs.

Reads `outputs/lrn-audit/lesson-notebook-specs.json` (produced by
`.claude/workflows/audit-tc-courses.js`) and writes one
`phases/<phase>/<lesson>/code/notebook.py` per unique lesson.

Each generated file:
  - has a fixed AUTOGENERATED header naming the source spec and Course IDs it
    serves, so the lineage is grep-able from the lesson directory
  - is jupytext-compatible (# %% markers) so `ide/jupyterlite/py_to_notebook.py`
    splits it into clean cells
  - is idempotent: re-running with the same spec leaves the file unchanged
    (hash compared on the generated body)

Usage:
  python3 scripts/generate_notebooks.py
  python3 scripts/generate_notebooks.py --lesson phases/14-agent-engineering/13-langgraph-stateful-graphs
  python3 scripts/generate_notebooks.py --dry-run
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SPECS_FILE = REPO / "outputs" / "lrn-audit" / "lesson-notebook-specs.json"


def render(spec: dict) -> str:
    """Spec → notebook.py source string."""
    lesson_path = spec["lesson_path"]
    courses = ", ".join(spec.get("in_courses") or ([spec["course"]] if spec.get("course") else []))
    framework = spec.get("framework", "stdlib")
    requires_key = spec.get("requires_api_key", False)
    api_key_name = spec.get("api_key_name", "")
    pip_requires = spec.get("pip_requires", [])
    scenario_hook = spec.get("scenario_hook", "")
    fallback = spec.get("fallback_static_output", "")

    lines: list[str] = []
    lines.append("# AUTOGENERATED — do not hand-edit; rerun audit workflow.")
    lines.append(f"# Lesson: {lesson_path}")
    lines.append(f"# Used in courses: {courses}")
    lines.append(f"# Framework: {framework}")
    lines.append(f"# Requires API key: {requires_key}"
                 + (f" ({api_key_name})" if requires_key and api_key_name else ""))
    if pip_requires:
        lines.append(f"# Pip requires (Pyodide micropip): {', '.join(pip_requires)}")
    lines.append("")
    lines.append(f'"""{scenario_hook.strip() or lesson_path}"""')
    lines.append("")

    if requires_key and api_key_name:
        # The lesson.html settings dialog + key-injector inject os.environ[KEY]
        # before this notebook is mounted. We still guard with a clear error
        # if a learner opens the raw notebook in JupyterLite without a key set.
        lines.append("import os")
        lines.append("if not os.environ.get(" + repr(api_key_name) + "):")
        lines.append("    raise RuntimeError(")
        lines.append(f'        "Set {api_key_name} via the gear icon in the lesson header before running this notebook."')
        lines.append("    )")
        lines.append("")

    for cell in spec.get("cells", []):
        kind = cell.get("kind", "code")
        content = cell.get("content", "").rstrip("\n")
        if kind == "markdown":
            lines.append("# %% [markdown]")
            for ml in content.splitlines():
                lines.append(f"# {ml}" if ml else "#")
            lines.append("")
        else:
            lines.append("# %%")
            lines.append(content)
            lines.append("")

    if fallback:
        lines.append("# %% [markdown]")
        lines.append("# ## Fallback (no live API access)")
        lines.append("#")
        lines.append("# If the cells above can't reach a live service, here is the static output")
        lines.append("# the lesson should produce, so you can still walk through the concept:")
        lines.append("#")
        for ml in fallback.splitlines():
            lines.append(f"# {ml}" if ml else "#")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def lesson_dir(lesson_path: str) -> Path:
    return REPO / lesson_path


def should_write(target: Path, new_content: str) -> bool:
    if not target.exists():
        return True
    old = target.read_text(encoding="utf-8")
    return _body_hash(old) != _body_hash(new_content)


def _body_hash(text: str) -> str:
    # Ignore the leading "Used in courses:" line so course-set churn alone
    # (same scenario, different course coverage) doesn't rewrite the file.
    body = "\n".join(L for L in text.splitlines()
                     if not L.startswith("# Used in courses:"))
    return hashlib.sha256(body.encode("utf-8")).hexdigest()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--lesson", help="Generate only this lesson_path (e.g. phases/14-.../13-langgraph...)")
    ap.add_argument("--dry-run", action="store_true", help="Show what would change, don't write")
    ap.add_argument("--specs", type=Path, default=SPECS_FILE)
    ap.add_argument(
        "--include-all-built",
        action="store_true",
        help="Also allowlist EVERY lesson that builds a notebook (has code/main.py or "
        "code/notebook*.py and no code/.no-notebook), as ['*']. Curated per-course "
        "specs keep their finer entry; this only ADDS the built-but-uncurated lessons. "
        "Use to surface all main.py lesson notebooks in LRN mode, not just the audit set.",
    )
    args = ap.parse_args()

    specs_present = args.specs.exists()
    if not specs_present and not args.include_all_built:
        print(f"Specs file not found: {args.specs}", file=sys.stderr)
        print("Run the audit workflow first: Workflow({name: 'audit-tc-courses'})", file=sys.stderr)
        return 2

    if specs_present:
        data = json.loads(args.specs.read_text(encoding="utf-8"))
    else:
        # No specs locally (they are gitignored). With --include-all-built we can
        # still refresh the allowlist: seed the curated base from the committed
        # notebook-index.json so the audit per-course entries survive, and only ADD
        # the built-but-uncurated lessons. Per-lesson generation is skipped.
        print("Specs file absent; --include-all-built runs in allowlist-only mode "
              "(no notebook.py generation, curated base read from notebook-index.json).")
        existing = REPO / "site" / "lrn" / "notebook-index.json"
        seeded = json.loads(existing.read_text(encoding="utf-8")).get("curated", {}) if existing.exists() else {}
        data = {"lessons": [
            {"lesson_path": k, "course": (c if c != "*" else None)}
            for k, courses in seeded.items() for c in courses
        ]}
    specs = data.get("lessons", [])
    if args.lesson:
        specs = [s for s in specs if s.get("lesson_path") == args.lesson]
        if not specs:
            print(f"No spec for lesson_path={args.lesson}", file=sys.stderr)
            return 2

    n_written = n_unchanged = n_skipped = n_opted_out = 0
    # In allowlist-only mode (no specs on disk) the seeded "specs" carry no cells,
    # so skip generation entirely and jump to the allowlist refresh below.
    for spec in (specs if specs_present else []):
        lesson_path = spec.get("lesson_path")
        if not lesson_path:
            continue
        d = lesson_dir(lesson_path)
        if not d.exists():
            print(f"  SKIP  {lesson_path}  (lesson directory missing)")
            n_skipped += 1
            continue
        code_dir = d / "code"
        code_dir.mkdir(exist_ok=True)
        marker = code_dir / ".no-notebook"
        # A divergent lesson built per course writes notebook.<course>.py next to
        # any shared notebook.py; lesson.html loads <lesson>.<course>.ipynb first.
        course = spec.get("course")
        nb_name = f"notebook.{course}.py" if course else "notebook.py"
        target = code_dir / nb_name

        # Lessons the audit decided shouldn't have a notebook (pure theory,
        # vendor comparisons, governance frameworks etc.) get a marker file
        # that the build pipeline respects, and any stale generated notebook
        # is removed. We intentionally leave existing main.py untouched.
        if spec.get("should_have_notebook") is False:
            if args.dry_run:
                print(f"  WOULD opt-out {lesson_path}  ({spec.get('opt_out_reason','no reason given')})")
            else:
                if target.exists():
                    target.unlink()
                marker.write_text(
                    f"# Opt-out from JupyterLite notebook.\n"
                    f"# Source: audit workflow.\n"
                    f"# Reason: {spec.get('opt_out_reason', 'pure theory; docs deliver the learning')}\n",
                    encoding="utf-8",
                )
                print(f"  OPT-OUT {lesson_path}  ({spec.get('opt_out_reason', '')[:60]})")
            n_opted_out += 1
            continue

        # If we had previously opted out but now decide to include, clear the marker.
        if marker.exists() and not args.dry_run:
            marker.unlink()

        content = render(spec)
        # Drop two siblings so the build pipeline knows what to do with this lesson:
        #  - code/.no-prebake : tell build-notebooks.sh to NOT run nbconvert --execute
        #    (audit notebooks have real LLM calls, the learner runs them step-by-step
        #    in JupyterLite — pre-baked outputs would defeat the didactic purpose)
        #  - code/lrn_llm.py  : pyfetch-based Claude wrapper shared by every notebook
        no_prebake = code_dir / ".no-prebake"
        helper_src = REPO / "ide" / "jupyterlite" / "lrn_llm.py"
        helper_dst = code_dir / "lrn_llm.py"

        if not should_write(target, content):
            print(f"  ok    {lesson_path}/code/{nb_name} (unchanged)")
            n_unchanged += 1
            # still ensure the marker + helper are present (in case they were
            # removed by hand or this is the first run after an upgrade)
            if not args.dry_run:
                if not no_prebake.exists():
                    no_prebake.write_text(
                        "# Audit-generated notebook: learner runs cells live, do not pre-bake outputs.\n",
                        encoding="utf-8",
                    )
                if helper_src.exists() and (
                    not helper_dst.exists() or helper_dst.read_bytes() != helper_src.read_bytes()
                ):
                    helper_dst.write_bytes(helper_src.read_bytes())
            continue

        if args.dry_run:
            print(f"  WOULD {lesson_path}/code/{nb_name} ({len(content)} bytes)")
        else:
            target.write_text(content, encoding="utf-8")
            no_prebake.write_text(
                "# Audit-generated notebook: learner runs cells live, do not pre-bake outputs.\n",
                encoding="utf-8",
            )
            if helper_src.exists():
                helper_dst.write_bytes(helper_src.read_bytes())
            print(f"  WRITE {lesson_path}/code/{nb_name} ({len(content)} bytes) + .no-prebake + lrn_llm.py")
        n_written += 1

    # Refresh the LRN notebook allowlist from ALL specs (not just the --lesson subset),
    # so site/lesson.html shows a notebook panel ONLY for curated hands-on lessons.
    # '*' = shared (all courses), else the per-course id. Theory lessons are absent.
    if not args.dry_run:
        import collections
        cur = collections.defaultdict(list)
        for s in data.get("lessons", []):
            if s.get("should_have_notebook") is False:
                continue
            cur[s["lesson_path"]].append(s.get("course") or "*")
        curated = {k: sorted(set(v)) for k, v in cur.items()}

        if args.include_all_built:
            # Add every lesson that actually builds a notebook but isn't part of the
            # curated audit set. These are the plain main.py code demos: no per-course
            # variant, so they get ['*']. Curated entries keep their finer per-course
            # lists — we never overwrite an existing curated key.
            added = 0
            for code_dir in sorted(REPO.glob("phases/*/*/code")):
                lesson_path = str(code_dir.parent.relative_to(REPO))
                if lesson_path in curated:
                    continue
                if (code_dir / ".no-notebook").exists():
                    continue
                has_build = (code_dir / "main.py").exists() or any(
                    code_dir.glob("notebook*.py")
                )
                if not has_build:
                    continue
                curated[lesson_path] = ["*"]
                added += 1
            print(f"--include-all-built: added {added} built-but-uncurated lesson paths")

        idx_obj = {"curated": curated}
        body = json.dumps(idx_obj, ensure_ascii=False, indent=0)
        lrn = REPO / "site" / "lrn"
        (lrn / "notebook-index.json").write_text(body, encoding="utf-8")
        (lrn / "notebook-index.js").write_text(
            "// AUTOGENERATED by scripts/generate_notebooks.py — curated LRN hands-on notebooks.\n"
            "window.LrnNotebookIndex = " + body + ";\n", encoding="utf-8")
        print(f"notebook-index: {len(idx_obj['curated'])} curated lesson paths")

    print()
    print(f"written: {n_written}, unchanged: {n_unchanged}, "
          f"opted-out: {n_opted_out}, skipped: {n_skipped}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
