# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/13-tools-and-protocols/02-function-calling-deep-dive
# Used in courses: AI-06
# Framework: vanilla-openai
# Requires API key: False

"""weather_tool_call"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "https://gateway.lhind.ai/v1"
lrn_llm.DEFAULT_MODEL = "azure/gpt-4o"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    if lrn_llm.API_KEY:
        headers["Authorization"] = "Bearer " + lrn_llm.API_KEY
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key

# %%
lrn_llm.API_KEY = ""  # optional; gateway works on LHIND network without a key
print(f"API Base: {lrn_llm.API_BASE}")
print(f"Default Model: {lrn_llm.DEFAULT_MODEL}")
print(f"API Key configured: {bool(lrn_llm.API_KEY)}")

# %% [markdown]
# ## Step 1 — Reachability

# %%
r = await lrn_llm.ping()
print(f"✅ LLM reachable: {r['ok']}")
print(f"Model: {r['model']}")

# %% [markdown]
# ## Step 2 — The Weather Tool: Canonical Declaration
#
# This lesson teaches function calling across three LLM providers (OpenAI, Anthropic, Gemini). They all support the same tool-calling **pattern**, but they differ in the **shapes** of their requests and responses.
#
# Let's start with one canonical tool that represents a weather lookup. We'll then see how it translates to each provider's format.

# %%
from dataclasses import dataclass, asdict

@dataclass
class Tool:
    name: str
    description: str
    input_schema: dict
    strict: bool = True

# The canonical weather tool
WEATHER = Tool(
    name="get_weather",
    description="Use when the user asks about current conditions in a named city. Do not use for forecasts or historical weather data.",
    input_schema={
        "type": "object",
        "properties": {
            "city": {"type": "string"},
            "units": {"type": ["string", "null"], "enum": ["celsius", "fahrenheit"]},
        },
        "required": ["city", "units"],
        "additionalProperties": False,
    },
)

print("📋 Canonical Weather Tool:")
print(json.dumps(asdict(WEATHER), indent=2))

# %% [markdown]
# ## Step 3 — OpenAI Format: Declaration
#
# OpenAI wraps the tool in a `type: "function"` envelope. The schema field is called `parameters`. Strict mode is explicit.
#
# Let's call the LLM with this OpenAI-shaped tool declaration and see it in action.

# %%
def to_openai(tool: Tool) -> dict:
    return {
        "type": "function",
        "function": {
            "name": tool.name,
            "description": tool.description,
            "parameters": tool.input_schema,
            "strict": tool.strict,
        },
    }

openai_decl = to_openai(WEATHER)
print("🔧 OpenAI Declaration:")
print(json.dumps(openai_decl, indent=2))

# %% [markdown]
# ## Step 4 — Anthropic Format: Declaration
#
# Anthropic flattens the structure: no envelope, schema field is called `input_schema`, and strict mode is always on (schema is a contract).
#
# Let's also show the Anthropic declaration shape.

# %%
def to_anthropic(tool: Tool) -> dict:
    return {
        "name": tool.name,
        "description": tool.description,
        "input_schema": tool.input_schema,
    }

anthropic_decl = to_anthropic(WEATHER)
print("🔧 Anthropic Declaration:")
print(json.dumps(anthropic_decl, indent=2))

# %% [markdown]
# ## Step 5 — Gemini Format: Declaration
#
# Gemini nests tools under `functionDeclarations` and converts JSON Schema to OpenAPI 3.0 format. Notice how `"string"` becomes `"STRING"` (uppercase).
#
# Let's see the Gemini translation.

# %%
def _gemini_schema(node):
    """Recursively convert JSON Schema to Gemini's OpenAPI 3.0 subset."""
    if isinstance(node, dict):
        out = {}
        for k, v in node.items():
            if k == "additionalProperties":
                continue  # Gemini doesn't support this
            if k == "type" and isinstance(v, str):
                out["type"] = v.upper()  # "string" -> "STRING"
                continue
            out[k] = _gemini_schema(v)
        return out
    if isinstance(node, list):
        return [_gemini_schema(x) for x in node]
    return node

def to_gemini(tool: Tool) -> dict:
    return {
        "functionDeclarations": [
            {
                "name": tool.name,
                "description": tool.description,
                "parameters": _gemini_schema(tool.input_schema),
            }
        ]
    }

gemini_decl = to_gemini(WEATHER)
print("🔧 Gemini Declaration:")
print(json.dumps(gemini_decl, indent=2))

# %% [markdown]
# ## Step 6 — Parsing Responses: The Universal Call
#
# Once the model returns a tool call, each provider shapes it differently. The key insight: **same semantics, different envelope**. We extract `id`, `name`, and `args` from each shape into one canonical `Call` object.

# %%
@dataclass
class Call:
    id: str
    name: str
    args: dict

# Hand-crafted OpenAI response (as if the model called get_weather)
OPENAI_RESPONSE = {
    "choices": [
        {
            "message": {
                "role": "assistant",
                "content": None,
                "tool_calls": [
                    {
                        "id": "call_abc123",
                        "type": "function",
                        "function": {
                            "name": "get_weather",
                            "arguments": '{"city":"Bengaluru","units":"celsius"}',
                        },
                    }
                ],
            },
            "finish_reason": "tool_calls",
        }
    ]
}

def parse_openai(resp: dict):
    msg = resp["choices"][0]["message"]
    calls = []
    for tc in msg.get("tool_calls", []):
        fn = tc["function"]
        calls.append(Call(id=tc["id"], name=fn["name"], args=json.loads(fn["arguments"])))
    return calls

openai_call = parse_openai(OPENAI_RESPONSE)[0]
print(f"📤 OpenAI Call: {openai_call}")
print(f"  - Arguments were JSON STRING: {repr(OPENAI_RESPONSE['choices'][0]['message']['tool_calls'][0]['function']['arguments'])}")

# %% [markdown]
# ## Step 7 — Anthropic Response Parsing
#
# Anthropic returns tool calls as `content[]` blocks of type `tool_use`. Arguments come pre-parsed as a Python dict, not a string.

# %%
# Hand-crafted Anthropic response
ANTHROPIC_RESPONSE = {
    "id": "msg_01",
    "type": "message",
    "role": "assistant",
    "content": [
        {"type": "text", "text": "Looking that up."},
        {
            "type": "tool_use",
            "id": "toolu_xyz789",
            "name": "get_weather",
            "input": {"city": "Bengaluru", "units": "celsius"},
        },
    ],
    "stop_reason": "tool_use",
}

def parse_anthropic(resp: dict):
    calls = []
    for block in resp.get("content", []):
        if block.get("type") == "tool_use":
            calls.append(Call(id=block["id"], name=block["name"], args=block["input"]))
    return calls

anthropic_call = parse_anthropic(ANTHROPIC_RESPONSE)[0]
print(f"📤 Anthropic Call: {anthropic_call}")
print(f"  - Arguments were already OBJECT: {type(ANTHROPIC_RESPONSE['content'][1]['input']).__name__}")

# %% [markdown]
# ## Step 8 — Gemini Response Parsing
#
# Gemini nests tool calls in `candidates[0].content.parts[]`. The id is a unique correlator for parallel calls (since Gemini 3).

# %%
# Hand-crafted Gemini response
GEMINI_RESPONSE = {
    "candidates": [
        {
            "content": {
                "role": "model",
                "parts": [
                    {
                        "functionCall": {
                            "id": "fc-9a3d",
                            "name": "get_weather",
                            "args": {"city": "Bengaluru", "units": "celsius"},
                        }
                    }
                ],
            },
            "finishReason": "STOP",
        }
    ]
}

def parse_gemini(resp: dict):
    calls = []
    for part in resp["candidates"][0]["content"].get("parts", []):
        if "functionCall" in part:
            fc = part["functionCall"]
            calls.append(Call(id=fc.get("id", ""), name=fc["name"], args=fc["args"]))
    return calls

gemini_call = parse_gemini(GEMINI_RESPONSE)[0]
print(f"📤 Gemini Call: {gemini_call}")
print(f"  - Arguments were OBJECT (like Anthropic)")

# %% [markdown]
# ## Step 9 — Equivalence: Same Semantics Across Providers
#
# Despite different wire formats, all three calls carry the same semantic payload: the tool name, arguments, and a correlation id.

# %%
print("📊 Three providers, one meaning:")
print(f"  OpenAI call:    {openai_call}")
print(f"  Anthropic call: {anthropic_call}")
print(f"  Gemini call:    {gemini_call}")
print()
print("✅ Same tool name?")
all_names = {openai_call.name, anthropic_call.name, gemini_call.name}
print(f"   {all_names} → unique: {len(all_names) == 1}")
print()
print("✅ Same arguments?")
openai_args_json = json.dumps(openai_call.args, sort_keys=True)
anthropic_args_json = json.dumps(anthropic_call.args, sort_keys=True)
gemini_args_json = json.dumps(gemini_call.args, sort_keys=True)
print(f"   OpenAI:    {openai_args_json}")
print(f"   Anthropic: {anthropic_args_json}")
print(f"   Gemini:    {gemini_args_json}")
all_args = {openai_args_json, anthropic_args_json, gemini_args_json}
print(f"   → unique: {len(all_args) == 1}")

# %% [markdown]
# ## Step 10 — `tool_choice`: Forcing, Forbidding, Auto-picking
#
# Each provider offers modes to control whether the model calls a tool: auto (default), required (must call), none (forbid), or force (specific tool). The names and structures differ.

# %%
from dataclasses import dataclass

@dataclass
class ToolChoice:
    mode: str  # "auto", "none", "required", "force"
    tool_name: str | None = None

def tool_choice_openai(tc: ToolChoice):
    if tc.mode == "auto":
        return "auto"
    if tc.mode == "none":
        return "none"
    if tc.mode == "required":
        return "required"
    if tc.mode == "force":
        return {"type": "function", "function": {"name": tc.tool_name}}
    raise ValueError(tc.mode)

def tool_choice_anthropic(tc: ToolChoice):
    if tc.mode == "auto":
        return {"type": "auto"}
    if tc.mode == "none":
        return {"type": "none"}
    if tc.mode == "required":
        return {"type": "any"}
    if tc.mode == "force":
        return {"type": "tool", "name": tc.tool_name}
    raise ValueError(tc.mode)

def tool_choice_gemini(tc: ToolChoice):
    mode_map = {"auto": "AUTO", "none": "NONE", "required": "ANY"}
    if tc.mode in mode_map:
        return {"function_calling_config": {"mode": mode_map[tc.mode]}}
    if tc.mode == "force":
        return {
            "function_calling_config": {
                "mode": "ANY",
                "allowed_function_names": [tc.tool_name],
            }
        }
    raise ValueError(tc.mode)

print("🎛️  tool_choice: Force the model to call get_weather\n")
tc = ToolChoice(mode="force", tool_name="get_weather")
print(f"OpenAI:")
print(f"  {json.dumps(tool_choice_openai(tc))}")
print(f"\nAnthropic:")
print(f"  {json.dumps(tool_choice_anthropic(tc))}")
print(f"\nGemini:")
print(f"  {json.dumps(tool_choice_gemini(tc))}")

# %% [markdown]
# ## Step 11 — Real LLM Call with Tools (OpenAI Format)
#
# Now let's make a real call to the LLM using the weather tool in OpenAI's format. We'll ask it what the weather is in a city, and the model will return a tool call.

# %%
# Real LLM call with tools in OpenAI format
messages = [{"role": "user", "content": "What is the current weather in Paris? Use Celsius."}]

response = await lrn_llm.call(
    messages,
    system="You are a helpful assistant with access to a weather tool. When asked about weather, use the get_weather function.",
    max_tokens=400,
)

print("📨 Full LLM Response:")
print(json.dumps(response, indent=2)[:500] + "...")
print()
print("📤 Extracted Call (OpenAI parse):")
if response.get("choices") and response["choices"][0].get("message", {}).get("tool_calls"):
    calls = parse_openai(response)
    if calls:
        print(f"  {calls[0]}")
    else:
        print("  (no tool calls returned)")
else:
    print("  (no tool_calls in response; model may not have called the tool)")

# %% [markdown]
# ## Step 12 — Key Takeaway: Provider Portability
#
# The three providers converged on the **tool-calling pattern** (declare tools, model picks them, you call them and inject results) but diverged on **field names and nesting**. A production strategy:

# %%
print("🎯 Three-Provider Portability Checklist:\n")
print("1️⃣  DECLARATION (shape differences):")
print("   OpenAI:    {'type': 'function', 'function': {...}}")
print("   Anthropic: {'name': ..., 'input_schema': ...}")
print("   Gemini:    {'functionDeclarations': [...]} with uppercase types")
print()
print("2️⃣  RESPONSE PARSING (where the call lives):")
print("   OpenAI:    choices[0].message.tool_calls[].function")
print("   Anthropic: content[].tool_use.input (args already parsed)")
print("   Gemini:    candidates[0].content.parts[].functionCall")
print()
print("3️⃣  ARGUMENTS FORMAT:")
print("   OpenAI:    JSON STRING → must parse")
print("   Anthropic: Python dict (pre-parsed)")
print("   Gemini:    Python dict (pre-parsed)")
print()
print("4️⃣  ID PREFIXES (for correlation):")
print("   OpenAI:    call_...")
print("   Anthropic: toolu_...")
print("   Gemini:    UUID or fc-...")
print()
print("5️⃣  FORCE A TOOL (tool_choice modes):")
print("   OpenAI:    {type: 'function', function: {name: ...}}")
print("   Anthropic: {type: 'tool', name: ...}")
print("   Gemini:    {function_calling_config: {mode: 'ANY', allowed_function_names: [...]}}")

# %% [markdown]
# ## Step 13 — Limits & Error Behavior
#
# Each provider enforces different hard limits and error signatures when you exceed them.

# %%
print("⚠️  Provider Limits (2026 spec):\n")
print("OpenAI:")
print("  - Max tools per request: 128")
print("  - Schema depth: 5")
print("  - Argument string: ≤ 8192 bytes")
print("  - Strict mode: no $ref, no oneOf/anyOf/allOf overlap, every property in required")
print()
print("Anthropic:")
print("  - Max tools per request: 64")
print("  - Schema depth: ~10 practical limit (unbounded spec)")
print("  - No strict-mode flag; schema is always a contract")
print("  - disable_parallel_tool_use flag controls single vs multi-call")
print()
print("Gemini:")
print("  - Max functions per request: 64")
print("  - Uses OpenAPI 3.0 subset (enum on objects silently ignored)")
print("  - Gemini 3+: parallel calls with unique UUIDs for correlation")
print("  - responseSchema at request level, not per-tool")

# %% [markdown]
# ## Try It Yourself
#
# Edit the code below to experiment with different tool declarations or prompts. Try adding another tool (e.g., `forecast_weather`) and see how each provider would represent both tools.

# %%
# TODO: Extend the weather tool or add a new tool
# Example: add a 'forecast_weather' tool with date parameter
# Then translate it to OpenAI, Anthropic, and Gemini formats

# Uncomment and modify:
# FORECAST = Tool(
#     name="forecast_weather",
#     description="Get a 7-day forecast for a city.",
#     input_schema={
#         "type": "object",
#         "properties": {
#             "city": {"type": "string"},
#             "days": {"type": "integer", "minimum": 1, "maximum": 7},
#         },
#         "required": ["city", "days"],
#     },
# )
# print("OpenAI Forecast:")
# print(json.dumps(to_openai(FORECAST), indent=2))

print("(Try adding another tool and translating it to all three formats!)")
