# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/19-capstone-projects/21-tool-registry-schema-validation
# Used in courses: AI-02
# Framework: stdlib
# Requires API key: False

"""notebook.ai-02.py"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "/api/llm"  # same-origin proxy; server injects the gateway key
lrn_llm.DEFAULT_MODEL = "azure/gpt-5.4"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    _key = lrn_llm.API_KEY
    if _key:
        headers["Authorization"] = "Bearer " + _key
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key

# %%
lrn_llm.API_KEY = ""  # optional; set your key here if needed
print(f"Endpoint: {lrn_llm.API_BASE}")
print(f"Model: {lrn_llm.DEFAULT_MODEL}")
print(f"Key configured: {'Yes' if lrn_llm.API_KEY else 'No (using gateway default)'}")

# %% [markdown]
# ## Step 1 — Reachability

# %%
r = await lrn_llm.ping()
print(f"✅ LLM erreichbar · {r['model']}" if r['ok'] else f"❌ LLM nicht erreichbar")

# %% [markdown]
# ## Step 2 — Build the ToolRegistry
#
# We'll implement the core registry classes and validator functions from the lesson. The validator checks argument objects against JSON Schema 2020-12 subset and returns either `Ok()` or a list of `ValidationError` with JSON Pointer paths.

# %%
import re
from dataclasses import dataclass
from typing import Any, Callable

PRIMITIVE_TYPE_MAP = {
    "string": (str,),
    "integer": (int,),
    "number": (int, float),
    "boolean": (bool,),
    "object": (dict,),
    "array": (list,),
    "null": (type(None),),
}

@dataclass
class ValidationError:
    path: str
    keyword: str
    message: str
    def to_dict(self):
        return {"path": self.path, "keyword": self.keyword, "message": self.message}

@dataclass
class Ok:
    pass

def _type_matches(value: Any, expected: str) -> bool:
    types = PRIMITIVE_TYPE_MAP[expected]
    if expected == "boolean":
        return isinstance(value, bool)
    if expected in ("integer", "number"):
        if isinstance(value, bool):
            return False
        return isinstance(value, types)
    return isinstance(value, types)

def _path(prefix: str, segment: str | int) -> str:
    seg = str(segment).replace("~", "~0").replace("/", "~1")
    return f"{prefix}/{seg}"

def _walk(schema: dict, value: Any, path: str, errs: list) -> None:
    t = schema.get("type")
    if t is not None and not _type_matches(value, t):
        errs.append(ValidationError(path=path or "/", keyword="type",
                                    message=f"expected {t}, got {type(value).__name__}"))
        return
    if "enum" in schema:
        if value not in schema["enum"]:
            errs.append(ValidationError(path=path or "/", keyword="enum",
                                        message=f"value {value!r} not in {schema['enum']!r}"))
            return
    if t == "string":
        if "minLength" in schema and len(value) < schema["minLength"]:
            errs.append(ValidationError(path=path or "/", keyword="minLength",
                                        message=f"length {len(value)} < minLength {schema['minLength']}"))
        if "maxLength" in schema and len(value) > schema["maxLength"]:
            errs.append(ValidationError(path=path or "/", keyword="maxLength",
                                        message=f"length {len(value)} > maxLength {schema['maxLength']}"))
        if "pattern" in schema:
            try:
                if not re.search(schema["pattern"], value):
                    errs.append(ValidationError(path=path or "/", keyword="pattern",
                                                message=f"value {value!r} does not match pattern {schema['pattern']!r}"))
            except re.error as exc:
                errs.append(ValidationError(path=path or "/", keyword="pattern",
                                            message=f"invalid regex: {exc}"))
    elif t == "object":
        required = schema.get("required", [])
        for req_name in required:
            if req_name not in value:
                errs.append(ValidationError(path=_path(path, req_name), keyword="required",
                                            message=f"missing required property {req_name!r}"))
        props = schema.get("properties", {})
        for prop_name, prop_value in value.items():
            if prop_name in props:
                _walk(props[prop_name], prop_value, _path(path, prop_name), errs)
    elif t == "array":
        items_schema = schema.get("items")
        if items_schema is not None:
            for idx, item in enumerate(value):
                _walk(items_schema, item, _path(path, idx), errs)

print("✅ Validator functions ready")

# %% [markdown]
# ## Step 3 — Define ToolRegistry Class
#
# The registry holds a typed collection of tools. Each tool has a name, schema, handler, and metadata. The `validate()` method returns `Ok()` if args match the schema, or a list of `ValidationError` objects with JSON Pointer paths.

# %%
class ToolRegistry:
    """Name-keyed table of tool records with schema validation."""
    _NAME_RE = re.compile(r"^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)*$")
    def __init__(self):
        self._records = {}
        self._order = []
    def register(self, name, schema, handler, description="", idempotent=False, override=False):
        if not self._NAME_RE.match(name):
            raise ValueError(f"tool name {name!r} must match {self._NAME_RE.pattern}")
        if name in self._records and not override:
            raise ValueError(f"tool {name!r} already registered; pass override=True to replace")
        if name not in self._records:
            self._order.append(name)
        self._records[name] = {"name": name, "schema": schema, "handler": handler,
                               "description": description, "idempotent": idempotent}
        return self._records[name]
    def get(self, name: str):
        if name not in self._records:
            raise KeyError(f"unknown tool {name!r}")
        return self._records[name]
    def validate(self, name: str, args: Any):
        rec = self.get(name)
        errors = []
        _walk(rec["schema"], args, "", errors)
        return Ok() if not errors else errors
    def names(self):
        return list(self._order)

print("✅ ToolRegistry class ready")

# %% [markdown]
# ## Step 4 — Register a Tool: db.get_user
#
# Let's register the lesson's example tool. It fetches a user from a database by id, with optional field filtering. The schema specifies that `id` is required and must be an integer, and `fields` (if provided) must be an array of strings from an enum.

# %%
registry = ToolRegistry()

def get_user(id: int, fields=None):
    """Fetch user record by id. Returns simulated user data."""
    users = {1: {"id": 1, "name": "Alice", "email": "alice@example.com"},
             2: {"id": 2, "name": "Bob", "email": "bob@example.com"}}
    user = users.get(id, {})
    if fields:
        return {k: user[k] for k in fields if k in user}
    return user

registry.register(
    name="db.get_user",
    description="Fetch a user record by id.",
    schema={
        "type": "object",
        "required": ["id"],
        "properties": {
            "id": {"type": "integer"},
            "fields": {
                "type": "array",
                "items": {"type": "string", "enum": ["id", "name", "email"]},
            },
        },
    },
    handler=get_user,
    idempotent=True,
)

print(f"✅ Registered tool: {registry.names()}")
print(f"   Schema: {json.dumps(registry.get('db.get_user')['schema'], indent=2)}")

# %% [markdown]
# ## Step 5 — Validation Success
#
# Let's test a valid argument set. The validator checks that `id` is an integer and `fields` (if present) contains only allowed strings.

# %%
valid_args = {"id": 1, "fields": ["id", "name"]}
result = registry.validate("db.get_user", valid_args)
print(f"Args: {valid_args}")
print(f"Result: {'✅ Ok()' if isinstance(result, Ok) else result}")

# %% [markdown]
# ## Step 6 — Validation Failure: Wrong Type
#
# Now let's pass `id` as a string instead of an integer. The validator returns an error with the JSON Pointer path `/id`.

# %%
invalid_type = {"id": "forty-two"}
result = registry.validate("db.get_user", invalid_type)
print(f"Args: {invalid_type}")
if not isinstance(result, Ok):
    for err in result:
        print(f"  Error: {err.to_dict()}")

# %% [markdown]
# ## Step 7 — Validation Failure: Missing Required Field
#
# Here we omit the required `id` field. The validator reports the path `/id` with keyword `required`.

# %%
missing_required = {"fields": ["name"]}
result = registry.validate("db.get_user", missing_required)
print(f"Args: {missing_required}")
if not isinstance(result, Ok):
    for err in result:
        print(f"  Error: {err.to_dict()}")

# %% [markdown]
# ## Step 8 — Validation Failure: Enum Constraint
#
# Now we pass `fields` with a value not in the allowed enum. The validator catches the invalid field name `phone` at path `/fields/1`.

# %%
invalid_enum = {"id": 1, "fields": ["id", "phone"]}
result = registry.validate("db.get_user", invalid_enum)
print(f"Args: {invalid_enum}")
if not isinstance(result, Ok):
    for err in result:
        print(f"  Error: {err.to_dict()}")

# %% [markdown]
# ## Step 9 — LLM Reads Validation Errors and Self-Corrects
#
# Let's send a validation error report to the LLM and ask it to fix the arguments. This demonstrates how an agent would use the registry: try to call a tool, get precise error paths, and let the model self-correct in one round trip.

# %%
bad_args = {"id": "alice", "fields": ["id", "phone", "address"]}
errors = registry.validate("db.get_user", bad_args)

error_report = f"""Tool: db.get_user
Attempted args: {json.dumps(bad_args)}
Validation errors:
"""
if not isinstance(errors, Ok):
    for err in errors:
        error_report += f"  - {err.path}: [{err.keyword}] {err.message}\n"

print("Validation errors for LLM:")
print(error_report)

# %%
system_prompt = """You are an agent assistant. You help fix tool arguments based on schema validation errors.
You read the error paths and messages, understand what's wrong, and suggest corrected arguments.
Always output ONLY a valid JSON object, no markdown or explanation."""

user_message = f"""{error_report}
What are the corrected arguments?"""

response = await lrn_llm.call(
    [{"role": "user", "content": user_message}],
    system=system_prompt,
    max_tokens=200
)

response_text = lrn_llm.text(response)
print("LLM response:")
print(response_text)

try:
    corrected_args = json.loads(response_text)
    print(f"\nCorrected args: {corrected_args}")
    
    # Validate the corrected args
    result = registry.validate("db.get_user", corrected_args)
    if isinstance(result, Ok):
        print("✅ Corrected arguments are valid!")
    else:
        print(f"❌ Still has errors: {[e.to_dict() for e in result]}")
except json.JSONDecodeError:
    print("Could not parse JSON from LLM response")

# %% [markdown]
# ## Step 10 — Registration Override Protection
#
# The registry prevents accidental re-registration. If you try to register the same tool twice, it raises an error unless you pass `override=True`. This is operational hygiene—silent overwrites are how tool catalogs drift in production.

# %%
# Try to register db.get_user again without override
try:
    registry.register(
        name="db.get_user",
        schema={"type": "object"},
        handler=lambda: None,
        override=False
    )
    print("❌ Should have raised ValueError")
except ValueError as e:
    print(f"✅ Registration protection works: {e}")

# Now with override=True
registry.register(
    name="db.get_user",
    schema={"type": "object"},
    handler=lambda: None,
    override=True
)
print(f"✅ Override successful. Registry now has: {registry.names()}")

# %% [markdown]
# ## Try it yourself
#
# Edit the tool schema and arguments below to experiment with validation. Try:
# - Adding a new required field
# - Changing minLength or maxLength on a string
# - Adding a pattern (regex) constraint
# - Creating your own tool and registering it
#
# Then ask the LLM to validate your schema against some test arguments.

# %%
# TODO: Design your own tool schema. Example: a search function with query string and result limit.
# Then register it and test validation with the LLM.

# For now, let's create a simple email validation tool as an example:
my_schema = {
    "type": "object",
    "required": ["email", "subscribe"],
    "properties": {
        "email": {
            "type": "string",
            "pattern": r"^[\w.-]+@[\w.-]+\.\w+$",  # basic email regex
            "minLength": 5,
            "maxLength": 100
        },
        "subscribe": {"type": "boolean"},
        "tags": {
            "type": "array",
            "items": {"type": "string", "enum": ["news", "updates", "offers"]}
        }
    }
}

registry.register(
    name="user.signup",
    description="Sign up a user with email and preferences.",
    schema=my_schema,
    handler=lambda **kw: {"status": "ok"},
    override=False
)

print("Registered: user.signup")
print(f"\nTry these test args:")
test_cases = [
    {"email": "alice@example.com", "subscribe": True},
    {"email": "invalid", "subscribe": True},
    {"email": "bob@example.com", "subscribe": True, "tags": ["news", "spam"]},
]
for i, args in enumerate(test_cases, 1):
    result = registry.validate("user.signup", args)
    status = "✅" if isinstance(result, Ok) else "❌"
    print(f"{status} Case {i}: {args}")
    if not isinstance(result, Ok):
        for err in result:
            print(f"     {err.path}: {err.message}")
