# AUTOGENERATED — do not hand-edit; rerun audit workflow.
# Lesson: phases/19-capstone-projects/24-plan-execute-control-flow
# Used in courses: AI-02
# Framework: vanilla-openai
# Requires API key: False

"""notebook.ai-02.py"""

# %%
import sys, json, types
lrn_llm = types.ModuleType("lrn_llm")
try:
    from pyodide.http import pyfetch as _pyfetch
    _IN_PYODIDE = True
except ImportError:
    import urllib.request as _urlreq
    _IN_PYODIDE = False
lrn_llm.API_BASE = "https://gateway.lhind.ai/v1"
lrn_llm.DEFAULT_MODEL = "azure/gpt-4o"
lrn_llm.API_KEY = ""  # optional; set in Step 0a

async def _lrn_call(messages, *, system=None, max_tokens=400, model=None):
    if system is not None:
        messages = [{"role": "system", "content": system}] + list(messages)
    payload = {"model": model or lrn_llm.DEFAULT_MODEL, "messages": messages,
               "max_completion_tokens": max_tokens}
    headers = {"content-type": "application/json"}
    if lrn_llm.API_KEY:
        headers["Authorization"] = "Bearer " + lrn_llm.API_KEY
    url = lrn_llm.API_BASE.rstrip("/") + "/chat/completions"
    body = json.dumps(payload)
    if _IN_PYODIDE:
        r = await _pyfetch(url, method="POST", headers=headers, body=body)
        data = await r.json()
    else:
        req = _urlreq.Request(url, method="POST", headers=headers, data=body.encode("utf-8"))
        with _urlreq.urlopen(req, timeout=60) as r:
            data = json.loads(r.read())
    if "error" in data:
        raise RuntimeError("LLM error: " + str(data["error"]))
    return data

def _lrn_text(r):
    ch = (r or {}).get("choices") or []
    return (ch[0].get("message", {}) or {}).get("content", "") if ch else ""

async def _lrn_ping():
    r = await _lrn_call([{"role": "user", "content": "Reply with exactly: OK"}], max_tokens=5)
    return {"ok": _lrn_text(r).strip().upper().startswith("OK"), "model": r.get("model")}

lrn_llm.call = _lrn_call
lrn_llm.text = _lrn_text
lrn_llm.ping = _lrn_ping
print("✅ notebook ready · endpoint:", lrn_llm.API_BASE)

# %% [markdown]
# ## Step 0a — Endpoint & Key
#
# Optionally set an API key. The LHIND gateway works without a key on the internal network.

# %%
lrn_llm.API_KEY = ""  # leave empty for LHIND network; set if needed
print(f"🔌 Endpoint: {lrn_llm.API_BASE}")
print(f"📊 Model: {lrn_llm.DEFAULT_MODEL}")
print(f"🔑 Key set: {bool(lrn_llm.API_KEY)}")

# %% [markdown]
# ## Step 1 — Reachability
#
# Test that the LLM endpoint is reachable.

# %%
r = await lrn_llm.ping()
print("✅ LLM erreichbar", r)

# %% [markdown]
# ## Step 2 — The Plan-Execute Agent Pattern
#
# A plan-execute agent separates planning from execution. The planner generates a list of steps, the executor runs them sequentially, and on failure the planner gets a chance to revise the plan.
#
# This lesson teaches the shape of a plan, how execution handles failures, and how replanning works.
#
# ### Key Concepts
#
# **Step**: A structured action with a tool name, arguments, and expected outcome.
#
# **Plan**: An ordered list of steps generated by the planner.
#
# **Replan**: When a step fails, the executor passes the error back to the planner, which can emit a revised plan.

# %%
from dataclasses import dataclass
from typing import Any
import json

@dataclass
class Step:
    id: int
    tool_name: str
    args: dict
    expected_outcome: str
    result: Any | None = None
    error: str | None = None

print("✅ Step defined")
print("Example: Step(id=1, tool_name='fetch', args={'key': 'input'}, expected_outcome='loaded user input')")

# %% [markdown]
# ## Step 3 — The Planner: LLM Generates a Plan
#
# The planner is a function that takes a goal, the history of executed steps, and the last error (if any) and returns a list of steps.
#
# Here we call the LLM to generate a plan. The LLM reasons about what steps are needed to accomplish the goal.

# %%
async def llm_planner(goal: str, history: list[Step], last_error: str | None) -> list[Step]:
    """Call the LLM to generate a plan."""
    history_text = ""
    if history:
        history_text = "\n\nPrevious steps executed:\n"
        for s in history:
            status = "OK" if s.error is None else f"FAILED: {s.error}"
            history_text += f"  - Step {s.id} ({s.tool_name}): {status}\n"
    
    error_text = ""
    if last_error:
        error_text = f"\n\nMost recent error: {last_error}\nRevise the plan to work around this failure."
    
    prompt = f"""Generate a plan to accomplish: {goal}

You are planning steps for a data pipeline with these tools:
- fetch(key): Load input data from a key
- transform(mode): Transform data with v1 or v2 algorithm
- render(): Render transformed data to HTML
- submit(): Submit HTML to backend
- log_failure(why): Log a failure message
- notify_user(): Notify user of failure

Return a JSON array of steps. Each step is an object with:
{{"id": <int>, "tool": <tool_name>, "args": {{...}}, "outcome": "<what this step does>"}}

Constraints:
- Keep plans short (2-5 steps)
- Use sequential IDs starting from where history ended
- If last_error occurred, propose a recovery plan{error_text}{history_text}

Return ONLY the JSON array, no other text."""
    
    r = await lrn_llm.call(
        [{"role": "user", "content": prompt}],
        max_tokens=500
    )
    text = lrn_llm.text(r)
    try:
        steps_data = json.loads(text)
        return [Step(
            id=s["id"],
            tool_name=s["tool"],
            args=s.get("args", {}),
            expected_outcome=s.get("outcome", "")
        ) for s in steps_data]
    except (json.JSONDecodeError, KeyError) as e:
        print(f"Parse error: {e}")
        return []

print("✅ LLM planner defined")

# %% [markdown]
# ## Step 4 — The Executor: Run Each Step
#
# The executor takes a tool name and arguments and simulates running that tool. In a real system, this would call actual services (databases, APIs, rendering engines, etc.).
#
# Here we simulate a simple pipeline with these behaviors:
# - **fetch**: Returns mock input data
# - **transform**: Can fail on mode v1 (simulating a backend service down)
# - **render**: Returns HTML string
# - **submit**: Returns a submission ID
# - **log_failure** and **notify_user**: Return success
#
# The simulated failure on transform v1 forces the replanning path.

# %%
class ToolFailure(Exception):
    pass

def tool_executor(tool: str, args: dict) -> Any:
    """Simulate execution of a tool."""
    if tool == "fetch":
        return {"status": "fetched", "data": {"name": "report", "entries": 42}}
    elif tool == "transform":
        mode = args.get("mode", "v1")
        if mode == "v1":
            # Simulate v1 backend being down
            raise ToolFailure("transform v1 backend temporarily unavailable")
        else:
            return {"status": "transformed", "mode": mode, "ready": True}
    elif tool == "render":
        return {"status": "rendered", "html": "<div>Report</div>"}
    elif tool == "submit":
        return {"status": "submitted", "id": 12345}
    elif tool == "log_failure":
        why = args.get("why", "unknown")
        return {"status": "logged", "why": why}
    elif tool == "notify_user":
        return {"status": "notified", "message": "Operation failed. Please try again."}
    else:
        raise ToolFailure(f"unknown tool: {tool}")

print("✅ Tool executor defined")
print("Behavior: transform v1 fails, forcing replanning to v2")

# %% [markdown]
# ## Step 5 — The Plan-Execute Loop
#
# The loop executes steps sequentially. On success, move to the next step. On failure:
# 1. If replan budget not exhausted, call the planner again with the error
# 2. If step budget exceeded, abort
# 3. Otherwise continue with the new plan
#
# This is the "control flow" part of the lesson.

# %%
async def plan_execute_loop(goal: str, max_steps: int = 12, max_replans: int = 2) -> dict:
    """Main loop: plan, execute, replan on failure."""
    history: list[Step] = []
    steps_taken = 0
    replans_used = 0
    last_error: str | None = None
    next_step_id = 1
    
    print(f"\n🎯 Goal: {goal}\n")
    
    # Initial plan
    plan = await llm_planner(goal, history, None)
    if not plan:
        return {"status": "failed", "reason": "no_plan", "history": []}
    
    print(f"📋 Initial plan ({len(plan)} steps):")
    for s in plan:
        print(f"  {s.id}. {s.tool_name}({s.args}) → {s.expected_outcome}")
    
    cursor = 0
    while cursor < len(plan):
        if steps_taken >= max_steps:
            print(f"\n❌ Step budget exceeded ({steps_taken} >= {max_steps})")
            return {"status": "failed", "reason": "step_budget", "history": history}
        
        step = plan[cursor]
        print(f"\n→ Executing: {step.tool_name}({step.args})")
        
        try:
            step.result = tool_executor(step.tool_name, step.args)
            print(f"  ✅ Result: {step.result}")
            history.append(step)
            cursor += 1
            steps_taken += 1
        except ToolFailure as e:
            step.error = str(e)
            print(f"  ❌ Error: {step.error}")
            history.append(step)
            steps_taken += 1
            last_error = step.error
            
            if replans_used >= max_replans:
                print(f"\n❌ Replan budget exhausted ({replans_used} >= {max_replans})")
                return {"status": "failed", "reason": "replan_budget", "history": history}
            
            replans_used += 1
            print(f"\n🔄 Replanning (attempt {replans_used})...")
            new_plan = await llm_planner(goal, history, last_error)
            if not new_plan:
                print(f"\n❌ Planner returned empty plan")
                return {"status": "failed", "reason": "no_plan", "history": history}
            
            print(f"📋 Revised plan ({len(new_plan)} steps):")
            for s in new_plan:
                print(f"  {s.id}. {s.tool_name}({s.args}) → {s.expected_outcome}")
            
            plan = new_plan
            cursor = 0
    
    print(f"\n✅ Goal achieved after {steps_taken} steps and {replans_used} replans")
    return {
        "status": "completed",
        "reason": "goal_met",
        "history": history,
        "steps_taken": steps_taken,
        "replans_used": replans_used
    }

print("✅ Plan-execute loop defined")

# %% [markdown]
# ## Step 6 — Run the Agent: Data Pipeline Goal
#
# Let's run the agent on the data pipeline goal from the lesson: **"ship the report"**.
#
# The agent will plan steps (fetch, transform, render, submit), and when transform v1 fails, it will replan to use v2 instead.

# %%
result = await plan_execute_loop(
    goal="ship the report",
    max_steps=12,
    max_replans=2
)

print(f"\n📊 Session Result:")
print(f"  Status: {result['status']}")
print(f"  Reason: {result['reason']}")
print(f"  Steps taken: {result.get('steps_taken', len(result['history']))}")
print(f"  Replans used: {result.get('replans_used', 0)}")
print(f"  History length: {len(result['history'])}")

# %% [markdown]
# ## Step 7 — Inspect the History
#
# The history shows every step that was executed, including errors. This is what a tracer or UI would use to display progress and debug failures.

# %%
print("\n📜 Execution History:")
for i, step in enumerate(result["history"], 1):
    status = "✅" if step.error is None else "❌"
    result_text = "(no result)" if step.result is None else f"→ {step.result}"
    error_text = "" if step.error is None else f" | Error: {step.error}"
    print(f"{i}. Step {step.id}: {status} {step.tool_name} {step.args}")
    print(f"   {result_text}{error_text}")

# %% [markdown]
# ## Try It Yourself
#
# Modify the goal or the executor to experiment with the plan-execute-replan loop. For example:
#
# - Change the goal to something different (e.g., "process and store the data")
# - Modify which step fails in the executor
# - Adjust max_steps and max_replans to see budget enforcement
#
# TODO: Try calling the loop with a different goal and observe how the LLM planner adapts.

# %%
# TODO: Experiment here
# Uncomment and modify to test:

# result2 = await plan_execute_loop(
#     goal="process and validate the dataset",
#     max_steps=15,
#     max_replans=3
# )
# print(f"Status: {result2['status']}")

print("✅ Ready for experimentation. Uncomment the code above and modify as desired.")
